### ISSUE TITLE
Strange behaviour of ~

### ISSUE THREAD

**Issue by frankluebeck** [gap-system/gap#1049]
### Observed behaviour
```
gap> a~ := 1;
Syntax error: ; expected
a~ := 1;
 ^
gap> ~a := 1;
Syntax error: ; expected
~a := 1;
 ^
gap> ~ := 1;
1
gap> l := [2, ~];
[ 2, ~ ]
gap> l = l[2];
true
```
### Expected behaviour
The assignment `~ := 1;` should lead to the same syntax error as the first examples.
### Copy and paste GAP banner (to tell us about your setup)
Seems that this has been in all version of GAP4 (and also in GAP3, where only the last line behaves differently).

**Comment by ChrisJefferson** [comment]
Some other bad places we can put `~`  (noting them, while I look around)

`f := function() local a,~,b; end;`

`f := function(a,~) end;` and `~ -> ~`

**Comment by ChrisJefferson** [comment]
This is tricky to fix, without possibly slowing GAP down -- the obvious places to fix it would involve putting code in places that have to be fast.

I'm investigating making `~` read-only from a user point of view (that would lead to a run-time error, rather than a parse-time error, but still stop it being written to).

**Comment by ChrisJefferson** [comment]
I have a fix for this, but it requires first merging #490 (just because they touch the same code, so there would be a merge conflict otherwise).
