### ISSUE TITLE
Can we run (some) manual tests on travis?

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1076]
The examples from the manual add a lot of coverage. It would be nice if we could run some or even all of them on travis (I have no idea how expensiv they are).

I guess the first step for this would be to improve the way we handle them. Right now, there is a relatively convoluted rule in the primary Makefile, which runs some GAP scripts (`doc/ref/extractexamples.g`, `doc/ref/runexamples.g`, and the same for `doc/tut`) and restarts GAP for each chapter. It also runs the tests three times, once starting GAP normally, once with option `-A`, and once with a `LoadAllPackage()` call added in.

I think we should instead have these scripts in tst; one script which takes one of the manuals (doc/ref, doc/tut, in the future perhaps also doc/dev), and extracts all examples from it into a subdir, say `tst/doc/ref` or `tst/doc-examples/ref` (and the same for tut). Initially, this would create one .tst file pr chapter, but of course we could revise it.

Afterwards, we can just use `TestDirectory` to run the tests. This way, we unify the way the tests are run, and can investigate how long the tests of each chapter take; we could then add one or multiple travis builds which run the examples of different subsets of the chapters (covering as many as possibly, ideally all).

Note: Restarting GAP between chapters might still be advisable, in that case we'd not use`TestDirectory`, but the rest of what I said would stay valid, I think.

**Comment by markuspf** [comment]
I am all for it.

Just to clarify: Do you want to extract the manual examples and commit the test files to the git repository, or do you want to extract them when the test is run?

**Comment by fingolfin** [comment]
The latter, so that they are always in sync with the manual.

**Comment by alex-konovalov** [comment]
I have some thoughts - will write later.

**Comment by ChrisJefferson** [comment]
I will not have time to work on this, but if any technical issues arise with the profiling itself, let me know and I am happy to add new functionality as required (where possible of course!)

**Comment by markuspf** [comment]
Doesn't seem to be too hard to do, I'll try myself a PR.

**Comment by markuspf** [comment]
I might regret asking this, but does there already exist some automation to give filenames to the documentation scraper? At the moment it seems filenames are recorded in `makedocreldata.g`...

**Comment by fingolfin** [comment]
@markuspf You mean, like, instead of listing every. single. file. you want to be able to say something like `everything in lib`? Well, `AutoDoc` does that for you.... Now, I am not suggesting to use `AutoDoc` here, but doing this is quite easy, and you could borrow from AutoDoc (code or inspiration). 

Or perhaps you meant something else, then please clarify.

**Comment by markuspf** [comment]
No I mean exactly this, can you point me to the function in autodoc that can inspire me?

**Comment by fingolfin** [comment]
It's `AUTODOC_FindMatchingFiles` and I just see that the `utils` package also has `FindMatchingFiles` (based on the AutoDoc code)

**Comment by markuspf** [comment]
I might do a PR that puts this in the library (`FindMatchingFiles`)?

I shall have a look, it;d be unfortunate if we had this function in 3 places...

**Comment by fingolfin** [comment]
Well, the `FindMatchingFiles` in utils clearly is based on an older version of `AUTODOC_FindMatchingFiles`, which was the result of some refactoring there. As it is, I think `FindMatchingFiles` in `utils` is not very generic and hence not useful for most people (note that I did not submit it to `utils`, that was @sebasguts I think, and @cdwensley added it?)

And I just noticed that the latest `AUTODOC_FindMatchingFiles` in `AutoDoc` is also buggy, as it ignores the `extensions` argument, hardcoding a value instead (not sure how that happened).

Finally, I am still not sure even this version of the function, with bug fix included, is terribly useful for public consumption, so I'd be reluctant to add to GAP as a documented function... and if you add it to GAP as an undocumented function, then I'd still keep my version in `AutoDoc`, as I don't want to rely on undocumented APIs... :-)

**Comment by fingolfin** [comment]
Also, I would expect there to be some overlap with `TestDirectory`, as that also needs to collect all `.tst` files in a given directory.

I guess what I am saying is: Don't waste too much time polishing this and putting it in "nicely", rather just get something working for now...

**Comment by markuspf** [comment]
Looking at it, I would not want to put that function into GAP

I'd like to put in a more generic one, for instance one that can at least take a list of roots, and extensions, and then returns a list of filenames. We can leave it undocumented and prefix it with something in capital letters so we can tell people that it's their own fault if we yank it out again, but for purposes of extracting documentation this seems like the way to go.

**Comment by fingolfin** [comment]
Aye. But again: Don't let the hope for something perfect get in the way of having something that works, now (or at least: soon ;-). Also, it's dangerous to try and design the "ultimate" function for a problem if you don't have a bunch of real world instances of the problem you want to solve. Anyway, that all is not meant to discourage you from whatever you feel like doing, just some generic advice ;-)

**Comment by cdwensley** [comment]
When functions are transferred from a package Home to Utils, the implicit assumption is that they will be removed from Home at the next release. 
With transfers from AutoDoc (unlike other packages) it is perfectly possible for the two versions to continue indefinitely because of the different names, e.g. AutoDoc_FindMatchingFiles and FindMatchingFiles. 
This is a very undesirable situation, so I need to know whether to remove such functions from Utils or whether to expect some improved code.  Either way, it would be useful to raise an issue at https://github.com/gap-packages/utils/issues.  (It seems to me that Utils is a very suitable place for the function in question.)

**Comment by alex-konovalov** [comment]
There are no technical obstacles for adding the test of manual examples to pull requests. They do not take long time (15-30 minutes altogether to build GAP and packages and to run all three configurations - with all, without and with default packages). IIRC, once should be able test them on fly, with [`ExtractExamples`](https://www.gap-system.org/Manuals/pkg/GAPDoc-1.5.1/doc/chap5.html#X8337B2BC79253B3F) and [`RunExamples`](https://www.gap-system.org/Manuals/pkg/GAPDoc-1.5.1/doc/chap5.html#X781D56FC7B938DCB), and the diffs will be reported with their original locations (so I don't see why `FindMatchingFiles` could help here).

We require that examples within each chapter will look exactly as in the manual (with default packages) if they are being run in exactly the same order. That's why we do run each chapter in a separate GAP session.

The major difficulty is coming from the fact that they are not enough robust. It could happen that they look differently dependently which of the three configurations (with all, without or with default packages) is used. Because of that, when `make testmanuals` runs in Jenkins, the test is automatically failed if there are diffs in the version with default packages - but not in the two others. In the two other runs, there is only a periodic manual check that there are no errors. Diffs which are caused by randomness are just ignored. Sometimes, examples are fixed to make them more reproducible, but there are cases (especially in the tutorial) when that's hard - one may really want to show the output instead of suppressing it.

The question is what will we do when PR breaks manual examples:
- recommend the submitter to simply update examples to the new output?
- suggest how to change examples to make them more reproducible?
- merge the PR anyway, and fix examples later?

For each of these three options, there may be PRs where it will be most sensible.

**Comment by fingolfin** [comment]
@alex-konovalov All you say to me seems like something that strongly indicates that we absolutely *need* to (a) improve the manual examples to be more robust, and to (b) thest the them on Travis. 

Of course if a PR breaks a manual example, we may need to be flexible about that, and decide what to do, as you described. But it's much, much better to do and decide that while reviewing the PR, than doing it some time later, after the PR has merged.

So I really hope #1082 will be polished into something we can merge, and then we can all collaborate on improving the manual examples as needed. On the long run, it would also be nice if we could run the manual tests in all three variations -- but one step after the other.

**Comment by alex-konovalov** [comment]
@fingolfin 

> @alex-konovalov All you say to me seems like something that strongly indicates that we absolutely need to (a) improve the manual examples to be more robust, and to (b) thest the them on Travis.

Yes

> Of course if a PR breaks a manual example, we may need to be flexible about that, and decide what to do, as you described. But it's much, much better to do and decide that while reviewing the PR, than doing it some time later, after the PR has merged.

(+1)

> So I really hope #1082 will be polished into something we can merge, and then we can all collaborate on improving the manual examples as needed. On the long run, it would also be nice if we could run the manual tests in all three variations -- but one step after the other.

I would do it differently - starting from lightweight Travis test to run `make testmanuals-light` which will be produced from `make testmanuals-light` throwing away two other configurations and leaving only the 'stable' one with default set of packages. May try to submit an alternative PR in a couple of days.

**Comment by markuspf** [comment]
Can this be closed with #1082 merged?

**Comment by markuspf** [comment]
Looking again, maybe we should run the tutorial examples as well to make sure they work?

**Comment by alex-konovalov** [comment]
That may be useful to add. Note however that sometimes the point of the tutorial examples is to actually show **how does the output looks like** so one can not easily fix the test by suppressing output or checking some of its properties instead.

**Comment by alex-konovalov** [comment]
@markuspf looking again, let's add tutorial examples too!

**Comment by fingolfin** [comment]
What is the status of this? Does soembody still want to work on this?

**Comment by alex-konovalov** [comment]
Either add tests of examples for the tutorial, and polish those that are changeable due to randomness, or close this. Opinions?

**Comment by fingolfin** [comment]
I am closing this, as the original issue has been resolved long ago. If somebody wants to add tutorial examples, they are welcome to do so; and also welcome to open a fresh issue requesting it. But I think it's a bad idea to repurpose an existing resolved issue.
