### ISSUE TITLE
Command line: add GNU style "--long-name" alternatives for all options

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#11]
So we we would for example add `--help` as alias for `-h`, `--root-paths` for `-l`, and so on.

I think those are easier to remember, and in particular, easier to understand when reading a script invoking GAP that one wrote a long time ago. Of course the existing short names should stay for now to ensure compatibility. Though I think we might want to remove some of them eventually, so that we can repurpose them for more useful things in the distant future...

**Comment by ChrisJefferson** [comment]
Because there are no more short options, in GAP 4.8 I added support for long flags, but options current have to be long or short, not both. I'll have a look at how hard it would be to support both long and short flags.

Just in case one any suggests it -- I think trying to use one of the standard parsing libraries would be really hard, as GAP parses in two segments, first letting the C pick up what it understands, then giving the rest onto the GAP library to parse as it wants.

**Comment by frankluebeck** [comment]
On Wed, Mar 04, 2015 at 08:36:44AM -0800, Max Horn wrote:
> So we we would for example add `--help` as alias for `-h`,
> `--root-paths` for `-l`, and so on.

Originally, long options were not used because everything that would call 
'malloc' was avoided in the kernel (because of problems with GAPs own 
memory manager). But this is no longer a problem with the current GAP,
so that the introduction of long arguments (in addition and as alternatives
to the current short ones) is sensible. This should not be difficult to
implement.

**Comment by stevelinton** [comment]
I've labeled this "Agreed", basically meaning that anyone who wants to should feel free to implement it.

**Comment by ChrisJefferson** [comment]
WIP pull request at #43 . I think nothing too contraversal. If anyone wants a nicer looking help page, they could produce one (the code is entirely in GAP. If you want to do this don't use any methods like Length, this code is loaded before most of the standard library. Look at what is already used in this file).

**Comment by alex-konovalov** [comment]
@ChrisJefferson : your last comment refers to PR #43 but that's already merged PR on a completely different topic, not on command line options. Could you please post the right PR number, please?

**Comment by markuspf** [comment]
This has been resolved by merging #91 today. It should still be merged into hpcgap-default.
