### ISSUE TITLE
Remove randomness based on time

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#1129]
Several algorithms in GAP use `Runtime()` to run for a fixed amount of time. This makes comparing test results and code coverage difficult as the results keep changing.

Functions which do this include the following: The first of these is definitely causing us problems.

* `IsomorphismPermGroupOrFailFpGroup`, at `grpfp.gi:4036`, variable `t1`.
* `Omega_Sim`, at `grpprc.gi:2723`.
* `NEWTC_CosetEnumerator`, at `sgpres.gi:3155`.

The best thing would be to replace these with something more repeatable -- if we can't do that we could for the sake of tests have a way of disabling the `Runtime()` based behaviour.

**Comment by fingolfin** [comment]
Ouch! Never was aware of that. So if I run the computation with otherwise identical settings twice, I might get different results... if my students runs it on a different computer, they also may get different results... OK, of course this is always true due to an extent, but for other kinds of randomness, I can control it by setting the state of the RNG.

This is also a problem for testing, I'd say... In recog, there are various bugs that only occur very rarely, and I only was able to debug them because I could snapshot the RNG state. It would have been (even more of) a nightmare if it also depended on timing.

That said, I sure see that it makes sense to try a strategy for some time before switchting to another. Hrm.

**Comment by stevelinton** [comment]
@fingiolfin: That said, I sure see that it makes sense to try a strategy for some time before switchting to another. Hrm.

I'm inclined to agree and a lot of effort has gone into trying to judge how much effort is the right amount.  So I think we probably need to think in terms of adding features to these routines to facilitate testing and debugging. Maybe something to discover some measure of the number of iterations attempted, and then an option to do exactly that many regardless of Runtime() on a subsequent run.

**Comment by hulpke** [comment]
Sorry to only chime in now -- it is sometimes hard to identify topics in dozes of discussion threads on colors and package building.

The first and last of the examples are mine. In both cases the situation is a calculation that takes in the minute range, a wide variety of result quality, but trying to find a global maximum is prohibitvely expensive.

The algorithms thus search ``for a while'' -- so that the overall time does not get too worse -- whether they can find a local maximum.

How long it should try probably depends on the machine speed and on how long the calculation so far took (for the trials not to slow down beyond reason).

That said, the timing approach is ad-hoc, as I'm not aware of other features that let me gauge the ``real world'' cost. 

I would be happy to add to the code:
- An option to run a fixed number of iterations instead of time bound. Please suggest name and syntax
- Using other parameters provided by GAP to have a more stable number of iterations

[ Ceterum censeo: Generically (for tests and coverage) I argue that in such cases each possible result is equally good and we should not test on the explicit results produced, but only on properties of the results. The problem is wirth teh way we test, not with the code. ]

**Comment by ChrisJefferson** [comment]
@hulpke : I should have referred you to this thread explicitly when I saw your name in the code, sorry.

I think we want an option, and then we'll test both with the option on and off. In practice, the main place this is proving annoying is testing which lines of code are executed by the tests, rather the eventual results of those tests.

How about a `UserPreference` called `ReproducableBehaviour`:

This preference disables code in GAP which changes behaviour based on time spent, and therefore can produce different results depending on how much time is taken by other programs running on the same computer. This option may lead to slower or lower-quality results.

Note that many algorithms in GAP use the global random number generator, which is NOT affected by this option. This only tries to ensure the same version of GAP, with the same package versions loaded, on the same machine, running the same code, in a fresh GAP session, will produce the same results.

**Comment by fingolfin** [comment]
Can this be closed now?

**Comment by fingolfin** [comment]
@ChristopherRussell ping?

**Comment by ChrisJefferson** [comment]
The cases of this which don't involve HPC-GAP are I believe all now fixed.
