### ISSUE TITLE
minor glitch in reference manual

### ISSUE THREAD

**Issue by cdwensley** [gap-system/gap#1159]
The Index in the Reference manual has an entry "PCore" immediately after "OnTuplesTuples".

**Comment by alex-konovalov** [comment]
It says there `PCore, see PCore 39.11-3` and then below in the index there is a proper entry `PCore 39.11-3`. This comes from `lib/grp.gd`:
```
##  <#GAPDoc Label="PCore">
##  <ManSection>
##  <Oper Name="PCore" Arg='G, p'/>
##
##  <Description>
##  <Index Key="Op(G)" Subkey="see PCore"><C>PCore</C></Index>
```
The `Key` attribute specifies where to put this entry into the index, that's why it's under "O". Perhaps one should also replace `<C>PCore</C>` by `Op(G)`, i.e.
```
 <Index Key="Op(G)" Subkey="see PCore"><M>Op(G)</M></Index>
```
