### ISSUE TITLE
DisplayCompositionSeries test fails in morpheus.tst

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#1233]
Since a couple of days ago, this happens in the master branch both with and without loading packages:
```
########> Diff in /data/gap-jenkins/workspace/GAP-newbuild-test/GAPCOPTS/64bui\
ld/GAPTARGET/standard/label/kovacs/GAP-master-snapshot/tst/testinstall/morpheu\
s.tst:56
# Input is:
DisplayCompositionSeries(AutomorphismGroup(SymmetricGroup(3)));
# Expected output:
G (size 6)
 | Z(2)
S (1 gens, size 3)
 | Z(3)
1 (size 1)
# But found:
Group
 | Z(2)
Group
 | Z(3)
Group
########
```

**Comment by fingolfin** [comment]
But this does not happen on Travis, does it? Nor can I reproduce it locally... so what is different about the Jenkins setup?

**Comment by fingolfin** [comment]
Note that the above suggests that `GroupString` (which `DisplayCompositionSeries` uses to print the groups) for some reason changed behavior. But that operation has not been modified in years.

You say this happens with `-A`, i.e. without loading any packages (except GAPDoc). So that rules out my otherwise suspect number 1...

At this point, I cannot really say anything about this, as I have not found a way to reproduce it. Tests pass, on my machine and on Jenins, and also interactively it works fine:
```
$ bin/gap.sh -A -b
gap> DisplayCompositionSeries(AutomorphismGroup(SymmetricGroup(3)));
G (size 6)
 | Z(2)
S (1 gens, size 3)
 | Z(3)
1 (size 1)
gap> 
```

**Comment by alex-konovalov** [comment]
Does not happen any more.
