### ISSUE TITLE
CI coverage reports again experience random fluctuations

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1256]
Consider PR #1254, which touches no source files, yet still coverage changes. Namely in these files: (UPDATE: added more files, marked resolved files)

* [x] hpcgap/src/funcs.c
* [x] src/hpc/threadapi.c
* [x] hpcgap/src/vars.c
* [x] src/compiler.c
* [ ] hpcgap/lib/stdtasks.g
* [x] stc/stats.c

It would be good if we could avoid these fluctuations, as they lead to spurious coverage failures.

**Comment by ChrisJefferson** [comment]
The `src/compiler.c` issues are to do with us testing compiling mode. There are several layers of problems here:

1) The `StoreString` method doesn't work properly when we use it to handle `-U` (compiler options) -- it puts a pointer into a `char [256]`, which we then try to parse as a string (that's where the fluctuations come from).

2) Even if we fix it, it turns out we ignore the argument `-U` anyway, as we manually set the flags in `InitKernel` anyway.

3) Relatedly, the `-i` option (set GAP root file) has been broken since at least 4.7.2 (last version I have that compiles), for the same reason.

I suggest, seeing as `-U` and `-i` haven't done anything useful for years and no-body cared, just removing them (for the compiler, in practice we know the best options to set, and can just continue hard-wiring them, as always)

**Comment by ChrisJefferson** [comment]
This first issue (`-U`) is fixed in #1265. Once that gets merged, we can look to see if there are other issues as well.

**Comment by fingolfin** [comment]
@ChrisJefferson Great find! I traced this in the logs of the old repository, and the current command line parsing code was introduced 2002-10-23. So, yeah, it should be safe to remove (although at least `-i` would also be trivial to fix -- but I see no point in that, and freeing up one-letter command line args to me is a good thing).

**Comment by fingolfin** [comment]
And I just verified that at least `-i` was already broken in GAP 4.4.12:
```
~/Documents/gap4r4$ bin/gap.sh  -i lib/init.g
gap: hmm, I cannot find '�_�' maybe use option '-l <gaproot>'?
 If you ran the GAP binary directly, try running the 'gap.sh' or 'gap.bat' script instead.gap>
gap>
```
