### ISSUE TITLE
Crash with perverse method

### ISSUE THREAD

**Issue by laurentbartholdi** [gap-system/gap#1286]
The following (slightly perverse) method causes a crash rather than an error:

```
gap> DeclareAttribute("XXX",IsGroup);
gap> InstallMethod(XXX,[IsGroup],XXX);
gap> XXX(SymmetricGroup(5));
Segmentation fault: 11
```

**Comment by fingolfin** [comment]
So this is an infinite recursion that we are not currently catching.

**Comment by fingolfin** [comment]
A backtrace for this looks like this, repeated over and over:
```
  * frame #0: 0x000000010015c141 gap`DoOperation1Args + 3 at opers.c:2185
    frame #1: 0x000000010015c13e gap`DoOperation1Args(oper=0x000010000053b7c0, arg1=0x000010000053c1c0) + 23
    frame #2: 0x000000010015cb65 gap`DoAttribute(self=0x000010000053b7c0, obj=0x000010000053c1c0) + 166 at opers.c:2684
    frame #3: 0x000000010015c2c1 gap`DoOperation1Args + 387 at opers.c:2267
    frame #4: 0x000000010015c13e gap`DoOperation1Args(oper=0x000010000053b7c0, arg1=0x000010000053c1c0) + 23
    frame #5: 0x000000010015cb65 gap`DoAttribute(self=0x000010000053b7c0, obj=0x000010000053c1c0) + 166 at opers.c:2684
    frame #6: 0x000000010015c2c1 gap`DoOperation1Args + 387 at opers.c:2267
    frame #7: 0x000000010015c13e gap`DoOperation1Args(oper=0x000010000053b7c0, arg1=0x000010000053c1c0) + 23
    frame #8: 0x000000010015cb65 gap`DoAttribute(self=0x000010000053b7c0, obj=0x000010000053c1c0) + 166 at opers.c:2684
```

A naive fix would be to prevent an operation from dispatching to itself, but clearly one can extend this to n operations, each dispatching to the next, in a cycle, so that naive fix is not enough.

Instead, we should adapt the existing `RecursionDepthTrap` mechanism to cover this case. Right now, we check for recursion inside `DoExecFunc0args` etc. only (and in two spots in plists / precords).

Perhaps we should also check it in `DoOperationNArgs`. Even more radical (and covering more similar cases) would be to have the check in the `CALL_&ARGS` macros.

With either approach, though, note that recursion depth shown then the trap triggers will no longer be identical to the depth of the backtrace printed by `Where`. But I think that's a small price.

Perhaps more serious is that now reaching a certain recursion depth might happen sooner than before.
