### ISSUE TITLE
Problems compiling stable-4.8 after compiling master

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/gap#1343]
I am having trouble when I try to recompile GAP in the stable-4.8 branch, after having previously compiled GAP in the master branch. I'm sorry if I'm not understanding how to use the new build system properly - I know that a lot of changes have been made recently.

More specifically, I can compile GAP in the master branch with no problems, in the following way:
```
git checkout master
./autogen.sh
./configure --with-gmp=system
make -j
```

When I checkout stable-4.8, obviously I need to recompile GAP. So I try something like this:
```
git checkout stable-4.8
./configure --with-gmp=system
make -j
```
The `configure` script produces the usual normal-looking output. However `make` fails in the following way:
```
GNUmakefile:163: Makefile.rules: No such file or directory
make: *** No rule to make target `Makefile.rules'.  Stop.
```
The only way that I've found to get around this is the run `make distclean` when GAP is in the master branch, before checking out stable-4.8. In other words, I have to do the following to compile stable-4.8:
```
git checkout master
make distclean
git checkout stable-4.8
./configure --with-gmp=system
make -j
```
It seems like I should just be able to checkout stable-4.8 and run configure and make as usual. Perhaps some file is not being tracked properly in the repository? Again, apologies if I'm doing something stupid/overlooking something simple.

**Comment by fingolfin** [comment]
All files are tracked fine. But both build systems generate different non-tracked files, and these can in principle get in the way of each other. So doing a `make distclean` before switching, or `git clean -f -x` (WARNING: this will also remove any untracked changes and files, so be extra careful!) is the way to go.

In this particular file, the generate `GNUmakefile` is left by the `master` build system, and that file has precedence over `Makefile` which is used by the old build system. So you need to remove it manually (the old build system naturally won't remove it for you, as it knows nothing about that file).

I recommend that you use separate worktrees or clones for master and stable; this also has the advantage that you can run both of them in parallel to compare results.

PS: Unless you are on a machine with hundreds of cores (and possibly even then), I'd recommend against using `make -j`, it'll be slower than, say, `make -j4`, due to excessive I/O load and RAM/CPU usage.

**Comment by wilfwilson** [comment]
Thanks @fingolfin.
