### ISSUE TITLE
C99 compiler warnings in package compilation

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/gap#1387]
Perhaps this is just my issue but I can't seem to resolve it: after some recent changes in GAP master relating to the gasman, whenever I try to compile the [Semigroups](https://gap-packages.github.io/Semigroups/) package, I get multiple warnings of the form:

    /Users/jdm/gap/src/gasman.h:94:9: warning: flexible array members are a C99
          feature [-Wc99-extensions]
        Bag data[];

I tried adding `std=c99` and `-Wno-c99-extensions` to my `CFLAG`s and to the `C/CXX/CPPFLAGS` in the Semigroups package `Makefile.am` file, but I can't seem to silence these warnings. Can anyone tell me how to get rid of these? Thanks!

**Comment by james-d-mitchell** [comment]
I'm using 

    ~/gap/pkg/semigroups]$ clang -v
    Apple LLVM version 8.0.0 (clang-800.0.42.1)
    Target: x86_64-apple-darwin16.4.0
    Thread model: posix
    InstalledDir:     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by fingolfin** [comment]
Yes, we decided to move to using C99 in GAP. So it seems you are not actually using `clang`, but rather `clang++` (a quite important distinction in this case): Unfortunately, flexible array members, as used here, are not supported in C++ (one of the various examples that show that C++ is not a superset of C :-/). And it seems the C++ folks are not going to add it, ever :-(.

And you can't switch a C++ compiler to "C99" mode (what should that do?). I'd assume that `-Wno-c99-extensions` would do the trick, after all, that's precisely what the compiler suggests -- just to double check: did you verify that it really gets passed on correctly to the compiler by your build system (in particular, at the end, and not e.g. before `-Wall` ? Could you perhaps past the exact invocation of the compiler, with all flags etc?

Anyway that's a bit unfortunate, and certainly not intentional. I guess we could get rid of the `data` member again -- it makes some code more elegant, but it is only needed inside of `gasman.c`, and we could replace it by a specialized internal macro (or static inline helper) which in the end does the same job (so one would write `DATA(header)` instead of `header->data`).
