### ISSUE TITLE
ElementOfFpMonoid undocumented

### ISSUE THREAD

**Issue by cdwensley** [gap-system/gap#1397]
It appears that ElementOfFpMonoid works as expected (the same way as ElementOfFpSemigroup) as a sort of inverse to UnderlyingElement, and I expect to use this operation in the Kan update under preparation.  But the operation is undocumented, and perhaps that is true of many of the functions in fpmon.gd.  Is there good reason for this?  Or is it reasonable to add brief entries in the chapter "Finitely Presented Semigroups and Monoids"?  In my gapdev of May 25th: 
gap> ?ElementOfFpMonoid
Help: no matching entry found
Help: 'ElementOfFpMonoid' is currently undocumented.
      For details, try ?Undocumented Variables

**Comment by james-d-mitchell** [comment]
There is probably no good reason for this, much of the code for fp semigroups and monoids is undocumented and some of it does not work very well. I think it would be entirely reasonable to add entries to the fp semigroups and monoids chapter.

**Comment by cdwensley** [comment]
OK - I'll prepare a pull request.

**Comment by cdwensley** [comment]
This is becoming a general revision of Chapter 52 of the manual, so I hope it is OK to raise questions here, as they occur to me, rather than start new issues. 
52.2.1 \/  is followed by  52.2.2 FactorFreeSemigroupByRelations, and the casual user might think that the first calls the second whereas, in fact, \/ calls FactorSemigroupByClosure which calls SemigroupCongruenceByGeneratingPairs. 
Nevertheless, FactorFreeSemigroupByRelations is called by HomomorphismFactorSemigroup, and the latter is frequently used.  It seems to me that SemigroupCongruenceByGeneratingPairs and FactorFreeSemigroupByRelations do essentially the same thing, and that the latter should at least cease to be documented if not replaced altogether.  Or perhaps it should call the former? 
On the other hand, if FactorFreeSemigroupByRelations is to remain documented then surely FactorFreeMonoidByRelations should also be included in this chapter?

**Comment by james-d-mitchell** [comment]
In general, I think most of the code in this part of GAP should be carefully tested, then revised, and simplified. 

There are two separate issues here, the first is with the documentation, and the second is with the code itself. Since the documentation should reflect what the code does, I'll concentrate on the code itself. I guess that some of the problems with the documentation reflect problems with the code itself. 

`SemigroupCongruenceByGeneratingPairs` should return a congruence object defined over a semigroup, but `FactorFreeSemigroupByRelations` returns a finitely presented semigroup. Congruences and f.p. semigroups are not the same thing in GAP, so this is the essential difference between these two. 

`FactorSemigroupByClosure` returns the quotient of its first argument (a semigroup) by the least congruence containing its second argument (a list of pairs of the semigroup). I guess that this is meant to be a convenience because `FactorSemigroupByClosure(S, L)` ought to return the same as `FactorSemigroup(S, SemigroupCongruenceByGeneratingPairs(S, L))`, so less typing. Going from the name alone, this again should be different than `FactorFreeSemigroupByRelations` and `SemigroupCongruenceByGeneratingPairs` in that it should return a quotient semigroup object, but it does not seem to do this, which is another issue by itself, since`IsFpSemigroup` does not imply and is not implied by `IsQuotientSemigroup` as far as I can see. 

It is not clear to me why the operations `FactorSemigroup` and `FactorFreeSemigroupByRelations` exist at all, they could instead simply be methods for `/` for a semigroups and congruence, and for a free semigroup and a list, respectively. 

There are several further issues: both the words `Factor` and `Quotient` are used interchangeably. For example, there is no real difference between `HomomorphismFactorSemigroup` and `HomomorphismQuotientSemigroup` so why do they both exist? I guess there is no good answer to this question. It would be better to use one or the other of these terms uniformly in the code, I think `Quotient` is better than `Factor`. 

This comment has got a bit on the long side. To conclude, I am not sure that all of these issues can be resolved by applying minor patches to the existing code and documentation, it will probably require that the code is completely revised and then the documentation revised after that.

**Comment by cdwensley** [comment]
That's a very helpful description of the situation.  However, there can be no harm in making edits to Chapter 52 so as to document operations such as ElementOfFpMonoid.  This has now been done and I will make a pull request shortly.
