### ISSUE TITLE
Simpcomp (was: Union sometimes fails if applied to a list of lists whose representations are mixed between PlistRep and RangeRep)

### ISSUE THREAD

**Issue by markusbaumeister** [gap-system/gap#1447]
### Observed behaviour
If Union gets a list of PlistRep-lists and RangeRep-lists, it sometimes does not return the union of those collections.

Input:
Union( [ [1..2], [17], [20], [11,23..23], [14,26..26], [1,17..17], [23] ] );
Union( [ [1..2], [5,6], [5,11], [6,14..14], [17], [20], [11,23..23], [14,26..26], [1,17..17], [2,20..20], [23], [26] ] );
Output:
[1,2]
[ 1, 2, 5, 6, 11 ]

### Expected behaviour
Union should return the union of the appropriate collections. In the given example the results should be respectively:
[1,2,11,14,17,20,23,26]
[ 1, 2, 5, 6, 11, 14, 17, 20, 23, 26 ]

### Copy and paste GAP banner (to tell us about your setup)
This was tested on three different versions of GAP (up to 4.8.7).

 ┌───────┐   GAP 4.8.3, 19-Mar-2016, build of 2016-06-09 11:32:41 (CEST)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64

 ┌───────┐   GAP 4.8.5, 25-Sep-2016, build of 2016-09-30 22:20:20 (CEST)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64 

 ┌───────┐   GAP 4.8.7, 24-Mar-2017, build of 2017-05-16 12:12:16 (UTC)
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64

**Comment by markuspf** [comment]
Note that this is fixed in the `master` branch, though I fail to find the commit that does it right now.

**Comment by markuspf** [comment]
I suspect it is this one: https://github.com/gap-system/gap/pull/444

**Comment by fingolfin** [comment]
Perhaps @stevelinton can have a look at this, given that he rewrote the `Union` code and hence is probably most familiar with it?

**Comment by stevelinton** [comment]
This is fixed in master and so will be fixed in 4.9.0. The only question is whether it's worth fixing on the stable branch for 4.8.8 &c. If so, are we better to move the fairly large, but hopefully by now reasonably well tested solution that is in master, or to try and write a minimal fix for the bug? The big fix does require a minor fix to simpcomp -- maybe that's already released.

**Comment by fingolfin** [comment]
@stevelinton thanks for the update. Looking at #444, there was a commit by @simpcomp-team, see https://github.com/simpcomp-team/simpcomp/commit/a06ed1859571dac5c31a22ba7031b9935f875c2e -- I assume this resolves the issue, but there hasn't been a simpcomp release since then. I filed https://github.com/simpcomp-team/simpcomp/issues/5 on this

**Comment by alex-konovalov** [comment]
Simpcomp 2.1.7 released and picked up for the redistribution (see https://github.com/simpcomp-team/simpcomp/issues/5). It should appear in GAP 4.9.0 archive.

**Comment by alex-konovalov** [comment]
Simpcomp 2.1.7 has been included in GAP 4.8.10 distribution.
