### ISSUE TITLE
Setup full "testpackages" to run on Travis

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1473]
Right now, we only run the package tests on a Jenkins server in St Andrews, which has restricted access and is hard to reach from outside there.

It would be much nicer if we ran `testpackages` somewhere were it is visible to the public, so that we can react to its results in a timely fashion.

Perhaps running it is too slow (we'll have to experiment), so that we wouldn't want to run this on every PR; but then we could at least set it up to run in a Travis cron job once per day (or week, or whatever).

**Comment by alex-konovalov** [comment]
Good idea. FYI, we have https://travis-ci.org/gap-system/gap-docker-pkg-tests which uses Travis to  run package tests using GAP Docker container. It runs the latest stable GAP release. It may have false negatives (e.g. tests pass but we can not detect that because of some problems and report them as failing). 

Docker container is useful because it reduces testing time, and also because it has most of the dependencies satisfied. My intention is to set up periodic build for the Docker container for the GAP development version, and then have a variant of such test using that container instead of the latest official release.

**Comment by alex-konovalov** [comment]
This is done and reported in #1732:  I've set up two Travis builds

- https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable
- https://travis-ci.org/gap-system/gap-docker-pkg-tests-master
which run standard tests for GAP packages in gapsystem/gap-docker-stable and gapsystem/gap-docker-master Docker containers respectively.
