### ISSUE TITLE
GAP library declares `CopyToVectorRep` and `CopyToVectorRepNC`, but does not install functions

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#1643]
As part of the cleanup and merge of GAP and HPC-GAP @fingolfin suggests to first fix the API of `CopyToVectorRep`, and document it, before it becomes something we have to support.

This issue is mainly here so we do not forget addressing it.

**Comment by alex-konovalov** [comment]
Here they are: 
https://github.com/gap-system/gap/blob/323141ee98128fe6bf71c703e67e2ead3fe9a7b4/hpcgap/lib/vecmat.gi#L1477

**Comment by markuspf** [comment]
That is HPC-GAP, not GAP. The point is that they are declared but not installed in GAP.

**Comment by alex-konovalov** [comment]
Then probably declarations must have been introduced in HPC-GAP  and crawled into the GAP library in the process of converging the two databases.

**Comment by fingolfin** [comment]
It did not "crawl in", it was added (by me) quite deliberately, with a comment explaining why.

**Comment by fingolfin** [comment]
I mean, this definitely needs to be resolved in some way, but let's do it properly before exposing this to the general population.

My main concern is that to use it, the caller has to "know" which arguments are accepted, and then use code like
```gap
if q <= 256 then
   a:= CopyToVectorRep(b);
else
  # Do something else... ???
  a := b;
fi;
```
and this is then repeated everywhere. In contrast, `ImmutableVector` and `ImmutableMatrix` work with arbitrary arguments. Which is why I introduced the latter, and already changed lots of code to use those two. But they cannot be used if we really need a mutable vector. But then it's not always clear what to do, esp. when one wants efficient code... E.g. one could default to use `ShallowCopy` in the cases which are currently not handled by `CopyToVectorRep`, but in many actual usage examples, this just makes a pointless copy, because it would have been perfectly fine to use the original vector.

So for such code, it'd be useful to have a function `Foobar` which is documented to return either the original vector, or an equivalent vector in a "better" representations, and which then always use as `v := Foobar(v)`  -- or possibly `v := Foobar(v, extra_hints)`, where `extra_hints` e.g. informs about the desired basefield.

Even better, though, would of course be to use proper MatrixObj and VectorObj objects from start to end, but that's a bigger project, so I am for a short term pragmatic solution which can then later be evolved into a "proper" solution (if necessary).

**Comment by alex-konovalov** [comment]
We can do 4.9.0 without this, so I've postponed this till later.
