### ISSUE TITLE
Release notes for GAP 4.9

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1699]
Below is a list of pull requests which are NOT in stable-4.8, formatted as a task list.

If you want to help, do this: Take any PR which has not been "ticked" yet. Look at it, and decide whether it contains changes that should be mentioned in the release notes. If yes, do so.
In either case, once you are done reviewing the PR, tick it, so that nobody else has to look at it.

TODO: explain how / where to add the release notes... perhaps on a Wiki page, or a HackMD file?

UPDATE: turns out that clicking the checkboxes is veery slow on GitHub. I will look into a way to first reduce the list some more...

**Comment by alex-konovalov** [comment]
Summarising this using wiki sounds like a good idea to me: then let's use https://github.com/gap-system/gap/wiki/Changes-between-GAP-4.8-and-GAP-4.9

**Comment by fingolfin** [comment]
Please see discussion on Slack

**Comment by alex-konovalov** [comment]
@fingolfin "below" there is no list of PRs as announced - could you please update the comment with an up to date info?

**Comment by fingolfin** [comment]
@alex-konovalov but you have the "for internal use pnly" HackMD URL with it already, which I gave out on Slack so that you and others could edit it further

**Comment by fingolfin** [comment]
Closing this then, as apparently it is not helpful and others are reluctant to edit it

**Comment by alex-konovalov** [comment]
The task of walking through all PR merged to master but not into stable is quite tedious. We are doing that in a shared document - if anyone wants to help, ask one of the assignees for this issue for details.

When we will have that completed, we can update [release notes on Wiki](https://github.com/gap-system/gap/wiki/Changes-between-GAP-4.8-and-GAP-4.9) and add the new chapter to the `doc/changes` manual.

To make collecting release notes easier, @fingolfin created new label ["not-for-release-notes"](https://github.com/gap-system/gap/labels/not-for-release-notes). Otherwise, if the PR should be mentioned in release notes, please use one or several more specific labels, e.g. ["enhancement"](https://github.com/gap-system/gap/labels/enhancement), ["new feature"](https://github.com/gap-system/gap/labels/new%20feature) etc.

**Comment by alex-konovalov** [comment]
@fingolfin we certainly need to update the list of PRs at hackmd for that...

**Comment by fingolfin** [comment]
I cand do taht eventually, but in the meantime, there is plenty of work already there, no? And I am reluctant to invest any work into it unless I know it won't be wasted

**Comment by alex-konovalov** [comment]
Yes, of course didn't mean "for that" = "to continue work on this", it's not preventing from sorting existing items in the list. But hopefully next week we might need more items, and you may plan that in your schedule then, if we have to make 4.9 beta this year.

**Comment by fingolfin** [comment]
(summary of discussion on Slack follows)
Instead of running my (super hacky) scripts again, I suggest that we instead use GitHub's filtering system to find PRs not yet covered. Here is a query URL which only shows PRs which were merged into master since the last GAP days, and for which the labels "not for release notes" and "added to release notes" are not set: <https://github.com/gap-system/gap/pulls?page=4&q=is%3Apr+-label%3A%22not+for+release+notes%22+-label%3A%22added+to+release+notes%22+is%3Aclosed+merged%3A%3E%3D2017-09-01+is%3Amerged++base%3Amaster>

I already went through a couple dozen PRs previously listed in that query and added the "not for release notes" label. As I write this, 87 PRs remain in that list.

Now to make the release notes, we can go through PRs in the issues, and decide what to do with it: Either they are for the release notes, then let's add the PR there, and afterwards give it the "added to release notes" label. Otherwise, add the "not for release notes" label. In either case, it will be removed from the list shown by the query.

**Comment by alex-konovalov** [comment]
Now 70 remain!

**Comment by alex-konovalov** [comment]
OK, in the hackmd list of pull requests about 20 left now - belong to @markuspf @fingolfin @chrisjefferson and @hulpke. I will look at them later, but if you wish, please have a look and handle them. I have left them because either I may have a doubt whether to include them or not, or they could be better described by you, or should be incorporated into some  other more global item, or contain a large collection of changes, so have to be checked and maybe some of them should be described, some not... 

That's not all - we need also to select PRs from GitHub:
* those merged into master after 2017-09-01 but before `stable-4.9` was created
* those merged into `stablle-4.9`

**Comment by alex-konovalov** [comment]
So, this task has achieved some milestone. All PRs that were in the hackmd.io document and all subsequent PRs that went to master before branching off stable-4.9 and then into stable-4.9 are processed. However, *the text still requires some polishing and editing*, and maintenance for future PRs going into stable-4.9. For that purpose, I have now moved the text from  hackmd.io document to the following wiki page: https://github.com/gap-system/gap/wiki/GAP-4.9-release-notes

My plan is to fix the text on that page and include a link to it into the announcement of GAP 4.9 beta. While we will be preparing for the first public release of GAP 4.9, that page may be further edited and extended, and converted (maybe with shortening) into a chapter of the Changes manual).

It is easy to find this page from the GAP GitHub wiki, as it is visible in the right navigation bar (and does not require a secret link like hackmd). For new PRs that will be going into stable-4.9, there is a query there and instructions how to process those PRs.

*Remark:* there is also a similar page for GAP 4.10 release notes, with a different query and similar instructions here: https://github.com/gap-system/gap/wiki/GAP-4.10-release-notes

**Comment by alex-konovalov** [comment]
GAP 4.9.0 published today, see release notes at https://github.com/gap-system/gap/wiki/GAP-4.9-release-notes. This issue is now closed and superseded by #2152 (Release notes for GAP 4.9.1).
