### ISSUE TITLE
DeclareObsoleteSynonym handles Operations incorrectly

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#1717]
Calling `DeclareObsoleteSynonym("ObsOp", "NewOp")` with `"NewOp"` the name of an operation defines `ObsOp` as a function. This causes method installations into `ObsOp` to fail.

### Observed behaviour
```
gap> DeclareObsoleteSynonym("ObsoleteList", "ListOp" );
gap> ListOp;
<Operation "ListOp">
gap> ObsoleteList;
function( arg... ) ... end
```

**Comment by alex-konovalov** [comment]
See the subsequent discussion in #1718. As #1718 has been closed, I am closing this issue too. `ObsOp` becomes a function since we want to print a message when obsolete operations are used to alert the user. The fact that one can not install new methods for obsolete operations is also a kind of an alert...
