### ISSUE TITLE
'gap -x 1345' exits when 'Print(10^1342);'

### ISSUE THREAD

**Issue by OpaStefanVogel** [gap-system/gap#1756]
### Observed behaviour
    pi@raspberrypi:~ $ gap -x 1345
    gap> 10^1342;
    100000...000
    gap> pi@raspberrypi:~ $ 

### Expected behaviour
gap should not exit after the last 'gap>' 

### Copy and paste GAP banner (to tell us about your setup)
 ┌───────┐   GAP, Version 4.7.5 of 24-May-2014 (free software, GPL)
 │  GAP       │   http://www.gap-system.org
 └───────┘   Architecture: arm-unknown-linux-gnueabihf-gcc-default32

**Comment by ChrisJefferson** [comment]
This has been fixed in the latest version of GAP. I remember it being fixed, but I can't find the issue number (sorry).

If you want GAP to stop printing "\" at the end of lines, then as a workaround you can call: `SetPrintFormattingStatus("*stdout*", false);`, which may work on the GAP you are using (sorry, it's old enough I don't have a copy), without having to use `-x`.

**Comment by OpaStefanVogel** [comment]
Yes,

    SetPrintFormattingStatus("*stdout*", false);

is ok, without using -x. Thank You. gap version 4.7.5 I get on Raspberry Pi Zero W with 'sudo apt-get install gap' and I use gap with node-red-daemon https://github.com/node-red/node-red-nodes/tree/master/utility/daemon.
