### ISSUE TITLE
Wrong syntax warning about undefined global variable.

### ISSUE THREAD

**Issue by sebasguts** [gap-system/gap#1800]
In 4.6, 4.7, 4.8, and master, the code
```gap
test_string := [ "a", "b", "c" ];
for i in [ 1 .. 10 ] do
 for k in [ 1 .. 10 ] do
   string := "aaaabbbb";
   xx := List( test_string, j -> PositionSublist( string, j ) );
 od;
od;
```
gives the syntax warning
```
Syntax warning: unbound global variable
    xx := List( test_string, j -> PositionSublist( string, j ) );
```
which is wrong. However,
```gap
test_string := [ "a", "b", "c" ];
for i in [ 1 .. 10 ] do
  for k in [ 1 .. 10 ] do
    string := "aaaabbbb";
    List( test_string, j -> PositionSublist( string, j ) );
  od;
od;
```
does not produce a warning. The above example is minimal in the sense that the warning does not appear with a single for loop, but only if there are at least two nested for loops.

Copy of banner:
```
 ┌───────┐   GAP 4.8.8-4401-g5f25772 of today
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
 Configuration:  gmp 6.1.2, readline
```

**Comment by fingolfin** [comment]
Actually, I am not so sure the warning is "wrong"; maybe it is undesirable, but GAP cannot easily tell the state of `string` at that point. For me, the bug is that the two snippets of code behave differently. I do not care that much whether they both show a warning, or both don't.

So, here is what (I think) is going wrong:

We only issue `SyntaxWarning("Unbound global variable");` in one place, namely inside function `ReadCallVarAss` from `read.c`. There, we have this check:
```C
    if ( type == 'g'                // Reading a global variable
      && mode != 'i'                // Not inside 'IsBound'
      && LEN_PLIST(STATE(StackNams)) != 0   // Inside a function
      && var != STATE(CurrLHSGVar)  // Not LHS of assignment
      && ValGVar(var) == 0          // Not an existing global var
      && ExprGVar(var) == 0         // Or an auto var
      && ! STATE(IntrIgnoring)      // Not currently ignoring parsed code
      && ! GlobalComesFromEnclosingForLoop(var) // Not loop variable
      && (GAPInfo == 0 || !IS_REC(GAPInfo)
          || !ISB_REC(GAPInfo,WarnOnUnboundGlobalsRNam) // Warning enabled
          ||  ELM_REC(GAPInfo,WarnOnUnboundGlobalsRNam) != False )
      && ! SyCompilePlease )        // Not compiling
    {
        SyntaxWarning("Unbound global variable");
    }
```
Now, note the `var != STATE(CurrLHSGVar)` check: In the line we print the warning, we are not assigning anything. But in the line just before it, we *did* assign, namely to `string`. And the value for `CurrLHSGVar` does not get reset to 0 after we parsed a statement. Hence, our check compares against that stale value, and decides we are assigning to `string`, and thus does not fire.

We can verify this theory by inserting another assignment between the two lines, at which point the warning resurfaces:
```
Unbind(string);
test_string := [ "a", "b", "c" ];
for i in [ 1 .. 10 ] do
  for k in [ 1 .. 10 ] do
    string := "aaaabbbb";
    foobar:=1;
    List( test_string, j -> PositionSublist( string, j ) );
  od;
od;
```

So, to fix that, we can try to reset `CurrLHSGVar` in suitable places.


Now, going back to your initial example, of course it would be kind of nice to not show the syntax warning there. That's the next stept to think about...

**Comment by fingolfin** [comment]
As to why this shows a warning at all: I guess that the plan back then was that the warning should only be shown when coding a function, but not when coding interactive input (?), which is why we have a line in the kernel code I showed above which says

> LEN_PLIST(STATE(StackNams)) != 0 // Inside a function

However, in your example, `string` *is* used in a function, namely in `j -> ...`.

I see no good solution for this, at least with the current way we use to generate these warnings. To „properly“ address this, I think we‘d have to somehow delay generating these warnings until we evaluate the coded function body, at which point we can fully see which globals are bound and which are not. I.e. in the above example, when parsing `j -> PositionSublist( string, j )`, of course `string` is not bound, which is why we generate the warning. But once we actually execute the line, of course it is bound. The only *general* way to resolve that would be to delay the warning until execution (as we cannot solve the halting problem; note that we can trivially modify @sebasguts example, by replacing the assigment `string := ...` by `if Magic() = 42 then string := ... fi;`. Now, in order to decide whether `string` will be bound or not, we have to know what `Magic()` is going to return. But that function might depend on user input or whatever.

In order to delay the warnings, I guess we could add some code which is called right before instantiating a function expression (say as part of `MakeFunction`); that code would iterate over the function body, and look for any references to gvars, and report any which are not bound (nor automatic, etc.). Of course reporting the right spot in a nice fashion will be harder, as we are not in the scanner anymore. Plus, this adds overhead to evaluating inner function expressions, so we may not want to do it in `MakeFunction` after all, but rather in some other place; and perhaps also remember (via some flag stored in the function object) whether we already reported the undefined globals or not...

Anyway, this starts getting way to complicated for my taste. So perhaps we just add to the brittle ad-hoc rules anyway, by suppressing the warning if the "bottom" / "first" element in the (virtual) stack of statements we a processing is an (interpreted) loop. Of course that also would mean suppressing correct warnings, i.e. adding more false negatives. Hrm.

**Comment by stevelinton** [comment]
Maybe we should just adjust the text of the warning to "Potentially unbound global variable".

**Comment by fingolfin** [comment]
Just to say, with PR #2595 merged, both of @sebasguts examples now produce essentially the same warning.

**Comment by fingolfin** [comment]
I think there is nothing left to be done here. Sure, it'd be nice if GAP knew not to print a warning here, but ultimately this boils down to the famously unsolvable "Halting Problem". Of course we an add even more special cases -- like in the example at hand, it is not too hard to "prove" that `string` will be assigned before the line which produces the warning is ever reached. But I simply don't think the complexity is worth it here.
