### ISSUE TITLE
Refactor IO/OS interaction code

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#184]
Make [io](https://github.com/gap-system/io) a needed package that is also compiled during bootstrapping. Move to using file IO from this package.

**Comment by stevelinton** [comment]
While io is a good thing to have, is it needed for something specific, like gapdoc is?

**Comment by markuspf** [comment]
My idea was to push file IO (and other IO, system interaction?) into one place, but I admit I am not sure whether that one place is the IO package or the GAP core.

I was reading through some of the file IO code while looking at pull-request #179 and figured that duplicating functionality is not the best idea in the long run. 

In no way am I suggesting to just go and break things, of course.

**Comment by stevelinton** [comment]
Might be a case for some refactoring. What follows is a bit of a brain dump.

There are lots of logically distinct components

1. Whatever code is needed to provide a uniform set of C functions inside the kernel on top of 
possibly varying OS provision. This used to be a big deal and would be a big deal again if we decided
to do a proper native Windows port, since we’d have to find a common abstraction over Windows/ Linux and maybe iOS file handling. At the
moment though it’s pretty trivial.

This is replicated inconsistently between the kernel and IO

2. A reasonably direct GAP interface to these functions — currently in the io package

3. Existing file handling — PrintTo, LogTo, Read, StringFile, InputTextFile,……

	The implementation of Read desperately needs some work — the searching which happens is bizarre and ill-defined.

4. Fancy extra features like pickling.

5. Non IO system calls like fork.


1. probably belongs in the kernel since at least some of it is needed long before a package can be loaded.
4. seems like a natural candidate for package code.
At least a minimal subset of 3 needs to be in the kernel (and not dependent on package code) for bootstrap reasons,
but it’s quite appealing to move as much of 3 as possible to GAP code on top of 2 which might, but doesn’t have to, speak for bringing 
2 into the core system.

5 mostly still feels experimental to me, so I’d leave it in the package.

Before we do any major work, though, we should think about whether we actually do want to do a native Windows version (or a Javascript version) 
or more generally to move away from assuming a UNIX filesystem and so on.  It might ultimately make a lot of things easier, but it’s a lot of work and involves enforcing a strict “no direct C file handling” rule on the core system and needed packages.,
	
Steve

**Comment by ChrisJefferson** [comment]
It would be nice to look at what we have in IO which people need, and what is missing (or just bizarrely implemented) -- I mainly use it myself just because I know the names of the POSIX functions, but ever so often I find some of the functionality is already in core.

**Comment by markuspf** [comment]
This seems to be at least somehow related with #88

**Comment by fingolfin** [comment]
Just to add my two cents: I like IO for the fact that it exists, and gives you a practical and, most importantly, actually available solution for various issues. What I dislike is that it is basically a thin wrapper around POSIX APIs, with no abstraction provided whatsover. Hence code using it is tied to UNIX systems, or at least some POSIX emulation layers (when running on non-POSIX systems like Windows). In fact, even POSIX systems differe in some subtle or not so subtle ways -- E.g. I am pretty sure I could whip up some code using IO which behaves differently on Linux on OS X.

So, on the long run, I wish we had some abstractions for common things, just like e.g. Python does. Of course creating good abstraction layers is really hard, and many languages (e.g. Python, Java, ...) often needed multiple attempts before they got it right (if ever). Perhaps we can identify some key aspects people use IO for, and come up with a good abstraction that'll work on Windows or "in web browser" or whatever, too. It's these abstractions I'd like to see inside GAP itself on the long run, not IO (depite IO being immensely valuable right now). Of course, a prototype for such abstractions could at first be written as part of some package, and, if it proves useable and useful, could later be integrated into GAP itself.

And of course unlike Java and Python and others, we don't have to start from scratch -- we can steal, erhm, borrow good ideas from them :)

**Comment by fingolfin** [comment]
To update this: I am still not sure (or rather I am sceptical) whther we should make `io` a required package -- but we definitely should cleanup the IO code that is already in GAP.

**Comment by alex-konovalov** [comment]
@markuspf what's the status of this? Should we re-assign this to a future milestone (4.9.1 or even 4.10.0).

**Comment by fingolfin** [comment]
While this would be nice to have, I don't think it's mandatory for 4.9.0, hence I just removed the milestone. Perhaps we can try to get this into 4.10.0.

**Comment by alex-konovalov** [comment]
If there was a milestone, it could be that it was to prevent this falling below the radar - perhaps in such cases one should not remove it, but change to the next major release? OTOH, this could easily lead to milestone "polluted" by such issues that might be of a less importance, hence postponed, rather than being populated with more high-priority tasks.

**Comment by fingolfin** [comment]
I don't think this is the way to go.
