### ISSUE TITLE
Unexpected behaviour with list slices

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#1940]
```
gap> l := [1,2,3];
[ 1, 2, 3 ]
gap> l{[2,3]}[1];
Error, List Element: <list> must be a list (not a integer)
not in any function at *stdin*:2
you can replace <list> via 'return <list>;'
brk> 
```

Whereas
```
gap> (l{[2,3]})[1];
2
```

I am pretty sure this should work without the brackets, but I haven't looked yet whether it's hard or easy to do.

**Comment by fingolfin** [comment]
I think this is correct. The two expressions have different meaning: The first, `l{[2,3]}[1]`, means: extract a sublist of from `l` consisting of the second and third element; then apply to each element of the new list the map  `x -> x[1]`. Which gives an error, because `x` is an integer in both cases.

The second means: extract that sublist; then apply `x -> x[1]` to that sublist.

**Comment by fingolfin** [comment]
See also https://www.gap-system.org/Manuals/doc/ref/chap21.html#X7921047F83F5FA28
