### ISSUE TITLE
'configure' script does not respect '--prefix' parameter when generating the startup scripts

### ISSUE THREAD

**Issue by alexeymuranov** [gap-system/gap#196]
I have encountered the following bug in `configure` script: i supply `--prefix` parameter, but the generated `gap-default64.sh` script does not respect it when defining `GAP_DIR` variable.  The variable is set to the directory that contains `configure` script when it is executed instead of the directory supplied with `--prefix` parameter.

More precisely: executing 

```
./configure --prefix=/Volumes/Data/Users/alexey/gap/4.7.8/
```

from `/Volumes/Data/Users/alexey/Downloads/gap4r7/` generates `bin/gap-default64.sh` where line 23 is

```
GAP_DIR="/Volumes/Data/Users/alexey/Downloads/gap4r7"
```

instead of the expected `GAP_DIR="/Volumes/Data/Users/alexey/gap/4.7.8"`.

**Comment by fingolfin** [comment]
In my eyes, the real bug here is that one is even allowed to specify a `--prefix`, as GAP does not know anything about the "prefix", and does not support `make install` either (see issue #197). :-)

But of course it would be nice to support installation of GAP eventually (in *addition* to the current mode of operation). And then the `prefix` option (and all its siblings) should be correctly supported, too.

**Comment by fingolfin** [comment]
Closing this as invalid: Prefix is only for "make install", so the described behavior is not actually wrong.

Adding support for "make install" should address the concern anyway, though.
