### ISSUE TITLE
Regression: warning when saving workspace

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1999]
I get this on master:
```
gap> SaveWorkspace("default.wsp");
#W bad bag id 4386049288 found, 0 saved
#W bad bag id 4386049304 found, 0 saved
#W bad bag id 4388303696 found, 0 saved
#W bad bag id 4388303704 found, 0 saved
#W bad bag id 4384440664 found, 0 saved
true
gap>
```

Curiously, a `git bisect` reveals that this was introduced by e89c288fd1f9f843a63a8dd198053118187381b8 and indeed, changing `GAP_PATH_MAX` back to 512 fixes the issue. What's going on here?!?

**Comment by wilfwilson** [comment]
This is weird. In the Travis tests for Semigroups, we quickly run a save/load workspace test, e.g. around line 2,500 [here](https://travis-ci.org/gap-packages/Semigroups/jobs/309016793). Until today this has worked fine, but it fails now, like in your message above:
```
########> Diff in save-workspace.tst:155
# Input is:
SaveWorkspace(Concatenation(SEMIGROUPS.PackageDir,
                               "/tst/workspaces/test-output.w"));
# Expected output:
true
# But found:
#W bad bag id 12884392 found, 0 saved
#W bad bag id 12873768 found, 0 saved
#W bad bag id 8445424 found, 0 saved
#W bad bag id 12875832 found, 0 saved
true
########
Semigroups package: workspaces/save-workspace.tst
```
Wouldn't that suggest that this bug was introduced very recently?

Also notable: this diff only appears in our 32-bit tests, not in our 64-bit tests.

**Comment by fingolfin** [comment]
I bisected it to the commit I listed. I happens for me in 64 bit builds, too, on OS X. Since it is only a warning, we may not have noticed it with GAP's travis tests.

**Comment by fingolfin** [comment]
And I also verified that if I edit `GAP_PATH_MAX` in `master`, the issue goes away

**Comment by wilfwilson** [comment]
Sorry @fingolfin, I didn't mean to doubt you. From my point of view it was strange that today was the first time I noticed a Travis failure because of this bug ([here's an example of it causing a failure](https://travis-ci.org/wilfwilson/Semigroups/jobs/312493531#L2480)), even though it was introduced 3 weeks ago and I have been running Travis jobs in that time.

However, in all of my Travis jobs since the link above, the diff has not occurred. This intermittent nature probably explains why I have not seen it until today.

**Comment by fingolfin** [comment]
Neither do I doubt your, or understood you as doubting. I think this is one of those bugs which depends on your *specific* compiler version, operating system, arch etc.
So for me, the issue occurs on OS X 10.11.6, with clang (Apple LLVM version 8.0.0, clang-800.0.42.1)

I guess I could try with gcc 7 or clang 5. later.

**Comment by ChrisJefferson** [comment]
This is caused by the lists FopiesGVars and CopiesGVars. These lists of lists store raw C pointers in PLISTS, which confuses the workspace save/load.

The function RemoveCopyFopyInfo tries to deal with this by unassigning all the elements of FopiesGVars and CopiesGVars (which are the troublesome lists). However, by rearranging memory layout, those inner lists are by bad luck not getting GCed any more, causing the problem.

Three possible solutions:

1) A quick hack solution is to extend RemoveCopyFopyInfo to actually clear the inner lists, before unassigning them.

2) As all C pointers are at least 4 byte aligned , and do `|1` and store them as valid GAP integers.

3) Stop using PLISTs.
