### ISSUE TITLE
Int( "" ) does not work anymore?

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#2047]
Up to GAP 4.8.8, `Int( "" )` returns `0`.
In the master branch, one gets `fail`.
This change breaks some of my code.
Is there a good reason for this change?

**Comment by fingolfin** [comment]
I am pretty sure there is no good reason, other than that the code for string <-> integer code conversion was rewritten and unified (instead of four or so implementations, we now use only one). I guess this special case fell through the cracks, also because (as far as I can tell) the documentation does not say anything about dealing with the empty string.

Personally, I'd think `Int("") = fail` makes more sense, *however* since this always returned 0 in the past, IMHO it still should do so now. So, let's fix this (and add a test, so it won't regress again in the future).

**Comment by fingolfin** [comment]
BTW, also `Int([])` used to return 0, presumably because the code did not distinguish between empty lists and empty strings. I guess we need to restore this as well...

**Comment by ChrisJefferson** [comment]
Int used to do crazy things, including executing arbitrary gap code in the string. We disabled on purpose, as most people (I claim) wouldn't expect that, and it produced security holes in things like SCSCP and openmath.

However, we should break empty string if it used to work, and people rely on it.

**Comment by fingolfin** [comment]
Hmm, I just run our existing tests for `Int()` in the master branch in GAP 4.8.8. We get several more discrepancies, i.e. stuff which used to return 0, now returns `fail`, e.g. `Int("-");` and `Int("--");`

Also, `Int("123456789123456789123456789123456789+1");` now returns (IMHO correctly) `fail`, but it actually used to return `123456789123456789123456789123456790`.. WTF?

That said, our documentation for `Int` is rather vague on what it does with "invalid" inputs:
>   If elm is a string (see Chapter 27) consisting of digits '0', '1', ..., '9' and '-' (at the first position) then  int  is  the integer described by this string. The operation String (27.7-6) can be used to compute a string for   rational integers, in fact for all cyclotomics.

This does not say what `Int("1+1")` should be. I suggest to augment this to clarify this: E.g. "if string consists of an option '-' in first position, followed by only digits '0', '1', ..., '9', then ..."

Also, in `master`, we now accept `Int(['1', '2', '\000', '3']);` and parse it as 12, which I find rather questionable -- I'd expect `fail` here, too.

**Comment by fingolfin** [comment]
Yeah, we should definitely restrict things. I am torn about `Int("") = 0` -- I don't mind supporting it if code relies on it and is hard to change, or leads to invalid computation results due to a change here. OTOH, I find it counterintuitive and not logical. Then again, the documentation for `Int` is super vague, so one can certainly justify it. Of course also `Int("answer") = 42` would be consistent with the documentation....

**Comment by ChrisJefferson** [comment]
Not that I think 1+1 didn't used to work either I think, we used to pass strings to eval if they were longer than.. 9 characters I think?

**Comment by fingolfin** [comment]
Yes, `Int("1+1")` always returned `fail`, and that's IMHO also good this way, and should be for larger stuff, too.

**Comment by fingolfin** [comment]
All in all, I take back my initial reaction of "I am pretty sure there is no good reason" ;-). As to allowing `Int("")` -- strictly speaking this is undocumented behaviour. Then again, we try not to break backwards compatibility without good reason. The empty string case is somewhat borderline here, although as I said before, I don't think having `Int("") = 0` is very reasonable. Python agrees with me, but JavaScript, PHP, Ruby and SQL all disagree. So, I think it's sufficiently established that converting an empty string to 0 may be OK that we can add this one thing back.

I'll prepare a PR.

**Comment by fingolfin** [comment]
BTW:
```
gap> Rat("/1");
0
gap> Rat("-/1");
0
```

**Comment by fingolfin** [comment]
See PR #2050; feedback on that is highly welcome.

**Comment by alex-konovalov** [comment]
Int("--") now returns zero, but the test expects `fail`.
