### ISSUE TITLE
BuildPackages.sh: bug in build_carat()

### ISSUE THREAD

**Issue by gaehler** [gap-system/gap#2116]
If CARAT is built with gcc 5 or newer, the flag "-std=gnu89" is required for compatibility with the bundled GMP library version 4.2.1. I therefore propose to add CFLAGS="-O -std=gnu89" to the make command in the build_carat() function. This should be done in the master and stable-4.9 branches, I presume.

In case there are further releases in the 4.8.x series planned: The version of build_carat() in that branch needs the above as well as other fixes. I can provide an improved version of build_carat().

In the longer run, it might be better to use either the system GMP library, or that bundled with GAP. It is a bit tricky though to make this selectable without too much fiddling with the CARAT makefile. Also, I have noticed that the GitHub version of GAP is built with the system GMP by default - is this a new policy?

**Comment by fingolfin** [comment]
GAP is now built by default against the system GMP, if available and usable, yes.

If you want to use the same version of GMP as used by GAP, be it a system wide one (there might be multiple!), or one bundled with GAP, you could take the linker flags from GAP's  `cnf/GAP-LIBS` and `cnf/GAP-LDFLAGS` files. However, since carat is a separate executable, that doesn't seem so important. Just link against the system GMP if available; though if not, you may want to fallback to trying to link against GAP's GMP found (if GAP uses one!) inside `GAPROOT/extern/install/gmp/`.

As to the code in `BuildPackages.sh`, my understanding is that the `carat` build code in there is an incomplete hack anyway -- at least it never worked for me on macOS (haven't tried it recently, though). We can of course tweak `BuildPackages.sh` further for carat, but it actually would be preferable if you could instead make building `carat` less unusual, i.e. ideally a matter of `./configure && make` as needed by most other packages... Then we could remove all special code for carat from `BuildPackages.sh`, and leave the matter of special compiler flags etc. to the package authors (i.e. you), as we do for virtually all other packages.

I'd be happy to provide assistance with the latter, too.

**Comment by gaehler** [comment]
Being only the author of the GAP interface code (Carat), not of the C code (CARAT), I have refrained from making extensive changes to the CARAT build system so far. What I could do is to write a wrapper consisting of a (fake) configure script an a makefile, which together do what currently is done by the build_carat() function (and perhaps a bit more). This would move the non-standard interface to the interior of the package. One has to see how portable this becomes, but it can't get much worse.

I would also try to get rid of the ancient version of the GMP library bundled with CARAT, and just use the system GMP library, or the one bundled with GAP (as I understand, from version 4.9 on, GAP will need GMP in any case).

**Comment by fingolfin** [comment]
@gaehler that sounds like a very good plan

**Comment by fingolfin** [comment]
This has been resolved via PR ##2255 resp. commit 1ee8a1292543356a2db0278c79e892bbb7136908 which removed `build_carat`
