### ISSUE TITLE
Testing \in for matrix group of order 6 is very slow (overhead of nice monomorphism handling?)

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2133]
Consider this:
```
gap> e:=One(GL(6,3));
< immutable compressed matrix 6x6 over GF(3) >
gap> g:=CyclicGroup(IsMatrixGroup, GF(3), 6);;
gap> h:=CyclicGroup(IsMatrixGroup, GF(9), 6);;
gap> g=h;
true
gap> ForAll([1..1000], i -> e in g); time;
true
1077
gap> ForAll([1..1000], i -> e in AsSet(g)); time;
true
2
gap> ForAll([1..1000], i -> e in h); time;
true
4206
gap> ForAll([1..1000], i -> e in AsSet(h)); time;
true
2
```

So testing 1000 times wether the groups neutral element is contained in it takes 2 milliseconds when testing this with `AsSet(g)`, but 1 second (500 times as long) when testing naively via `e in g`. And if I take the same group over GF(9) (the groups really are equal, only the matrices "remember" their base field to be GF(9)), the it's even 4 seconds.

Part of the problem likely is that the select nice monomorphism is not that "nice", e.g.:
```
gap> NrMovedPoints(NiceObject(g));
726
```

Looking at the used `NiceMonomorphism` method, I see this heuristic:
```gap
  # is the GL domain small enough to simply use it?
  if IsTrivial(grp) 
     or Size(FieldOfMatrixGroup(Parent(grp)))^DimensionOfMatrixGroup(grp)
         >2000 then
    # if the permutation image would be too large, compute the orbit.
    TryNextMethod();
  fi;
  return NicomorphismFFMatGroupOnFullSpace( GL( DimensionOfMatrixGroup( grp ),
		  Size( FieldOfMatrixGroup( Parent(grp) ) ) ) );
```
Here, `Size(FieldOfMatrixGroup(Parent(grp)))^DimensionOfMatrixGroup(grp)` is 729, so, we just embed the group into `GL(3,9)`.

Perhaps this heuristic should also take the size of the group (if known) into account? Here, clearly even the left regular permutation representation would be more efficient.

Indeed, if I force it to use a nice monomorphism created via `NicomorphismOfGeneralMatrixGroup` (e.g. by lowering the above threshold from 2000 to 700), I get these timings:
```
gap> ForAll([1..1000], i -> e in g); time;
true
48
gap> ForAll([1..1000], i -> e in h); time;
true
159
```
That's more than a magnitude of improvement, though it's still 25-80 times slower than testing `AsSet(g)` directly. But it's at least bearable.

Perhaps there are other ideas how one could improve the experience here? And yes, the fully proper way to dal with this is to use group recognition, *but* in this case we already know the group is cyclic of order 6, even in its natural representation -- there really isn't anything left to recognize ;-).

**Comment by hulpke** [comment]
Yes, the code assumed that a matrix group would be somewhat meaty and that for smallish vector spaces the determination of a domain sometimes costs more and gains little over just using the whole space.

I've now done a change somewhat equivalent to what was suggested. So, why is it still so much slower:

The problem is with niceomorphisms that are not defined on the whole of GL (though this is currently not tested and thus is always a problem).  When you ask  (e in G), it is possible that G has a niceomorphism, but e is not in the domain of this niceomorphism, but the niceomorphism produces a good-looking image. (Imagine G as GL3(5)<= GL4(5) and e cyclic of oder 4 on the last basis vector. The niceomorphism for G only tests the first 3 basis vectors, and considers e as identity.)
In an element test, one thus needs to map the image *back* through the niceomorphism to check that it indeed returns the original element. This takes time.

Short of introducing domains for elements (like in Magma) I do not see a way around this.

**Comment by fingolfin** [comment]
I think that would already be fine. I only noticed this when writing some test cases, and was surprised that tests with tiny matrix groups were taking muuuuch longer than expected.
