### ISSUE TITLE
HPC-GAP crashes if user kills current thread

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#217]
Killing a thread while on it leads to a segfault. While it is not clever to do that, I think GAP should never segfault, and prevent the user from doing this:
```
gap> !shell
--- Switching to thread 5
[5] gap> !kill 5
[5] gap>
Segmentation fault: 11
```

**Comment by rbehrends** [comment]
The problem is not a thread killing itself, which works fine:

```
CreateThread(function() KillThread(CurrentThread()); Display(314); end);
WaitThread(last);
!list
```

But apparently that the multi-threaded UI falls apart when the control thread kills the thread that has active input. This is done in the function `CommandKill@` in `lib/consoleui.g`. I'll see if I can look into this later, but you probably just need to report an error if `thread = ActiveThread@`.
