### ISSUE TITLE
MakeReadOnly and MakeReadOnlyObj not working?

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#224]
This happens on hpcgap-default

```code
gap> l :=  [1,2,3];
[1,2,3];
gap> RegionOf(l);
<region: thread region #0>
gap> MakeReadOnly(l);
 [ 1, 2, 3 ]
gap> l[2] := 5;
5
gap> l;
[ 1, 5, 3 ]
gap> RegionOf(l);
<region: read-only region>
```

**Comment by rbehrends** [comment]
This works for me on the most recent version. The most likely cause would be that Ward failed to insert the proper checks on your machine (there really needs to be feedback in the build process if that happens).

If you look at the file `gen/plist.c` (which is generated from `src/plist.c`), there should be a `ReadGuard()` and a `WriteGuard()` check in `AssPlist()`. If it's not, then Ward couldn't parse the file (the usual cause is some system include file using a weird gcc/clang extension that isn't part of the C standard).

**Comment by rbehrends** [comment]
I have updated Ward so that it adds the following line to files that it could not parse:

```c
/* ERROR: Ward failed to parse C source */
```

With that version, `egrep -l 'ERROR: Ward' gen/*.c` should show all files that had issues being parsed.

**Comment by markuspf** [comment]
Where is this update? It's not oh https://github.com/gap-system/ward

**Comment by rbehrends** [comment]
Oops, I accidentally pushed to my local copy. It's updated now.

**Comment by markuspf** [comment]
It now looks as if ward just fails to parse any file for me. Is there a way to print diagnostics so I can find out why? My system is DragonFly, and there might well be some system header weirdness...

**Comment by rbehrends** [comment]
I've added PR #225 to allow for testing ward on the source files more easily. See the commit message for how to use it.

**Comment by markuspf** [comment]
It seems to be choking on  /usr/include/stdlib.h

```C
#if __ISO_C_VISIBLE >= 2011 || __cplusplus >= 201103L
int     at_quick_exit(void (*func)(void));
_Noreturn void
        quick_exit(int);
void    *aligned_alloc(size_t, size_t) __heedresult;
#endif /* __ISO_C_VISIBLE >= 2011 */
```

Specifically the _Noreturn:

```
../ward/bin/ward -parseonly -Ibin/x86_64-unknown-dragonfly4.3-gcc-hpc -I. -Iextern/64bit/include -DHPCGAP -DCONFIG_H -DGC_THREADS -DBOEHM_GC -DUSE_GMP=1 -DNUM_CPUS=4 src/plist.c
eval: ${50_...}: Bad substitution
eval: ${50_...}: Bad substitution
//usr/include/stdlib.h:319,1:Syntax error
```

**Comment by rbehrends** [comment]
_Noreturn is a C11 keyword. I've just pushed a new commit for Ward that deals with this (and a couple others). Let me know if there are remaining issues.

**Comment by markuspf** [comment]
These solves the issue for me. I'll merge #225 as well.

I do think that the build should terminate if ward fails.

**Comment by rbehrends** [comment]
For now, I'd recommend simply having a warning if Ward failed. I can have a look at doing that later.

**Comment by rbehrends** [comment]
I've added support for warnings in PR #226.

**Comment by markuspf** [comment]
I'll close this now because the problem is solved. Issues about the build system will be addressed later.

**Comment by fingolfin** [comment]
We run into ward failing again yesterday and today. It is very easy to overlook those warings... It would be really great if ward failing would immediately abort the build process with a suitable error :)

**Comment by rbehrends** [comment]
First, I think it's rather more important to fix the underlying issues, which is generally the result of system include files using gcc/clang specific extensions (or more recently, C11 stuff).

The alternative is to either (1) skip system include files (which would require some non-trivial parser changing, but should be doable [1]) or (2) use standardized system include files that we know will not create such problems.

Note that Ward doesn't hide errors; if it can't parse a file, it will simply copy the original file (meaning that read and write guards are missing). This is why I don't understand [this commit message](https://github.com/gap-system/gap/commit/f2472987d9422ccfebce0a2b788e0bbdd683f000). That the code compiled despite a missing `pthread.h` must have had an unrelated reason; without `pthread.h`, `pthread_mutex_t` is not defined, which makes both Ward and the C compiler fail (but note that any C compiler has to give up, too, since it can't know the type).

My major concern is that funky stuff in system header files makes building HPC-GAP fragile on certain platforms; on the other hand, stopping on errors makes it also difficult to figure out and fix the issues on those platforms (note that the worst that can happen is missing read/write guards). Hence why I'd like Ward's parser to be independent of system header files in the long term: then we can consider going to errors instead of warnings.

[1] The primary problem with parsing C without system include files is that in order to parse C code, you need to be able to distinguish between typedef symbols and other identifiers. I may be able to carry my work on Singular (where I had to deal with this problem also) over.
