### ISSUE TITLE
Installer for GAP 4.9 on windows still refers to gap4.8

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#2482]
The default install directory is gap4r8

The default start menu folder is GAP 4.8.10

**Comment by alex-konovalov** [comment]
Could you confirm whether this happens when the previous GAP installation has not been uninstalled using the "Uninstall" from the menu? If so, I will reiterate that in installation instructions. Then I will see if the default path can be done differently in https://github.com/gap-system/gap-distribution/issues/53

**Comment by alex-konovalov** [comment]
Closed by https://github.com/gap-system/gap-distribution/commit/ed39680aa339d9d95ff92a382513f0a5f41f612a
