### ISSUE TITLE
Adjust documentation of -T command line option

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#2546]
This comes from the discussion in #2530.

Change the documentation of `-T` to say that it disables the break loop *and* the traceback. Currently the documentation seems to see printing a traceback as part of the "break loop behaviour", which I think one should separate.
The doc says:
```
-T
     suppresses  the  usual  break  loop  behaviour of GAP. With this option GAP behaves as if the user quit
     immediately  from  every  break loop. This is intended for automated testing of GAP. This option may be
     repeated to toggle this behavior on and off.
```

**Comment by fingolfin** [comment]
Sure, why not. Perhaps like this:
"... With this option GAP behaves as if the user quit immediately  from  every  break loop, and also suppresses displaying any error backtrace."

Although not everybody will know what a "backtrace" is; but the manual at least helpful links `?backtrace` to `Where`, so that should be OK.
