### ISSUE TITLE
Allow packages to use ISO 8601 dates in their PackageInfo.g

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2727]
It would be nice if packages could also specify the release date in ISO 8601 format, i.e., as `YYYY-MM-DD`. This is less ambiguous than the current `DD/MM/YYYY` (which e.g. Americans may confuse with `MM/DD/YYY`).

Besides needing to modify `lib/package.gi` and the documentation, it may also be necessary to modify the package distribution.

This might be a good "first issue"?

**Comment by alex-konovalov** [comment]
Cf. also https://github.com/gap-system/gap-distribution/issues/20. 

I think we can implement this in a way that both formats will be permitted concurrently, and that `ValidatePackageInfo` will display an advice to switch to ISO 8601 (maybe at some info level, otherwise this will show up too often if #2726 is merged). 

Indeed, not a problem to detect whether the date is in `YYYY-MM-DD` or `DD/MM/YYYY` format.

**Comment by cdwensley** [comment]
Date := "28/08/2018"  is converted by GAPDoc to "28 August 2018" in a manual front page, whereas 
Date := "2018-08-28" remains unchanged, which is not as nice.  Perhaps @frankluebeck can comment?

**Comment by fingolfin** [comment]
Indeed, AFAIK does nothing with title pages. But we can certainly add support to ISO dates in GAPDoc, too. Alternatively, we could simply convert the date from ISO 8601 to the "old" date format on the fly while loading, thus preserving full compatibility with any code that might for whatever reason try to parse these dates.

**Comment by wucas** [comment]
I'm working on a PR to change `ValidatePackageInfo` so it accepts both formats.
