### ISSUE TITLE
docs: command line options "-c" is not documented.

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#273]
I am not sure what is meant for -- other than what I can read in the code, that is: it modifies `SyCacheSize`, which is the "size of the data cache". And this affects gasman somehow. But it is unclear to me whether it has any real-world noticable impact; and whether anybody uses it.

It was apparently added before the initial CVS import in July 1996.

In summary: We should either document it, or remove it.  My guess is that the latter option is the best choice, but perhaps somebody knows better?

**Comment by stevelinton** [comment]
The idea was to keep the "young generation" in GASMAN to a limited size so that it would fit in cache. This forces more, but shorter partial garbage collections.

I haven't tried it in many years, but I don't recall it ever producing measurable speedups. On the other hand that was in the days of 256KB caches. I don't know if it would be useful on a more modern CPU.

**Comment by frankluebeck** [comment]
I have made a few tests yesterday. You can easily see the difference by trying `gap -g -g`, and then for example `ReadLib("../tst/testinstall.g");`. Then run the same in a GAP called with `gap -g -g -c 1m`. On my hexa core pentium cpu with 12MB cache size the latter is about  30% slower (it is worse with `-c 10m` and the slowdown is about the same in the range `-c 500k` to `-c 4m`).

So, the default (that is `-c 0k`) seems always better. 

How about adding a short description to the documentation, but also saying that in the current implementation a non-zero argument doesn't seem to be useful.
