### ISSUE TITLE
Strip GAP executable?

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#2760]
On my system, GAP master:

```
# ls -lh gap
-rwxr-xr-x 1 makx makx 20M Aug 29 18:52 gap*
```

(20 megabytes...)

```
# strip gap
# ls -lh gap
-rwxr-xr-x 1 makx makx 2.4M Aug 29 18:54 gap*
```

Should we be stripping the executable, at least when building without `--enable-debug`?

**Comment by fingolfin** [comment]
IMHO, stripping is something that I'd do as part of `make install`, but otherwise, I wouldn't want it to happen -- I frequently debug non-debug builds of GAP (because they are much faster, and of course sometimes bugs vanish with `--enable-debug`); if we stripped the binary automatically, I'd have to edit the makefile and relink each time (and would of course forget that all the time, etc.).

**Comment by alex-konovalov** [comment]
Hm, I have fresh macOS builds of master and stable-4.9 made today, and there `gap` is 2.3 and 2.4M respectively. Is is an OS-specific thing?
