### ISSUE TITLE
analog of ViewObj that stores output in a memory area

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#2839]
For interfacing with libgap, one wants to be able to store the output of `ViewObj()` called on a GAP object in a memory area, rather than being sent to `stdout`.

To explain by analogy: if `ViewObj()` is akin to [`printf()`](http://www.cplusplus.com/reference/cstdio/printf/), then I'd like to have something like [`sprintf()`](http://www.cplusplus.com/reference/cstdio/sprintf/).

Ideally, I'd rather not be doing memory management on that memory area (unlike how it's done for `sprintf()`, but this is of secondary importance).

----

In Sagemath's current [libGAP](https://bitbucket.org/vbraun/libgap) this is worked out by replacing `stdout` with such a memory area, but it's clear that it's very far for ideal, as it needs patches to GAP kernel.

**Comment by stevelinton** [comment]
There is an Operations `ViewString` which is supposed to do exactly this, so one solution might be to add `ViewString` methods to more objects  (after which they usually no longer need `ViewObj` methods).

**Comment by dimpase** [comment]
What I am thinking of using for the time being is
```
    str = NEW_STRING(0);
    out = CALL_2ARGS(   /* setting a string buffe
       GAP_ValueGlobalVariable("OutputTextString"), str, True);
     ...
    CALL_2ARGS(GAP_ValueGlobalVariable("PrintTo"), out, foo);
    CALL_2ARGS(GAP_ValueGlobalVariable("PrintTo"), out, baz);
     ...
```
and then `CSTR_STRING(str)` contains what I need. This does not strike me as optimal, though. (And perhaps there are pitfalls here I don't foresee).

**Comment by markuspf** [comment]
Note that @ThomasBreuer seems to think differently about `ViewObj` vs `ViewString`; Also note that `PrintTo` does *not* do the same thing as `ViewObj`. A potenially usefuel (yet again) hack would be implementing `ViewTo` which works like `PrintTo`.

**Comment by embray** [comment]
In Sage's interface to GAP (and the Sage-independent Python library I'm working based on the Sage interface) this issue is currently the only reason it needs to use the internal functions `OpenOutputStream()` and `CloseOutput()`.  Although it might still be useful to expose these in the libgap API, I wouldn't need them except for this.

The only way to consistently capture the `ViewObj` output is to set the output stream to a text stream, call `ViewObj()`, then `CloseOutput()`.  A `ViewTo` or `ViewObjTo` (however you want to name it) global function which does effectively the same thing would also alleviate this problem.

It's unfortunate that (for understandably historical reasons) that `ViewString` and `ViewObj` are two completely independent operations that can, if they want, do complete different things.  A sensible thing to do would be to implement `ViewString` and have `ViewObj` delegate to it, and that is done for some objects in the standard library, but of course this is not done consistently across the GAP extended universe so can't be relied upon.

**Comment by embray** [comment]
GAP.jl basically does the same thing, but defines a new GAP function `STREAM_CALL` for this purpose.  Having this in GAP itself could also be useful: https://github.com/oscar-system/GAP.jl/blob/2d383fcecd48bbcc90b520cf6dec3217175a76c0/pkg/JuliaInterface/src/JuliaInterface.c#L320

**Comment by ChrisJefferson** [comment]
The short version is indeed the relationships between functions like `ViewObj` and `ViewString` and friends should be clearer, with clear delegations, but previously attempts to "clean this up" have suffered from there just been too much code, and also because GAP package tests are typically based around matching strings, cleanups which introduce changes in how objects print lead to breaking lots of tests.

**Comment by fingolfin** [comment]
There is now `CALL_WITH_STREAM` in the GAP kernel (and it will be in GAP 4.12, to be released tomorrow). This is based on `STREAM_CALL` from GAP.jl (and GAP.jl already has been using `CALL_WITH_STREAM` for some time now).

**Comment by dimpase** [comment]
OK, thanks.

**Comment by dimpase** [comment]
I'm trying to revive [gappy](https://gappy.readthedocs.io/), and I am again facing this issue;  e.g. I'd like to replace the old 1-argment version of `OpenOutputStream` with something equivalent. 

Any pointers? Can this be done with documented  libgap API?

**Comment by fingolfin** [comment]
from GAP.jl:
```gap
BindGlobal( "StringDisplayObj",
function(obj)
  local str, out;
  str := "";
  out := OutputTextString(str, false);
  SetPrintFormattingStatus(out, false);
  CALL_WITH_STREAM(out, Display, [obj]);
  CloseStream(out);
  return str;
end );

BindGlobal( "StringViewObj",
function(obj)
  local str, out;
  str := "";
  out := OutputTextString(str, false);
  SetPrintFormattingStatus(out, false);
  CALL_WITH_STREAM(out, ViewObj, [obj]);
  CloseStream(out);
  return str;
end );
```

**Comment by dimpase** [comment]
hmm, that's certainly not libgap API, it's just straight GAP, involving a undocumented GAP function `CALL_WITH_STREAM`.
Any reason it's not in GAP itself?

**Comment by fingolfin** [comment]
The function `CALL_WITH_STREAM` is "undocumented" alright, but it was introduced for just this purpose. And it is in "GAP itself", so I don't really understand your question.

If you'd like a single libgap function for doing what you want: PR welcome.
