### ISSUE TITLE
Add PrintNextApplicableMethod()

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#2860]
A convenience function that basically repeats the last `PrintApplicableMethod(oper, args, 0, i)` but with `i+1`.

**Comment by fingolfin** [comment]
There is no `PrintApplicableMethod` in GAP; I never heard of it (or at least did not recall hearing about it) before, a quick grep reveals that it is from the `utils` package, so you could request this there. (Although I must say, I'd just use arrow-up, then increment i manually).

(Personally, I don't quite see the utility of `PrintApplicableMethod` over `ApplicableMethod` either -- what does it do that e.g. `ApplicableMethod(oper, args, 6, i)` or `Print(ApplicableMethod(oper, args, 1, i));` do not do?)

**Comment by cdwensley** [comment]
The operation PrintApplicableMethod came about because I get very confused by the output of ApplicableMethod, and do not necessarily want a long list of methods before a function listing.  Then, once it existed, Utils seemed a reasonable place to put it.  A PrintNextApplicableMethod could easily be added to Utils, if that were thought useful.  Better still, revise ApplicableMethod, making PrintApplicableMethod redundant.

**Comment by ssiccha** [comment]
So `PrintApplicableMethod` definitely does not offer any additional features over `ApplicableMethod`. I just find it more convenient for a quick look. First, I don't have to do an additional `Print` or `PageSource` Second, `PrintApplicableMethod` prints the location of the method's source code. (Third, I tend to forget the order of the arguments to ApplicableMethod` and always have to look them up)
I think its easier to remember and more convenient to first do `PrintApplicableMethod(oper, args)`; and then `PrintNextApplicableMethod()` if one encounters a `TRY_NEXT_METHOD()` call.

**Comment by cdwensley** [comment]
@ssiccha  Entirely agree with your comments about convenience.  PrintApplicableMethod, as it currently exists, claims to be callable as PrintApplicableMethod( our, [params], 0, nr ); but fails to work with nr<>1.  Have you already got a version of PrintNextApplicableMethod - if so, where should it go?  Or is it better to fix PrintApplicableMethod?  Or is it better to revise ApplicableMethod?

**Comment by ssiccha** [comment]
@cdwensley Hmm, I think PrintApplicableMethod with for arguments also worked for me. Let me check tomorrow.

**Comment by fingolfin** [comment]
Just to clarify: I deliberately wrote that I *personally* don't see the utility of `PrintApplicableMethod` as a given -- but that is not meant to belittle it, and of course fully I respect that others find it useful. I just don't understand how that comes about, and would love to understand it better, in the hopes that perhaps the feedback can be used to make `ApplicableMethod` more use friendly.

Specifically, I don't understand how this
```
gap> PrintApplicableMethod(FrattiniSubgroup, [CyclicGroup(IsPcGroup, 9)], 0, 1);
this method is contained in lines [1232,1246] of file:
    /Users/mhorn/Projekte/GAP/gap.github/lib/grp.gi
function ( G )
    local i, abinv, indgen, p, q, gen;
...
```
is more helpful than the following (in fact, to me it is strictly less helpful, as there is no `FILENAME:LINE` string I could Cmd-click it in iTerm to open the function in my editor):
```
gap> Print(ApplicableMethod(FrattiniSubgroup, [CyclicGroup(IsPcGroup, 9)], 1, 1));
#I  Searching Method for FrattiniSubgroup with 1 arguments:
#I  Total: 13 entries
#I  Method 6: ``FrattiniSubgroup: for abelian groups'' at /Users/mhorn/Projekte/GAP/gap.github/lib/grp.gi:1230 , value: 134
function ( G )
    local i, abinv, indgen, p, q, gen;
...
```

It is only two letter more to type (one `(` and one `)`), and provides additional information, which to me seems relatively easy to understand. But of course I know this output quite well, so this is probably a classic case of not seeing the issue anymore after a certain point. Since you referred to the latter output as confusing, I am curious to learn what about it you find confusing -- perhaps we can come up with changes that make it less confusing, while retaining its utility?

BTW, independently of this, I also thought before about adding "options" (in the sense of <https://www.gap-system.org/Manuals/doc/ref/chap8.htm>) to `ApplicableMethod` that one can use instead of those magic constants 1 to 6 in the third argument, in order to adjust the output.


In any case, it seems to me that the *original* issue here (adding a `PrintNextApplicableMethod` method) really belongs on the issue tracker of the `utils` package. So I recommend filing this there and then closing this issue here; and perhaps opening a new one titled "Ideas for improving ApplicableMethod" or so.

**Comment by ssiccha** [comment]
> claims to be callable as PrintApplicableMethod( our, [params], 0, nr ); but fails to work with nr<>1.
@cdwensley Do you have any examples that don't work with your gap installation? For me it works fine with the example from the manual and also with `PrintApplicableMethod( String, [Group(())], 0, 2 );`.

**Comment by ssiccha** [comment]
> Just to clarify: ...

@fingolfin That was perfectly clear to me. :)

> (in fact, to me it is strictly less helpful, as there is no FILENAME:LINE string I could Cmd-click it in iTerm to open the function in my editor)

Good point, I'll open an issue for that on the utils package.

> Since you referred to the latter output as confusing, I am curious to learn what about it you find confusing -- perhaps we can come up with changes that make it less confusing, while retaining its utility?

I personally don't find the _output_ of `ApplicableMethod` confusing. @cdwensley mentioned that:
> The operation PrintApplicableMethod came about because I get very confused by the output of ApplicableMethod, and do not necessarily want a long list of methods before a function listing.

Did you use it with `ApplicableMethod( oper, args, 1, "all" );`, @cdwensley? I guess the output can be a bit overwhelming if you use `"all"` as fourth argument. I wrote some remarks on that below. Could you elaborate a bit on that?

I will put the following things in a seperate issue:
> BTW, independently of this, I also thought before about adding "options" (in the sense of https://www.gap-system.org/Manuals/doc/ref/chap8.htm) to ApplicableMethod that one can use instead of those magic constants 1 to 6 in the third argument, in order to adjust the output.

These magic constants are what actually bugs me. I like your suggestion with being able to pass options to `ApplicableMethod` which adjust the output. It would be nice if one could get rid of the `printlevel` argument and just use a sensible default value instead (like e.g. 1). To me `printlevel` is just that weird extra argument that I have to remember to pass a `1` to.

After thinking a bit about the possibly confusing output I got the following: I guess it really depends on the 3rd and 4th argument. If I do `ApplicableMethod( String, [Group(())], 1, 2 );` I get:
```
#I  Searching Method for String with 1 arguments:
#I  Total: 70 entries
#I  Method 2: ``String'' at /home/sergio/projects/gap/lib/teaching.g:794 , value: 
10000
#I  Skipped:
#I  Method 
10
 : ``String: for a group with generators'' at /home/sergio/projects/gap/lib/grp.gi\
:4259 , value: 36
function( G ) ... end
```
I imagine the `Skipped:` on the fifth line could be confusing. First, it seems a bit unnecessary that gap tells us thing about the highest ranked applicable method, although we only requested the second one.  Second, that it says `Skipped:` for the first method in addition sounds like it would be not applicable. And the line breaks are a bit awkward.

If I do `ApplicableMethod( IsCyclic, [Group(())], 1, "all" );` I get the following output, which I guess can also be confusing for the same reasons.
```
#I  Searching Method for IsCyclic with 1 arguments:
#I  Total: 7 entries
#I  Method 1: ``IsCyclic: system getter'' at /home/sergio/projects/gap/lib/grp.gd:
157 , value: 2*SUM_FLAGS+38
#I  Skipped:
#I  Method 4: ``IsCyclic'' at /home/sergio/projects/gap/lib/grp.gi:35 , value: 36
#I  Skipped:
#I  Method 
5
 : ``IsCyclic: generic method for groups'' at /home/sergio/projects/gap/lib/grp.gi:
44 , value: 35
#I  Skipped:
#I  Method 
7
 : ``IsCyclic: default method requiring categories and checking properties'' at /ho\
me/sergio/projects/gap/lib/grp.gd:157 , value: 1
#I  Skipped:
[ function( obj ) ... end, function( G ) ... end, function( G ) ... end, 
  function( <1 unnamed arguments> ) ... end ]
```

**Comment by ssiccha** [comment]
I closed this issue so I guess further discussion should be done in #2871.
