### ISSUE TITLE
SegFault: equality of records

### ISSUE THREAD

**Issue by siccha** [gap-system/gap#287]
After playing around with records and Immutable() a bit, I found a segmentation fault using the `=` operator. 
This is the code I used:
```
x := rec( a := [] );
x.a := x;
y := Immutable(x);

a := rec( a := [] );
a.a := a;
```
`x, y, a` are records containing a pointer to themselves.
Both `x=y;` and `x=a;` yield a segmentation fault.

**Comment by ChrisJefferson** [comment]
Interesting!

This certainly shouldn't crash, but I am pondering if solving this problem in full generality is feasible, or we should aim to produce an Error. 

In a similar vain,

```x < y``` segfaults as well, and also building the same construction with lists:
```
gap> x := [];;
gap> x[1] := x;
[ ~ ]
gap> y := [];;
gap> y[1] := y;
[ ~ ]
gap> x = y;
fish: Job 2, 'gap' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by stevelinton** [comment]
This was discussed in 2009. Certainly then we couldn't see a way to get a graceful failure in this case that wouldn't have performance implications for common operations such as rec(a := 1) = rec(a := 2).

It would be possible to write a function that safely compared "loopy" lists and records, but I suspect the performance cost of making it the default method for = might be unacceptable.

**Comment by frankluebeck** [comment]
(1) This behaviour is the same in all GAP versions.

(2) What answer do you expect from:
```
    x := rec(a := ~);
    x2 := x;
    y := rec(a := ~);
    x2 = x;
    x = y;
```
? The comparisons `x=x` and `x2=x` yield `true` because GAP first checks if these are *identical* objects.  In `x=y` GAP has two different objects which are records with one component `a`. Then these components are compared recursively. And so on . . .  Should x and y be equal or not? There may be arguments for both possibilities or for running into an error.

(3) It would be nice to detect an error in this example instead of crashing the GAP session. But, as stevelinton said, this is probably difficult without a significant performance penalty.

(4) As a conclusion I suggest to not assume that any two GAP objects can be compared by `=`  (and even less by `<`). Only use `=` for pairs of objects for which you  know what GAP means by the result.  (In certain cases for which GAP does a `=` comparison, you may not agree with the result. Try `Group((1,2,3),(1,2)) = Group((1,2),(2,3));` and  `FreeGroup(2) = FreeGroup(2);`. In many more cases it is not obvious what `=` should mean.)

**Comment by siccha** [comment]
Okay, I'm closing the issue then. Thanks for all the explanations!

**Comment by ChrisJefferson** [comment]
One option would be to look at at least catching the infinite stack recursion and entering a break loop, as we would for infinite-recursing GAP code. This wouldn't produce a useful error message, but would at least stop the seg-fault (would it be a useful improvement? Not sure).

**Comment by stevelinton** [comment]
@ChrisJefferson this might be possible. We could identify all the kernel functions like EqPlist (and for all the other operations) which are potentially recursive and have them increment and check  a thread-local (global) depth counter.  We'd need to be careful to make sure the counter was decremented appropriately on every possible return path. The cost of this should be negligible compared to the work these functions are already doing to get list lengths etc., even in the simplest cases.
