### ISSUE TITLE
Unhelpful printing of declared but not installed functions

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#2926]
This just confused a user; it's probably "just" a bug in function viewing/printing.

```
gap> DeclareGlobalFunction("Cheese");
gap> Cheese;
function( args... ) ... end
gap> Print(Cheese);
function ( args... )
    <<kernel or compiled code>>
end
gap> Cheese();
Error, Cheese: function is not yet defined
not in any function at *stdin*:7
```

**Comment by fingolfin** [comment]
What would you suggest as "better" behavior?

**Comment by stevelinton** [comment]
So the printing is "formally" correct. `Cheese` is a function, created by `NewGlobalFunction` in `opers.c` with all its handlers set to `DoUninstalledGlobalFunction`. 

It would obviously be more helpful for `ViewObj`  (or `ViewString`) and `PrintObj` to do something more useful for this object.  Fixing `PrintObj` would be fairly straightforward because it's in the kernel and we can just inspect the handlers, but it risks eventually having a lot of special cases in `PrintFunction` which is not elegant. Some hook-registration scheme could be used. 

Fixing `ViewObj` is a bit more involved, because that all happens at the `GAP` level. I can see a few ways of doing this:

1. Add a kernel function that simply tells you if a function is of this kind.
2. Like 1. but do something a but more general that allows a variety of "special" functions to tell the GAP level about themselves.
3. Move `ViewString` for functions back into the kernel where all the information it needs is available
4. Instead of setting `Cheese` to be a magic function defined in the kernel like this, make it another kind of `ToBeDefined` object with a `CallFuncList` method (and suitable `ViewString` etc. methods).

I'd favour 4, I think. because it makes what's going on transparent at the GAP level and merges two mechanisms (global functions and global values) into one.

**Comment by fingolfin** [comment]
This seems to explain the "how", but the "what" is still not clear to me: What would you suggest as "better" or "more useful" behavior, concretely (and regardless of how to and whether we can implement it)?

Regarding your point 4: well, the nice thing about the current approach is that we can just reuse the `T_FUNCTION` object. With your approach, we'd have to either "swap master pointers", or else modify the tnum of the object (both practices I thought we rather wanted to reduce, for the sake of HPC-GAP); or else, to "unbind and rebind" the variable referencing the function (but that presents its own issues, of course).

**Comment by ChrisJefferson** [comment]
While not perfect, we could "just" set the location of the function, to get output like

```
function ( args... )
    <<kernel code>> from "Cheese" has been declared but not defined:1
end
