### ISSUE TITLE
streamlining libgap API

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#2957]
Currently a number of functions exported in `libgap.h` is very small, insufficient for even very limited use cases. 

As well, there are potential name clashes, e.g. `T_INT` with Python.

**Comment by dimpase** [comment]
@jdemeyer

**Comment by fingolfin** [comment]
It's not clear to me what you are saying / asking here. It seems you want to discuss something, but then perhaps you should give some more concrete suggestions and/or requests?

And I've discussed T_INT a 100 times now with various people on Sage, I don't know why it keeps coming up again and again: This is an enum, so it does not affect the binary. It only affects code using / parsing the headers. The suggested workaround then was that you `#define T_INT T_SOMETHING_ELSE` before including GAP's `compiled.h`. I thought @nthiery had tried this during our meeting in 2017, but maybe he only said it was plausible, and then it was never pursued? Anyway,  If that doesn't work for some reason after all, please provide concrete information on what you tried, and what the exact failure was, and we can think more about it. Just repeating the same question won't get us ahead on this topic, though.

**Comment by jdemeyer** [comment]
I think the best solution would be: inside GAP, you use the name `GAP_T_INT` but then you make an alias `T_INT` for it. So basically replace
```
enum TNUM {
...
T_INT,
...
}
```
by
```
enum TNUM {
...
GAP_T_INT,
...
}
#define T_INT GAP_T_INT
```
Then `libgap.h` could have
```
#undef T_INT
```
to avoid the name conflict.

**Comment by fingolfin** [comment]
I am not sure how that is the best solution. I am sure it is the easiest solution for SageMath, but I find it rather undesirable for GAP. So far, still nobody has said why the solution I propose is infeasible or problematic or whatever. Until that happens, I for one won't make such a change (but perhaps somebody else working on GAP is willing to do so *shrug*). Once it is clear why this is difficult for you, I'll be happy to to reconsider, of course.

Anyway, to me, a much better long-term solution would be if `libgap-api.h` was standalone, so you would include only that, and would thus never even "see" `T_INT` or anything else from `objects.h`. Of course that is not feasible right now, and first requires adding more dedicated APIs to `libgap-api.h`. I'd much rather work towards that goal.

Perhaps you guys could add a link to your VCS here (<https://github.com/sagemath/sage> ?), and tell us where the relevant files for your GAP interface are, in the latest version (the one meant to use `libgap-api.h`; the stuff @dimpase was working on; what I see in the sage `develop` branch does not use it). Then it'd be easier to get an overview of things that is hopefully more up-to-date than what is on <https://hackmd.io/emNi76svSWCh1fBeLKqPdA>.

**Comment by ChrisJefferson** [comment]
Fixing T_INT specifically seems like a very specific hack just for Sage, while (hopefully) libgap might be useful for other systems.

**Comment by dimpase** [comment]
> Fixing T_INT specifically seems like a very specific hack just for Sage

`T_INT` is [used](https://github.com/python/cpython/blob/b08746bfdf64e55ce33516f2065fa2aa4f51be95/Include/structmember.h#L28) in Python headers, and happends to be `1`, so anyone building a Python extension using libgap would run a danger of errors due to `T_INT` being set to a wrong constant.

**Comment by ChrisJefferson** [comment]
Well, it's a hack just for Python, we also share T_CHAR and T_BOOL I think

**Comment by fingolfin** [comment]
Yes, Dima, we understand that this is the problem you are facing (although I indeed wonder why T_CHAR and T_BOOL aren't a problem?!?). What I don't understand is why you don't just do this:
```C
#undef T_INT
#define T_INT GAP_T_INT
#include "compiled.h" // GAP headers
#include "libgap-api.h"
#undef T_INT
#define T_INT 1
```
If you need this in multiple places, you can even put it into a header file of your own.

**Comment by jdemeyer** [comment]
> What I don't understand is why you don't just do this:

First of all, that's not the right question to ask because it seems to presuppose that GAP isn't going to change and that other projects should just cope with that. Instead, the right question to ask is the following: what is the best way to make GAP compatible with other projects (in particular CPython)?

I proposed that GAP uses `GAP_T_INT` instead but keeps `T_INT` for backwards-compatibility. That way, you fix this conflict once and for all (instead of requiring changes to everybody who combines GAP and Python) and you don't lose any compatibility within GAP itself.

**Comment by fingolfin** [comment]
Another question that was not yet answered: Why are you only worried about `T_INT`? What about `T_CHAR` and `T_BOOL`, which also clash?

**Comment by dimpase** [comment]
In my view, it's Python that should gets its things in order, as it's using  short global `#defines` for its types, something that looks quite outdated and dangerous.
Indeed, the following compiles and produces patently wrong results:
```
#include <stdio.h>
enum foo { /* say, this comes from GAP's  headers */
	T_INT  = 0,
	T_BOOL = 7
};
#define T_INT 42  /* and this is Python's headers */
int main() {
	int r;
	r = T_INT;
	printf("%d\n", r);  /* oops, T_INT is 42... */
	return 0;
}
```
In contrast, if Python were a good citizen and used enum, too, it would not be a problem, as the following
does not compile:
```
#include <stdio.h>
enum foo { /* say, this comes from GAP's  headers */
	T_INT  = 0,
	T_BOOL = 7
};
enum bar { /* assume this comes from Python  headers */
	T_INT  = 42
};
```

**Comment by nthiery** [comment]
Max: I apologize that we are not very well organized here on the Sage
side and there are so many of us (partially) involved. Which means for
you as many people that you have to interact with and explain things
to. Please take it as a sign of interest!

My two cents: GAP has gone a very long way in our direction, investing
a lot of time for us. Maybe some things are not absolutely perfect in
our opinions; but they are sooo much better than before. Let's move on
and get things working with GAP as it is now (unless of course we hit
a hard hurdle). Once we will have gained more experience, it will be
time to redo an overall assessment together with the GAP team (and
other libGAP users) and think about how to evolve libgap if needed.
Those evolutions should be easy to cater for a posteriori.

**Comment by fingolfin** [comment]
@nthiery Indeed, that sound reasonable. Of course we'll try to help overcome any hard hurdles, don't hesitate to bring them up. And my offer stands: if you point us at a VCS branch with your work on makinge SageMath use `libgap-api.h`, I'd be happy to take a look at it and make suggestions for both you and also for us -- indeed, as we explained elsewhere, we are very willing and interested in adding more APIs to `libgap-api.h`, based on your needs; but for that, we need to know what those are.

**Comment by markuspf** [comment]
As I mentioned a couple of times before, and again at Luxembourg this week: Do make suggestions by making pull-requests that update `libgap-api.{c,h}` so that we have an API that caters for users and is not made up in isolation (by me or anyone else, really).

I have no idea what a useful API will look like. I did write a lengthy email on the GAP mailing list about what the points are that I think need to be addressed in the end. (https://mail.gap-system.org/pipermail/gap/2018-August/001123.html)

**Comment by dimpase** [comment]
> point us at a VCS branch with your work on makinge SageMath use `libgap-api.h`

it is here:
https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/WIP/libgap410

look at https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/WIP/libgap410/src/sage/libs/gap
for the interface with libgap (it's written in Cython, and is quite broken ATM, with segfaults deep inside GAP, leading to an infinite recursion in GAP's error reporting :-( )

The work on it happens on https://trac.sagemath.org/ticket/22626

**Comment by jdemeyer** [comment]
> Yes, that question presupposes that we won't change `T_INT`, correct. Because that has been and still is our supposition.

But why? If `T_INT` is a problem for porting GAP, why do you not want to change it?

To me, this feels too much "us versus them" instead of "let's help eachother".

> In any case, I already explained that the correct solution from our point of view is that you don't use any GAP header other than libgap-api.h

Sage actually uses the `T_INT` value from GAP. So regardless of which headers it includes, those headers need to give access to `T_INT`.

**Comment by ChrisJefferson** [comment]
If we define a clean API, then in that API we can define an alternative name to T_INT.

I feel we are trying to help, by separating out into one place what sage uses. At the moment sage (and other integrations) just dive into gap's internals. Maybe tomorrow I'll remove T_INT, or add a T_OBJECT that would clash with python again, or clash with some other macro. At present I don't know what sage needs, and therefore integration will continue to be fragile and break frequently.

**Comment by dimpase** [comment]
I don't like these hacks with `#undefine/#define`. There could be a suitably prefixed, say, by `libGAP_`, or `libgap_`, enum in `libgap-api.h`, equivalent to the enum with `T_INT`, and the original GAP's enum kept internal.

I could volunteer to add into GAP build system a generation of such an enum from the internal enum (assuming there is no opposition).

In the long run, however, I understand there is a plan to refactor GAP command line interface to use libgap, and then such a libgap-based GAP would rather use what's in `libgap-api.h`, no?

**Comment by fingolfin** [comment]
@jdemeyer First of all, that's not the right question to ask because it seems to presuppose that `T_INT` is a problem for "porting" (???) GAP, or rather, for using GAP as a library, which it isn't in general: at least two projects other than SageMath are doing fine despite it, so this is really SageMath specific. Moreover, it is also presupposes that making `T_INT` usable from client code is desirable -- which it isn't. As a matter of fact, there is zero reason for SageMath to use GAP's `T_INT`. Indeed, looking at the SageMath code for accessing GAP, it is not actually used in any meaningful way.

If SageMath ever needs to test if something is a GAP immediate integer, it should use `IS_INTOBJ` instead (or some new API to be added to `libgap-api.h`).

@dimpase I am not aware of such a plan for refactoring GAP's command line interface.

**Comment by jdemeyer** [comment]
> Yes, I suggested so, see e.g. https://hackmd.io/emNi76svSWCh1fBeLKqPdA

I assume that whatever API you come up with, it will either include all `T_*` enums or none of them. So if you say that we should use `IS_INT` instead of `T_INT`, there should also be replacements for `num == T_MACFLOAT` for example.

**Comment by dimpase** [comment]
I think that using these `IS_...` function calls on GAP objects is not very convenient. Ideally, one would rather have a mapping from GAP types to the types of the caller, and dispatch on this mapping using e.g. function pointers rather than have a long list of these
```
if ...:
     make_bla
if ...:
     make foo
...
```
IMHO it's a reasonable request to have a complete mapping like this exported by GAP, as an enum or otherwise.

**Comment by markuspf** [comment]
@dimpase, @jdemeyer has any one of you read the above cited hackmd? It really stops just about short of writing the code for you.

Have you *tried* implementing this proposal? Have you run into concrete problems trying to implement this proposal? if not, can you please try implementing it?

Talking about hypotheticals is not helpful.

**Comment by markuspf** [comment]
> IMHO it's a reasonable request to have a complete mapping like this exported by GAP, as an enum or otherwise.

To which end? Do you have a usecase in mind?

**Comment by ChrisJefferson** [comment]
No, it's not reasonable to use an enum. In fact, we've been moving away from using direct access to the enum internally where possible, because there are 3 different values for ints (immediate, large positive and large negative), twenty different plist types (and that's not including the 3 boolean list enums and 3 string list enums).

Also, if you want to know if something is a "list-like" object (which is what you should probably want to know most of the time, in the case of lists), you can't figure that out from the enum anyway, as some objects satisfy IsList, and others don't.

**Comment by jdemeyer** [comment]
>  It really stops just about short of writing the code for you.

Unless I missed something, I doesn't say what to do with `T_MACFLOAT` or the other `T_*` enums.

**Comment by jdemeyer** [comment]
> Talking about hypotheticals is not helpful.

The naming conflict with `T_INT` certainly is not hypothetical. So we need a solution for that first.

Besides that, there are quite a lot of similar short names, like `Obj`, `UInt`, `True`, `EQ`, ...
As far as I know, none of these actually conflicts with anything, but those still worry me.

**Comment by dimpase** [comment]
> @dimpase, @jdemeyer has any one of you read the above cited hackmd? It really stops just about short of writing the code for you.

I read it and [tried using it to repalce Sage's libGAP with the new libgap](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/WIP/libgap410), certainly. I ran into hard to debug problems, and asked people, e.g. Jeroen, to look into them. Jeroen, however, wanted to discuss first with Marcus, and as a result we have opened this very issue.

**Comment by markuspf** [comment]
> > It really stops just about short of writing the code for you.
> 
> Unless I missed something, I doesn't say what to do with `T_MACFLOAT` or the other `T_*` enums.

And I quote:

> But in many cases, it is probably better to use GAP functions to perform the tests:

**Comment by markuspf** [comment]
So here's the next issue right there: Would it be possible to make a reasonably small standalone libgap python wrapper that does not depend on the whole of SageMath? That would be much easier to contribute to.

**Comment by dimpase** [comment]
> Would it be possible to make a reasonably small standalone libgap python wrapper

This is a very good suggestion, something to consider. One can either have a basic wrapper that does not extend the Python's arithmetic to GAP objects, and only allowing basic Python types (its numerical tower and strings) to be received from GAP, or going for something more interesting, such as adding GAP interface to [scipy](https://www.scipy.org/), which is very mainstream, or [numpy](https://www.sympy.org) - which is not as popular, but has some basic group theory in.

**Comment by jdemeyer** [comment]
> So, start with something standalone, something that'll make it easy to transfer work to SageMath. Make that work, then slowly add features as needed by Sage.

The problem with that is that we already have a working Sage <-> GAP interface based on Volker Braun's libGAP. We don't want to replace that by something having less features.

**Comment by markuspf** [comment]
@nthiery @dimpase @jdemeyer this is all fine and well, but none of us wants to install SageMath and understand all the ins and outs of it to help you out with a better library interface for GAP. Whenever you want two complex pieces of software to communicate you have two choices: 
 1) Find an expert (better yet a group of them) who knows both things and does it
 2) Find experts on both sides and find a non-obstructive interface they can talk about


Number 1) clearly doesn't apply here, since I have still not met anyone who'd do it (and such an interface might actually end up being very messy since both sides know internals of systems they just tap into. But thats a digression).

So lets run with 2). 

For such an interface to be successful you must not make the barriers for either side too high (otherwise you're back at 1) and we already established that's not going to happen anytime soon). So what we need in this case is a python package that binds to GAP and provides the functionality that SageMath needs.

Since we (the GAP developers) do not know what functions SageMath (or any other user of GAP as a library) needs, and having a bit of code that randomly calls GAP internals is not exactly the definition of "need", the GAP API isn't very well-defined and we have to add bits to make it work. We offered doing that, but none of us want to install and compile SageMath to do that.

So to help, I made the thing I asked for above:

  https://github.com/markuspf/py-gap
  
None of us is, btw, saying that we cannot or must not reuse bits of SageMath's libgap code but with the above code I can test with little overhead what's going wrong and why GAP is crashing (and people like @fingolfin, @ChrisJefferson, @sebasguts could, too).

Do you not think that this is a more productive way of going about the interfacing problem?

**Comment by dimpase** [comment]
Thanks. Certainly, the hard part of Sage's libGAP is interaction with GAP is relatively small, but it includes maintaining a dictionary of GAP objects that must be kept alive by GC, and error processing, as Python's way of interaction is often in a try/except loop, and this is not a choice of Sage, it's already there in Python, e.g. in a basic [getattr](https://docs.python.org/3/library/functions.html#getattr) function. 

A prototype should include this, e.g. show how to manipulate GAP's integers and lists of integers in Python, 
convert GAP's (lists of) integers to Python (lists of integers) should survive calls to GC, etc.

So, GAP's initialisation should include setting up GC callback (to maintain the dictionary of GAP's objects to keep alive) and an error callback, which should recover in a meaningful way. All this is very delicate and tricky to get right. E.g. I don't know what happens during GAP's error recovery (and that's where I am getting errors in my prototype).

**Comment by nthiery** [comment]
Hi Markus,

Thanks for kickstarting this Python-level binding. This sounds like a
good way to proceed indeed. Once we get the key features running
there, it should not be too hard to rebuild the higher level features
that we have in Sage (matching Sage types with GAP types) on top of
that.

Well, "we" ... by that I mean Sage devs, with the occasional help from
GAP devs. And am feeling rather uncomfortable rambling about it
without actually being able to contribute myself in the short run.

Cheers,
                                Nicolas

**Comment by markuspf** [comment]
Just to reiterate what @fingolfin said: I am not intending to develop this prototype for you, it will just be easier to debug issues and help with a smaller prototype. I am happy to transfer ownership of the repository above, or for anyone to copy and paste the three lines of code it contains.

**Comment by dimpase** [comment]
by the way, if there were a C++ wrapper for libgap (putting it in a named namespace, naturally), it would alleviate the very issue of name conflicts, and could still be used to build a Python extension.

**Comment by nthiery** [comment]
>    Just to reiterate what [1]@fingolfin said: I am not intending to
>    develop this prototype for you, it will just be easier to debug
>    issues and help with a smaller prototype. I am happy to transfer
>    ownership of the repository above, or for anyone to copy and
>    paste the three lines of code it contains.

Yes, that was my understanding, and it's definitely fair!

**Comment by jdemeyer** [comment]
>     1. Find an expert (better yet a group of them) who knows both things and does it

More realistically: find somebody who knows enough of both systems to make it work in a possibly hacky way and then clean it up afterwards with real experts.

Writing an interface from scratch and then hoping that it will work for SageMath looks unrealistic to me. It would be better to adapt the existing interface. That what's Dima been doing on https://trac.sagemath.org/ticket/22626 and I think that we are almost there.

To use the PARI bindings from SageMath as an example: those went through several major changes (from being hand-written to auto-generated, from a module in SageMath to a separate package, from copying all PARI objects to Python to just use pointers on the PARI stack) but the code was never rewritten from scratch.

**Comment by markuspf** [comment]
@jdemeyer, in our opinion then, good luck. Sorry.

**Comment by jdemeyer** [comment]
> But in many cases, it is probably better to use GAP functions to perform the tests:

OK, but that still doesn't solve the problems with naming conflicts because the header which defines `IS_INT` also needs `T_INT`.
