### ISSUE TITLE
ExternalSubsetOp incorrectly abuses types

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#296]
The following code doesn't work (thanks to @markuspf ). The problem is that the code tries to use some spare space in type objects, which is used by something else (I assume the code worked once, when type objects were smaller?)

````
gap> extS := ExternalSet(SymmetricGroup(4), [1..4],
                    GeneratorsOfGroup(SymmetricGroup(4)),
                    GeneratorsOfGroup(SymmetricGroup(4)),
                    OnRight);

gap> ExternalSubset(extS);
````

The easy fix would be to redefine XSET_XORBTYPE and XSET_XSET_XSSETTYPE to take values which are definitely free, but I wonder if a better plan would be to stop treating types as mutable objects? or have a well defined record (atomic record in HPC-GAP) attached to types which could be used for this kind of thing, rather than just finding a (hopefully) empty slot.

**Comment by fingolfin** [comment]
This code did not even work in GAP 4.4.12, i.e. it already produced an error there. Since this is only used to implement a (sub)tyle cache, I think we should just remove that. While that would slow down ExternalSubset a bit, I am not concerned about that, given that apparently nobody ever used it in the past, oh, 8 or so years :)

**Comment by markuspf** [comment]
With #297 merged, I'll close this issue.
