### ISSUE TITLE
Make developer's manual available online

### ISSUE THREAD

**Issue by embray** [gap-system/gap#2995]
There is a helpful manual (#1161) for performing development on GAP (in particular the documentation on GASMAN is nice to read).  I found it very instructive for figuring out what's going on in some areas.  However, it's not very easy to find if you don't know it's there.  It seems all the other interesting manuals included in the GAP sources are made available online at https://www.gap-system.org/Doc/doc.html so why not the dev manual?

I don't think being able to build the manuals should be a prerequisite to being able to read the dev manual :)

**Comment by alex-konovalov** [comment]
Glad that you find it helpful, but please be aware that at least parts of it may be severely outdated or incomplete. That's the reason why things are as such...

**Comment by embray** [comment]
That is true.  It would still be more useful to have than not though, especially for the GASMAN documentation.  Perhaps a large disclaimer could be added to it.

**Comment by embray** [comment]
Also, perhaps I'm missing some dependencies or something but I can't for my life get the docs to actually build in the first place.

**Comment by alex-konovalov** [comment]
Do you build them with `make manuals`?

**Comment by alex-konovalov** [comment]
See also https://github.com/gap-system/gap/wiki/Building-main-GAP-manuals

**Comment by embray** [comment]
Yes, I tried all that and it was blowing up.  I think I might have been missing some latex dependencies, but this just resulted in random exceptions from GAP that were non-obvious.  It's working for me now.
Nevertheless, I still think the information that *is* useful in the dev manual would be more discoverable if it were on the website (along with a bit fat disclaimer that you can't be held liable for any information in it that's out of date :)

**Comment by embray** [comment]
The more I've looked at it, it's definitely more out of date and incomplete than I thought.  Maybe it would b worth deleting altogether, or moving the bits that still are useful into a section of the reference manual.

**Comment by fingolfin** [comment]
At the last GAP Days, I went through the kernel part of the dev manual and fixed various issues in it. It's a bit more useful again now, I hope. Well, that chapter; many (most? all?) of the remaining chapters, less so... Perhaps we should ditch those, and then publish the dev manual again?

After having worked on that chapter of the dev manual, though I also wonder how useful it is to have it in GAPDoc. Because it doesn't really seem to use any of the features of GAPDoc, plus in GAPDoc, we don't get syntax highlighting for the C code. So perhaps we'd be better of converting the dev manual into a Markdown document? Or if we were to start using something like Doxygen to generate kernel "documentation", then most of the dev manual could be converted into Doxygen (or whatever) documentation, with direct hyperlinks to functionality referenced there...

**Comment by alex-konovalov** [comment]
1) Perhaps, except that we never actually published (i.e. redistributed with GAP) the dev manual. There was a "New features for developers" manual, which was then incorporated into the reference manual, maybe you had that in mind...

Alternatively, if the kernel chapter is ready, maybe move it into the reference manual?

2) Using another format depends on whether we want it to be available from GAP via `?` and `??` commands. Maybe converting to AutoDoc to make editing easier?

**Comment by fingolfin** [comment]
The dev manual is now available online at https://gap-system.github.io/gap/
