### ISSUE TITLE
package "carat" for 64-bit Windows: the archive contains 2 files with filename 'con' 

### ISSUE THREAD

**Issue by ignatsoroko** [gap-system/gap#3107]
This is the issue of version 4.10.0. (The version 4.8.7 doesn't have this issue.)

The zip file with 64-bit installation of GAP for Windows contains two files which have filename 'con':

pkg\carat\carat\src\con.c
pkg\carat\carat\tex\progs\con.html

They cause error when unzipping, since Windows cannot have a file with filename `con` (reserved for console).

**Comment by alex-konovalov** [comment]
Thank you @ignatsoroko - this is related to https://github.com/gap-system/gap-distribution/issues/55 (reported there, since it is technically not an issue about the core GAP system). This problem rarely occurs for the users of 32-bit GAP version which use `.exe` installer (which do not have offending files) but users of the experimental 64-bit version do not have an alternative.

As I've said in that issue, the solution [found here](https://social.technet.microsoft.com/Forums/ie/en-US/3601cb4e-e509-4046-bb39-a11f1f444459/cannot-delete-a-file-named-quotconpdfquot?forum=winserverfiles) is to call `del` in Windows command prompt specifying the full path as below (`\\.\` before the drive name is essential):

    del \\.\C:\gap-4.10.0\pkg\carat\carat\tex\progs\Con.html
    del \\.\C:\gap-4.10.0\pkg\carat\carat\src\con.c

The problem should be solved in the standalone Carat software, to which the GAP package Carat provides an interface. Luckily we have now GitHub repositories for both:
- https://github.com /gap-packages/carat maintained by @gaehler where this problem has been reported at https://github.com/gap-packages/carat/issues/5 
- https://github.com/lbfm-rwth/carat/ maintained by @DominikBernhardt where this problem has been fixed 11 days ago in https://github.com/lbfm-rwth/carat/pull/14

So it now waits till the new version of the standalone Carat will be released, and then the GAP package Carat will be updated.

In your case, if this is just an error message, but the unpacking continues (like I observe when I , then this issue may be closed. Otherwise, if unpacking terminates, please let me know, and I will think of a workaround.

**Comment by alex-konovalov** [comment]
Previous versions did not even attempted to build Carat under Windows, so it's archive supplied inside  the Carat GAP package was not unpacked.

**Comment by alex-konovalov** [comment]
I will then close this issue - hopefully the new release of Carat will be out soon.
