### ISSUE TITLE
In GAP MakeReadOnlyObj doesn't make objects immutable

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#3132]
Note that this is not in HPC-GAP.

In GAP I can do:
```
gap> l := [];;
gap> MakeReadOnlyObj(l);;
gap> l[1] := 1;;
gap> l;
[ 1 ]
```

I would find it more sensible if `MakeReadOnlyObj` makes objects immutable in GAP. At least until there is a proper `MakeReadOnlyObj` function in GAP, if we ever want one.

**Comment by ssiccha** [comment]
I have code that I want to run both under HPC-GAP and GAP. Currently I have to do `MakeReadOnlyObj` and `MakeImmutable` on an object to have it work in HPC-GAP and GAP.

**Comment by fingolfin** [comment]
As explained on PR #3136, in HPC-GAP, `MakeReadOnlyObj` also does not make objects immutable. Or rather, it only makes "external" objects immutable, because of this code in `src/objects.c:
```C
Int IsMutableObjObject (
    Obj                 obj )
{
#ifdef HPCGAP
    if (RegionBag(obj) == ReadOnlyRegion)
        return 0;
#endif
    return (DoFilter( IsMutableObjFilt, obj ) == True);
}
```
But for internal objects, e.g. plists, this does not currently happen. Indeed, one can verify this in HPC-GAP as follows:
```
gap> foo:=[1,2,3];
[ 1, 2, 3 ]
gap> IsMutable(foo);
true
gap> MakeReadOnlyObj(foo);
[ 1, 2, 3 ]
gap> IsMutable(foo);
true
```

Moreover, `MakeReadOnlyObj` says that it will only touch objects in the same region as the starting object, so if there are subobjects in multiple regions, arguably it *cannot* make the starting object immutable.

Whether one considers this correct or a design issue or whatever can be argued about; but in any case, I think this means that the issue here is rather more complicated than what is stated above :)

**Comment by ssiccha** [comment]
You're right. In the best case the suggested alternative is a hack, in the worst case it's a really bad idea. I didn't want to sell it as "this is what we definitely should do" (I rather should have put a discussion label on this issue). Also, the discussion in #3136 has convinced me that my suggestion is indeed a bad idea.
