### ISSUE TITLE
ReadByte doesn't read a byte!

### ISSUE THREAD

**Issue by mohammadfarrokhi** [gap-system/gap#3273]
The ReadByte function jumps over a byte (backspace with ASCII code 10 at location 2413) while reading a data file. The file contains 2741 bytes with the byte codes 171, 10, 173 at locations 2412, 2413, 2414.

```
gap> bytes:=[];;
gap> input:=InputTextFile("d:/error.txt");
InputTextFile(d:/error.txt)
gap> for i in [1..2741] do Add(bytes,ReadByte(input));od;
gap> CloseStream(input);
gap> bytes[2741];
fail
gap> bytes[2412];
171
gap> bytes[2413];
173

```

[error.txt](https://github.com/gap-system/gap/files/2838311/error.txt)

```
 ┌───────┐   GAP 4.10.0 of 01-Nov-2018
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: i686-pc-cygwin-default32
 Configuration:  gmp 6.0.0, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.1, Alnuth 3.1.0, AtlasRep 1.5.1, AutoDoc 2018.09.20, AutPGrp 1.10, Browse 1.8.8, CRISP 1.4.4, Cryst 4.1.18, CrystCat 1.1.8,
             CTblLib 1.2.2, FactInt 1.6.2, FGA 1.4.0, GAPDoc 1.6.2, IO 4.5.4, IRREDSOL 1.4, LAGUNA 3.9.0, Polenta 1.3.8, Polycyclic 2.14,
             PrimGrp 3.3.2, RadiRoot 2.8, ResClasses 4.7.1, SmallGrp 1.3, Sophus 1.24, SpinSym 1.5, TomLib 1.2.7, TransGrp 2.0.4, utils 0.59
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by ChrisJefferson** [comment]
So, there are two related problems here. One is a real bug we definately have to fix, one is something which we might have to provide a work-around for.

The problem here is in Windows, some programs send out `\r\n` (byte value 13 followed by byte value 10), while Unix programs expect to just see `\n` (byte value 10).

GAP (and many other programs) will auto-convert a `\r\n` into a `\n`.

Now, there is a bug in GAP. if we see (for example) `\rABC\n`, we will turn this into `\nABC`, we turn the first `\r` into a `\n`, then drop a later `\n`. We should instead (I think) just turn `\r\n` into `\n`.

However, if you need the raw byte stream, you still could have trouble, as you will see `\r\n` turned into `\n`. We could add a "I want raw access to this file" mode. You can already get this using the IO package, if you know about how to use C functions like `open` to get "binary" access to a file, but they aren't very friendly to use.
