### ISSUE TITLE
GAP terminates session when trying to calculate large coset space

### ISSUE THREAD

**Issue by DominikBernhardt** [gap-system/gap#3297]
The calculation
```G:=SymmetricGroup(14);
Sym( [ 1 .. 14 ] )
gap> H:=Group((1,2),(2,3));
Group([ (1,2), (2,3) ])
gap> RightCosets(G,H);
```
causes GAP to terminate with the message `gap: cannot extend the workspace any more!` and to delete the history of the current session.

**Comment by fingolfin** [comment]
Quoting some comments from Slack:
@ChrisJefferson wrote:
> So, the technical reason for this is that you asked for a single allocation which is bigger than the amount of memory GAP can allocate.
> (as opposed to wants to current allocated, which is where the 'permitted' comes from)
Basically, GAP's memory allocation function can't return "false" or "failed", so if a massive bag is asked for, and can't be given, our only choice is to exit GAP immediately.

@markuspf then suggested to at least improve the error message. 
> "Tried to allocate an object of size X whereas max space was Y < X, consider running GAP with -o, etc.

@fingolfin remarked
> actually, why can't we just call `ErrorQuit` when we get a huge allocation?  Of course we shouldn't do this if the heap is completely full and we could not enlarge this, as handling that error again needs an allocation, etc. But we could have a logic like this: "if OOM was triggered by a huge allocation, *and* we actually have, say, at least 16 MB heap free; THEN don't abort, instead call ErrorQuit"
> so if tiny allocations start to fail, we still abort, but not for small ones

@ChrisJefferson pointed out that this could still cause issues, e.g. when it happens in the middle of copying objects; our copying code modifies the objects being copied, and since we don't have proper exception handling, if e/g/ copying a subobject of a list fails, then we'd never clean up that list being copied, likely resulting in a crash or worse later on.
He also pointed out that it's likely that more similar problems could exist

**Comment by fingolfin** [comment]
Regarding the last point: If we had proper `try / catch / (re)throw` in GAP, then we could catch such out-of-bounds errors in the object copying code to restore them.
Or, we could do what we do in HPC-GAP (or what Julia does) and switch to non-intrusive copying, where an ObjMap keeps track of which objects already were copied. Of course that would only resolve this one spot, but I have some hope that only a finite number of places is problematic... but it's of course difficult to be sure that one has found all problematic cases... :/

**Comment by stevelinton** [comment]
@fingolfin This is an instance of a broader problem. Basically the requirements to be able to run  GAP code safely,  are *not* maintained by the kernel C code at all times. Copying is just one instance of this. This is why, for instance, entering the break loop in response to SIGINT has to be done by setting  flag saying you plan to do so and then waiting until a safe time to check it.  `ErrorQuit` can only be called when these conditions hold. A subset of these conditions must hold when memory is allocated, but that subset is not the whole set. It might be interesting to try and see whether the work we have done in HPCGAP plus features of modern C++ or progress in programming language technology could let us avoid this problem entirely.

**Comment by DominikBernhardt** [comment]
I agree with @markuspf . This message would be more helpful to the user.
