### ISSUE TITLE
Avoid AC_ namespace for custom autoconf macros

### ISSUE THREAD

**Issue by embray** [gap-system/gap#3340]
I noticed that many GAP packages ship with an `m4/ac_find_gap.m4`.  Since I couldn't find where that file is maintained I'm opening an issue here (I'm surprised it's not maintained in the gap source tree, but maybe it's in a package template or something?)

It defines a macro called `AC_FIND_GAP`.  However, per the [autoconf docs](https://www.gnu.org/software/autoconf/manual/autoconf-2.66/html_node/Macro-Names.html) the `AC_` namespace is reserved for macros included in autoconf itsef.

Historically this rule has not been followed by many packages so GAP is hardly alone in this, and I think for that reason autoconf does not prevent you from using the `AC_` namespace (as it does with some others).  Also, given that "GAP" is already in the name, it's not like this is likely to ever conflict with an actual autoconf macro.

Regardless, it might be better if instead a `GAP_` prefix were used for autoconf macros included with GAP.  It would also be nice if this macro were included in the GAP source code--that way downstream packagers could easily install it, say, to a standard location like `/usr/share/aclocal`, and GAP packages would be able to use it without having to include their own copy.  Maybe call the macro `GAP_CONFIGURE` and the filename `gap_configure.m4`.

**Comment by fingolfin** [comment]
I agree that the prefix AC_ should not be used; that it is has historical reasons.

But I don't understand the point about "installing" the macro file. Packagrs only need the file during packaging, to generate the configure script. But for end users, it is not needed (normally). Anyway, since package would not be able to rely on the M4 file to be present (and much less on its location), they'd have to include it in their git repository  anyway if they don't want tonterribly inconvenience potential contributors.

Finally, the long term plan (from my POV) would be to migrate most if not all packages away from using autotools anyway.

**Comment by embray** [comment]
I agree, the point about "installation" was mostly orthogonal.  I was thinking about it more from a system packaging perspective where GAP is "installed" as a build dependency for other GAP packages.

**Comment by fingolfin** [comment]
I worked on this earlier this year, now a majority of GAP packages switched from `AC_FIND_GAP` to `FIND_GAP`, see e.g.  https://github.com/gap-packages/ferret/blob/master/m4/find_gap.m4. The packages which have not yet switched include the following  (note that in addition, some packages may have updated this in their repository but have't made a new release since then):
- [ ] 4ti2gap
- [ ] BlissInterface
- [ ] Semigroups
- [ ] SingularInterface
- [ ] debugger
- [ ] float
- [ ] img
- [ ] linboxing
- [ ] nq

**Comment by fingolfin** [comment]
This has been resolved in all distributed packages.
