### ISSUE TITLE
GAPDoc and HPCGAP (was cleaning up pkg directory)

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#34]
The `pkg` directory is not under version control in the master branch. However, it is under version control in the hpc-gap default branch because it contains an older version of GAPDoc package by @frankluebeck with slight modification to work under HPC-GAP. 

Since in my clone of the GAP repository I have a symlink `pkg` pointing to `pkg` in my GAP installation, I've just created another clone to work with hpcgap-default branch there. 

I think it would cause less confusion if we would remove `pkg` subdirectory from the hpcgap-default branch too. I will try to summarise below the changes that I have made to GAPDoc - hopefully they may be re-applied to make a new version of GAPDoc working with both GAP and HPC-GAP.

**Comment by alex-konovalov** [comment]
This is the list of commits needed for GAPDoc to make it work in HPC-GAP:
*  Use empty string instead of empty list in Base64String for better results: 8f758be3915d85ca0c4ad0f6be7611756c45a811 
*   Make a few things immutable: eb3c9c3967776f0daa49d7aa71d8633c9c16c651
* Avoid unbinding from GAPInfo: 95cd5df92a7b127fde1feb045b1e74dd63387880
* Introduced HELP_REGION: e3650be3038b512b1545aadfb7cd3310dccb5cb4
* MakeImmutable( GAPInfo.TermEncoding ): 6ac822a5bd597ffabc4e07bf7dbe26f3e3b3daaa
* MakeImmutable(UNICODE_RECODE): 6ac822a5bd597ffabc4e07bf7dbe26f3e3b3daaa
* Fixed issues with character encodings in concurrent threads: 2eb0d37434a70bbde94eb90e60646c67ae52b0b5
* Fixed building manuals: dfd2998ff524e7534117d4577fda96ffeac2b5f9
* BOXCHARS made immutable: a8eb9bdd3c321c571bd48128feed59e27853d45e 

Since all HPC-GAP constructs used in these commits are now treated in the master branch as no-ops, there should be no problem to make a new version of GAPDoc which will work both in GAP 4.8 and HPC-GAP.

**Comment by fingolfin** [comment]
I started some work on that, see https://github.com/frankluebeck/GAPDoc/pull/18

**Comment by fingolfin** [comment]
Frank merged (most) of my PR to GAPDoc. I made PR #1532 to get our copy of GAPDoc closer to Frank's repository. This makes it easier to see which changes remain. I will track the status of the various commits Alex' listed below, checking all which are either added to upstream GAPDoc, or (as far as I can tell) redundant. Note that I have some questions on the remaining ones.

- [ ] Use empty string instead of empty list in Base64String for better results: 8f758be3915d85ca0c4ad0f6be7611756c45a811 
- [ ] Make a few things immutable: eb3c9c3967776f0daa49d7aa71d8633c9c16c651
- [ ] Avoid unbinding from GAPInfo: 95cd5df92a7b127fde1feb045b1e74dd63387880
- [ ] Introduced HELP_REGION: e3650be3038b512b1545aadfb7cd3310dccb5cb4
- [ ] MakeImmutable( GAPInfo.TermEncoding ): 6ac822a5bd597ffabc4e07bf7dbe26f3e3b3daaa
- [ ] MakeImmutable(UNICODE_RECODE): 6ac822a5bd597ffabc4e07bf7dbe26f3e3b3daaa
- [ ] Fixed issues with character encodings in concurrent threads: 2eb0d37434a70bbde94eb90e60646c67ae52b0b5
- [ ] Fixed building manuals: dfd2998ff524e7534117d4577fda96ffeac2b5f9
- [ ] BOXCHARS made immutable: a8eb9bdd3c321c571bd48128feed59e27853d45e

**Comment by fingolfin** [comment]
@stevelinton @alex-konovalov  Things which are unclear to me:
* What is the motivation for 95cd5df (Avoid unbinding from GAPInfo) ? OK, so GAPInfo is an atomic record, and so unbinding from it at lot is not nice. But is this an actual problem?
* Regarding 2eb0d37434a70bbde94eb90e60646c67ae52b0b5 ("Fixed issues with character encodings in concurrent threads"): So first `nam` is made immutable, so that it can be accessed from all threads. But then `UNICODE_RECODE` is made thread local. Naively, I would have expected this to take care of copying `nam` into the thread local region, too. But I guess (but haven't tried) this isn't the case, probably because the reference to `nam` is inside a function object, and the code copying the `UNICODE_RECODE` record does not "see" it that way... Is that correct?
I would have just tested this via experiment, but it is actually not clear to me what you guys did to trigger the problem fixed by that commit.

**Comment by fingolfin** [comment]
Also, I wonder if we can't simplify a little bit on the HELP_REGION aspect: What do you think about 550989b92ccc1465ac27c898e9e5e07d5230c33a in PR #1532? OK, now that I think about it, perhaps we also need to adjust `GAPDocTextTheme.(f) := res.(f);` to use `LockAndMigrateObj`, and perhaps also `StructuralCopy` and/or `Immutable`... Indeed, we can probably make those theme object immutable, can't we?

**Comment by alex-konovalov** [comment]
@frankluebeck @fingolfin Just to check, is this staying in GAP 4.9.0 or there may be new GAPDoc release that will work in both modes?

**Comment by alex-konovalov** [comment]
#1865 is a step in this direction. It imported the latest snapshot of GAPDoc at the time of submitting that PR (commit c24e382597cf2) from https://github.com/frankluebeck/GAPDoc
