### ISSUE TITLE
Problem with Travis testing

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#3456]
This is triggered by an issue I had with PR #3451

The test "Compiler: clang C
TEST_SUITES="docomp testinstall""

fails
(https://travis-ci.org/gap-system/gap/jobs/533338574)

    IsomorphismFpGroup(h);
# Expected output:
[ (2,3)(6,7)(11,13)(12,14), (3,4)(7,8)(10,11)(14,15), 
  (4,5)(8,9)(11,12)(13,14), (1,5)(6,12)(7,14)(8,15), (2,6)(3,7)(4,8)(5,9) 
 ] -> [ S_6.1, S_6.2, S_6.3, S_6.4, S_6.5 ]
# But found:
[ (1,6,10,13,15,5)(2,7,11,14,4,9)(3,8,12), (2,6)(3,7)(4,8)(5,9) ] -> 
[ S_6.3^-1*S_6.2^-1*S_6.1^-1*S_6.4^-1*S_6.5^-1, S_6.5^-1 ]

 an inconsistency, but the test

"C
TEST_SUITES="docomp testtravis""

which runs the same test file does not cause a problem.

What could cause this discrepancy? The changes are only in the library and should not be affected by packages.

[I will change the test file to ignore the issue]

**Comment by fingolfin** [comment]
That usually has nothing to do with Travis, but rather indicates that a test depends on global effects -- `testtravis` runs more tests than `testinstall`. Hence if one of the additional tests (which may be run before the problematic test is reached) does something that affects the output of the problematic test, well, you get a difference. E.g. some of the homomorphism code uses global caches, doesn't it? Those will have different content. Also, the random number generator may be in a different state if the `.tst` file does not use `START_TEST` (which resets the RNG seed), but of course `grpperm.tst` does have `START_TEST`, so that's not it.
