### ISSUE TITLE
Strange 'Unbound global variable' error in utils/tst/groups.tst

### ISSUE THREAD

**Issue by cdwensley** [gap-system/gap#3555]
### Observed behaviour
ChristoleysiMac:utils christopherwensley$ ../../dev.sh 
 ┌───────┐   GAP 4.10dev-2158-g507da64 of today
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin17.4.0-default64-kv7
 Configuration:  gmp 6.0.0, GASMAN
 Loading the library and packages ...
Syntax warning: Unbound global variable in /Applications/gap/gapdev/pkg/transg\
rp/lib/trans.grp:240
	  TRANSAVAILABLE[tradeg]:=true;
	  ^^^^^^^^^^^^^^
Syntax warning: Unbound global variable in /Applications/gap/gapdev/pkg/atlasr\
ep/gap/utils.gi:44
        pos:= POSITION_FIRST_COMPONENT_SORTED( WidthUnicodeTable, ints[j] );
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 Packages:   AClib 1.3, Alnuth 3.1.0, AtlasRep 1.5.1, AutoDoc 2019.05.20, 
             AutPGrp 1.9, CRISP 1.4.4, Cryst 4.1.17, CrystCat 1.1.8, 
             CTblLib 1.2.2, FactInt 1.6.2, FGA 1.4.0, GAPDoc 1.6.2.dev, 
             IRREDSOL 1.4, LAGUNA 3.9.0, Polenta 1.3.8, Polycyclic 2.14, 
             PrimGrp 3.3.1, RadiRoot 2.8, ResClasses 4.7.1, SmallGrp 1.3, 
             Sophus 1.24, SpinSym 1.5, TomLib 1.2.6, TransGrp 2.0.2, 
             utils 0.64
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> dir := DirectoriesPackageLibrary( "utils", "tst" );;
gap> file := Filename( dir, "groups.tst" );; 
gap> opts := rec( compareFunction := "uptowhitespace" );; 
gap> Test( file, opts );
########> Diff in /Applications/gap/my-dev/pkg/utils/tst/groups.tst:133
# Input is:
for i in [1..len] do
       imi := images[i]; 
       im2 := image2[i]; 
       if not ForAll( imi, im -> ( im in im2 ) ) then  
           ok := false; 
       fi; 
   od;
# Expected output:
# But found:
Syntax warning: Unbound global variable in stream:4
       if not ForAll( imi, im -> ( im in im2 ) ) then  
                                         ^^^
########
false
gap> Test( file, opts );
true                                

### Expected behaviour
Do not understand why im2 is claimed to be unbound. 
This does not happen in 4.10.2. 
I can fix it by adding  imi:=[];; im2:=[];;  before the for loop, so this is no longer a Utils problem, but it does appear to me to be a problem in gapdev.

**Comment by ChrisJefferson** [comment]
The first problem (when loading GAP) is caused (I think) by your packages being out of date.

**Comment by ChrisJefferson** [comment]
The second problem actually seems to happen for me also in 4.10, I haven't carefully figured out why/when.

The reason is that GAP generates 'unbound global variable' warnings when it reads code, so it reads the whole for loop, notices 'im2' is used without being defined and warns, and only then executes the loop.

There isn't a perfect fix for this problem, we have a fairly big heuristic to try to figure out when to warn about this kind of thing.

**Comment by cdwensley** [comment]
Thanks for your prompt comments. 
I'm not sure why you think Utils is "out of date".  
As for the "notices 'im2' is used without being defined" - 'im2' has been defined, but only inside the for loop.  'imi' has been defined & used in the same way, but is not complained about. 
However, if this is just one case of a known general problem, perhaps the issue should be closed?

**Comment by ChrisJefferson** [comment]
It's not utils that is out of date, it's transgrp and atlasrep.

The warning is because of how im2 is used inside a lambda function, which counts as a function.

The full reasoning is the following (I wouldn't put this in docs, just so you know what's going on). I don't know why it's changed from 4.10 however:

1) GAP sees the start of a 'for' loop. GAP switches from "immediate execution" to "build an AST".
2) GAP reads it's way through the loop, building the AST.
3) GAP sees `im -> `, GAP switches to 'parse a function', while we parse functions, we warn about undefined variables.
4) GAP sees 'im2', and warn about it.
5) Finally, the for loop is parsed. Now execute it, and while doing that see 'im' and 'im2' defined for the first time.

**Comment by cdwensley** [comment]
Thanks - that's very helpful.  I'll close the issue.
