### ISSUE TITLE
Error when calling MaximalSubgroupClassReps for a group of units

### ISSUE THREAD

**Issue by EricSwartz** [gap-system/gap#3599]
When trying to calculate the maximal subgroups of the unit group of a group ring, I encountered the following error.  (The error also shows up when calling MaximalSubgroups.)

### Observed behaviour  
```
gap> R:= GroupRing(GF(2), SymmetricGroup(3));
<algebra-with-one over GF(2), with 2 generators>
gap> UR:= Units(R);
<group with 3 generators>
gap> max:= MaximalSubgroupClassReps(UR);
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 2nd choice method found for `IsNormalizedUnitGroupOfGroupRing' on 1 \
arguments at /home/eswartz/gap-4.10.1/lib/methsel2.g:250 called from
IsNormalizedUnitGroupOfGroupRing( U 
 ) at /home/eswartz/gap-4.10.1/pkg/laguna-3.9.2/lib/laguna.gi:1342 called from
Random( der[i] ) at /home/eswartz/gap-4.10.1/lib/grp.gi:887 called from
CompositionSeries( grp ) at /home/eswartz/gap-4.10.1/lib/pcgscomp.gi:113 called from
Pcgs( group ) at /home/eswartz/gap-4.10.1/lib/pcgsspec.gi:689 called from
SpecialPcgs( G ) at /home/eswartz/gap-4.10.1/lib/grppcatr.gi:373 called from
...  at *stdin*:3
type 'quit;' to quit to outer loop
brk> 
```

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.10.1 of 23-Feb-2019
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv3
 Configuration:  gmp 6.1.2
 Loading the library and packages ...
 Packages:   AClib 1.3.1, Alnuth 3.1.0, AtlasRep 1.5.1, AutoDoc 2019.02.22, 
             AutPGrp 1.10, CRISP 1.4.4, Cryst 4.1.18, CrystCat 1.1.8, 
             CTblLib 1.2.2, FactInt 1.6.2, FGA 1.4.0, GAPDoc 1.6.2, IO 4.5.4, 
             IRREDSOL 1.4, LAGUNA 3.9.2, Polenta 1.3.8, Polycyclic 2.14, 
             PrimGrp 3.3.2, RadiRoot 2.8, ResClasses 4.7.1, SmallGrp 1.3, 
             Sophus 1.24, SpinSym 1.5, TomLib 1.2.7, TransGrp 2.0.4, 
             utils 0.61
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by stevelinton** [comment]
Assigning to @alex-konovalov  because this looks like a problem in Laguna, or at the very least a problem involving laguna.

**Comment by alex-konovalov** [comment]
Thanks for the report - I will look. A workaround is to start GAP without LAGUNA loaded (e.g. using `-A` option, or use settings mechanism to disable a particular package), then it works:
```
gap> R:= GroupRing(GF(2), SymmetricGroup(3));
<algebra-with-one over GF(2), with 2 generators>
gap> UR:= Units(R);
<group with 3 generators>
gap> max:= MaximalSubgroupClassReps(UR);
[ <group of size 6 with 2 generators>, <group of size 6 with 2 generators>, <group of size 6 with 2 generators>,
  <group of size 4 with 2 generators> ]
gap> 
```

**Comment by EricSwartz** [comment]
Thank you!  As a workaround, we actually converted the units group to a permutation group, did the calculations, and then inverted the isomorphism to send it back.  However, we wanted to make the bug known!

**Comment by wilfwilson** [comment]
Is it possible/appropriate to move this issue to <https://github.com/gap-packages/laguna/issues>?

**Comment by fingolfin** [comment]
There are a bunch of issues in the LAGUNA code related to this error:
* the "properties" `IsUnitGroupOfGroupRing` and `IsNormalizedUnitGroupOfGroupRing` have no methods installed,, which is the immediate cause of this problem
* arguably, they shouldn't be properties in the first place, though, but rather categories, as they are not something that an arbitrary group could satisfy, but rather depend on how the groups were constructed / how their elements "look like"
* LAGUNA does this: `DeclareProperty("IsNormalizedUnitGroupOfGroupRing", IsGroupOfUnitsOfMagmaRing);`; but when one looks at the objects LAGUNA constructs, it turns out that if `IsNormalizedUnitGroupOfGroupRing` is set to true, then `IsGroupOfUnitsOfMagmaRing` is set to `false`. Something is not right here.
* in the break loop in the error message, the break is inside a method for `Random`; changing the properties above to categories would go beyond that error, but would immediately run into another error a few lines later, due to this in the code: `elif IsUnitGroupOfGroupRing then` (note the missing argument)

**Comment by alex-konovalov** [comment]
Glad @EricSwartz that you have found a workaround. 

@wilfwilson issues can be only transferred within an organisation. I have cross-posted this at https://github.com/gap-packages/laguna/issues/16 instead.

@fingolfin thanks for the analysis. I will release a fix.

**Comment by alex-konovalov** [comment]
Fix merged in https://github.com/gap-packages/laguna/issues/16 - thanks @fingolfin. I will publish new LAGUNA release shortly.
