### ISSUE TITLE
LogTo() command overwrites existing log file without warning

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#362]
Is there any reason for this behaviour? Probably one could use `IsExistingFile` and trigger an error if such file exists.

I assume that one the reasons to silently overwrite it is that it's very convenient for automated scenarios when you may repeatedly call LogTo("somelogfile"); and do not want to have an error.

OTOH, in this case probably `LogTo` is not the best way to save the results and one should rather be using `PrintTo` and `AppendTo`. So would it be a good idea to change the `LogTo` behaviour?

**Comment by fingolfin** [comment]
I think this is reasonable behavior, and exactly what I'd expect. Moreover, I dislike changing existing behavior like this in a way that is likely to break people's scripts, 

Anyway, you haven't really explained why you think this behavior should be changed? In which situations do you consider the current behaviour to be problematic, and for whom?

**Comment by stevelinton** [comment]
We could make this an user-settable option -- to do nothing, warn or give an error when LogTo would overwrite a file.

**Comment by alex-konovalov** [comment]
@fingolfin: I had a question from a new user - I think it would be good to have a public issue where this is explained, since this may be a regular question.

**Comment by frankluebeck** [comment]
I don't see a need for action here. `LogTo` just works as documented and as it always worked since GAP 2 times. In my opinion overwriting the given file is the expected behaviour (and the behaviour is like that of `PrintTo`). If someone wants to save parts of several GAP sessions, then `LogTo` should be called with different names (or the files from previous calls must be renamed).

Appending logs from different sessions doesn't seem to make much sense because you don't see where a log from a different session starts.

**Comment by alex-konovalov** [comment]
Ok, thanks - then I will closes this. And just in case, this behaviour of `LogTo` is documented.
