### ISSUE TITLE
Suspicious code in MaximalAbelianQuotient

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#3634]
The following arose while investigating another problem. I'm not sure what's going on, and I'm not sure if there is a bug.

In `MaximalAbelianQuotient`, at `ghomfp.gi:1061`, line 1096 (at present) is:

`SetAbelianInvariants(f,DiagonalOfMat(s.normal));`

This has two problems.

1) the AbelianInvariants are supposed to be power of primes -- this can return lists like `[6,6]`

2) This line never does anything anyway, and neither does 1092 just above it (`SetAbelianInvariants(f,img)`), as we always set the abelian invariants on line `1083`, so these calls are ignored.

So, this dodgy line is always ignored, but I don't understand the code well enough to see if this should be getting set somewhere else, and should it be working that 1092 is also ignored?

@hulpke added these lines. I wonder if he didn't notice 1083 means they don't do anything, and also 1096 has to look like 1083 and call `AbelianInvariantsOfList` (guessing wildly)?

**Comment by hulpke** [comment]
Thanks for spotting. Even if the commit is recently (because I just worked on the code) the line has been there for a long time (and probably never threw an error, as it actually was ignored). My guess is that I added them when implementing the abelian quotient, thinking locally to remember the structure in the pre-image.
You are right on both points: The lines should go (which I'll do, as I'm anyhow working on the code) as being redundant, but if they were they would have to use `AbelianInvariantsOfList`.
