### ISSUE TITLE
Inverses of free group automorphisms are not always on standard generators

### ISSUE THREAD

**Issue by ignatsoroko** [gap-system/gap#3675]
If we define two commuting automorphisms of a free group and use Comm() to form their commutator, then the printed description of the result is not simplified sometimes. Moreover, if we write explicitly the commutator letter by letter, it is sometimes simplified, but at other times not, in a different way than if we just use Comm():

### Observed behaviour
gap> F:=FreeGroup("x","y","z");
<free group on the generators [ x, y, z ]>
gap> AssignGeneratorVariables(F);
#I  Assigned the global variables [ x, y, z ]
gap> B:=GroupHomomorphismByImages(F,F,[x,y,z],[y\*x^-1\*y,y,z]);
[ x, y, z ] -> [ y\*x^-1\*y, y, z ]
gap> D:=GroupHomomorphismByImages(F,F,[x,y,z],[x,y,y\*z^-1\*y]);
[ x, y, z ] -> [ x, y, y\*z^-1\*y ]
gap> K:=Comm(B,D);
__[ y\*x^-1\*y, y, y\*z^-1\*y ] -> [ y\*x^-1\*y, y, y\*z^-1\*y ]__
gap> B\*D\*B^-1\*D^-1;
[ x, y, z ] -> [ x, y, z ]
gap> B^-1\*D^-1\*B\*D;
__[ y\*x^-1\*y, y, z ] -> [ y\*x^-1\*y, y, z ]__

### Expected behaviour
gap> K:=Comm(B,D);
[ x, y, z ] -> [ x, y, z ]
gap> B^-1\*D^-1\*B\*D;
[ x, y, z ] -> [ x, y, z ]

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.10.0 of 01-Nov-2018
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-unknown-cygwin-default64
 Configuration:  gmp 6.1.0, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.1, Alnuth 3.1.0, AtlasRep 1.5.1, AutoDoc 2018.09.20, AutPGrp 1.10, Browse 1.8.8, CRISP 1.4.4,
             Cryst 4.1.18, CrystCat 1.1.8, CTblLib 1.2.2, FactInt 1.6.2, FGA 1.4.0, GAPDoc 1.6.2, IO 4.5.4,
             IRREDSOL 1.4, LAGUNA 3.9.0, Polenta 1.3.8, Polycyclic 2.14, PrimGrp 3.3.2, RadiRoot 2.8,
             ResClasses 4.7.1, SmallGrp 1.3, Sophus 1.24, SpinSym 1.5, TomLib 1.2.7, TransGrp 2.0.4, utils 0.59
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by hulpke** [comment]
Actually, `K` is simplified. What you would like is that homomorphisms on `F` are always given on the standard generators. This currently doesn't happen because it requires a calculation, while swapping generators/images comes at minimal cost. This is advantageous if not much is done with the homomorphism and does not block other calculations.
You could install your own method for inverting automorphisms of free groups that ensures the inverse is given on the standard generators all time. Alternatively you could write your own `View` method for such homomorphisms to always list standard generators and their images.

The reason for the different behavior of `B*D*B^-1*D^-1;` versus  `B^-1*D^-1*B*D;` is that the product traces through generators. If the product starts with `B` it is the generators on which `B` is given, if it starts with `B^-1` it is the generators on which `B^-1` is given.

**Comment by fingolfin** [comment]
I would say there is no issue here, is there? @ignatsoroko may have had some expectations, but those expectations simply were not well founded. And it's still trivial to extract the images of the "standard" generators, if one wants them, by mapping them through the homomorphism.

So I am tempted to close this as "invalid wontfix" or so...?

**Comment by hulpke** [comment]
@fingolfin I'm happy with closing. Its something that we don't plan to change, though I understand that in some situations a different default could be desireable.
