### ISSUE TITLE
Suspicious code in InversePcgs

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#3676]
Consider the following code:

```
gap> SetInfoLevel(InfoAttributes, 10);
gap> G := SymmetricGroup(10);;
gap> xset := Group( [ (2,5)(3,4), (2,3)(4,7), (2,4)(3,8) ] )^G;;
gap> Normalizer( ActingDomain( xset ), Representative( xset ) );
```

It outputs:
```
#I  Attribute KernelOfMultiplicativeGeneralMapping of GroupHomomorphismByImages( Group( [ (1,4)(2,5)(3,6), (1,2,5,3,6), (1,6,2,4,3) ] ), Group( [ f1 ] ), [ (1,4)(2,5)(3,6), (1,2,5,3,6), (1,6,2,4,3) ], 
[ f1, <identity> of ..., <identity> of ... ] ) already set to Group( [ (1,2,5,3,6), (1,6,2,4,3) ] ), cannot be changed to Group( () )
```

This warning is coming from [`ghompcgs.gi:360`](https://github.com/gap-system/gap/blob/master/lib/ghompcgs.gi#L360-L361), which is trying to set the `KernelOfMultiplicateGeneralMapping` of the input to `Group(())`. As the map already has a kernel, that assign is ignored.

I haven't dived into this yet, but this feels likely to be a bug of some kind -- one of these kernels is right?

I put the full backtrack here, in case it helps someone who understands this quickly see the problem:

```
gap> WhereWithVars(100);
SetKernelOfMultiplicativeGeneralMapping( hom, SubgroupNC( Source( hom ), gensKer ) ); at /home/caj/files/reps/gap/gap/lib/ghompcgs.gi:361
  arguments:
    hom := GroupHomomorphismByImages( Group( [ (1,4)(2,5)(3,6), (2,3,5,6,4), (1,3,4,2,6) ] ), Group( [ f1 ] ), [ (1,4)(2,5)(3,6), (2,3,5,6,4), (1,3,4,2,6) ], 
      [ f1, <identity> of ..., <identity> of ... ] )
  local variables:
    pcgs := Pcgs([ f1 ])
    new := <unassigned>
    idR := <identity> of ...
    idD := ()
    gensInv := [ f1 ]
    imgsInv := [ (3,6,4,5) ]
    gensKer := [  ]
    gens := Pcgs([ (3,6,4,5) ])
    imgs := [ f1 ]
    i := 1
    u := f1
    v := (3,6,4,5)
    uw := 1
    tmp := 1
    vw := <unassigned>
    j := <unassigned>
 called from
InversePcgs( hom ); at /home/caj/files/reps/gap/gap/lib/ghompcgs.gi:502
  arguments:
    hom := GroupHomomorphismByImages( Group( [ (1,4)(2,5)(3,6), (2,3,5,6,4), (1,3,4,2,6) ] ), Group( [ f1 ] ), [ (1,4)(2,5)(3,6), (2,3,5,6,4), (1,3,4,2,6) ], 
      [ f1, <identity> of ..., <identity> of ... ] )
    elm := <identity> of ...
  local variables:
    pcgsR := <unassigned>
    exp := <unassigned>
    imgs := <unassigned>
    pre := <unassigned>
    i := <unassigned>
 called from
PreImagesRepresentative( com!.map2, elm ) at /home/caj/files/reps/gap/gap/lib/mapprep.gi:351
  arguments:
    com := CompositionMapping( GroupHomomorphismByImages( Group( [ (1,4)(2,5)(3,6), (2,3,5,6,4), (1,3,4,2,6) ] ), Group( [ f1 ] ), [ (1,4)(2,5)(3,6), (2,3,5,6,4), (1,3,4,2,6) 
       ], [ f1, <identity> of ..., <identity> of ... ] ), MappingByFunction( Group( [ ConjugatorAutomorphism( Group( [ (2,3,5,6,4), (1,3,4,2,6) ] ), (1,4)(2,5)(3,6) ), 
        InnerAutomorphism( Group( [ (2,3,5,6,4), (1,3,4,2,6) ] ), (2,3,5,6,4) ), InnerAutomorphism( Group( [ (2,3,5,6,4), (1,3,4,2,6) ] ), (1,3,4,2,6) ) ] ), Group( 
      [ (1,4)(2,5)(3,6), (2,3,5,6,4), (1,3,4,2,6) ] ), function ( auto )
          if not IsConjugatorAutomorphism( auto ) then
              return fail;
          fi;
          img := ConjugatorOfConjugatorIsomorphism( auto );
          if not img in ran then
              if not img in r then
                  r := ClosureGroup( r, img );
                  cen := Centralizer( r, g );
              fi;
              img := First( List( Enumerator( cen ), function ( i )
                        return i * img;
                    end ), function ( i )
                      return i in ran;
                  end );
          fi;
          return img;
      end, function ( elm )
          return ConjugatorAutomorphismNC( g, elm );
      end ) )
    elm := <identity> of ...
  local variables:
    im := <unassigned>
    rep := <unassigned>
 called from
PreImagesRepresentative( opg, x ) at /home/caj/files/reps/gap/gap/lib/gpprmsya.gi:1282
  arguments:
    x := <identity> of ...
  local variables: <none>
 called from
func( C[i] ) at /home/caj/files/reps/gap/gap/lib/coll.gi:665
  arguments:
    arg := [ [ <identity> of ..., f1 ], function ( x )
              return PreImagesRepresentative( opg, x );
          end ]
  local variables:
    tnum := 41
    C := [ <identity> of ..., f1 ]
    func := function ( x )
          return PreImagesRepresentative( opg, x );
      end
    res := [ , 1 ]
    i := 1
    elm := <unassigned>
    l := 2
 called from
List( AsSSortedList( Image( opg ) ), function ( x )
      return PreImagesRepresentative( opg, x );
  end ) at /home/caj/files/reps/gap/gap/lib/gpprmsya.gi:1282
  arguments:
    s := SymmetricGroup( [ 1 .. 6 ] )
    u := Group( [ (1,2)(3,4), (1,3)(4,6), (1,4)(3,5) ] )
  local variables:
    dom := [ 1, 2, 3, 4, 5, 6 ]
    issym := true
    o := [ [ 1, 2, 3, 4, 5, 6 ] ]
    b := Group( [ (2,3,5,6,4), (1,3,4,2,6) ] )
    beta := 360
    alpha := <unassigned>
    emb := <unassigned>
    nb := <unassigned>
    na := <unassigned>
    w := Group( [ ConjugatorAutomorphism( Group( [ (2,3,5,6,4), (1,3,4,2,6) ] ), (1,4)(2,5)(3,6) ), InnerAutomorphism( Group( [ (2,3,5,6,4), (1,3,4,2,6) ] ), (2,3,5,6,4) ), 
        InnerAutomorphism( Group( [ (2,3,5,6,4), (1,3,4,2,6) ] ), (1,3,4,2,6) ) ] )
    perm := <unassigned>
    pg := <unassigned>
    l := <unassigned>
    is := <unassigned>
    ie := <unassigned>
    ll := <unassigned>
    syll := <unassigned>
    act := <unassigned>
    typ := <unassigned>
    sel := <unassigned>
    bas := <unassigned>
    wdom := <unassigned>
    comp := <unassigned>
    lperm := <unassigned>
    other := <unassigned>
    away := <unassigned>
    i := <unassigned>
    j := <unassigned>
    b0 := <unassigned>
    opg := CompositionMapping( GroupHomomorphismByImages( Group( [ (1,4)(2,5)(3,6), (2,3,5,6,4), (1,3,4,2,6) ] ), Group( [ f1 ] ), [ (1,4)(2,5)(3,6), (2,3,5,6,4), (1,3,4,2,6) 
       ], [ f1, <identity> of ..., <identity> of ... ] ), MappingByFunction( Group( [ ConjugatorAutomorphism( Group( [ (2,3,5,6,4), (1,3,4,2,6) ] ), (1,4)(2,5)(3,6) ), 
        InnerAutomorphism( Group( [ (2,3,5,6,4), (1,3,4,2,6) ] ), (2,3,5,6,4) ), InnerAutomorphism( Group( [ (2,3,5,6,4), (1,3,4,2,6) ] ), (1,3,4,2,6) ) ] ), Group( 
      [ (1,4)(2,5)(3,6), (2,3,5,6,4), (1,3,4,2,6) ] ), function ( auto )
          if not IsConjugatorAutomorphism( auto ) then
              return fail;
          fi;
          img := ConjugatorOfConjugatorIsomorphism( auto );
          if not img in ran then
              if not img in r then
                  r := ClosureGroup( r, img );
                  cen := Centralizer( r, g );
              fi;
              img := First( List( Enumerator( cen ), function ( i )
                        return i * img;
                    end ), function ( i )
                      return i in ran;
                  end );
          fi;
          return img;
      end, function ( elm )
          return ConjugatorAutomorphismNC( g, elm );
      end ) )
    bp := <unassigned>
 called from
NormalizerParentSA( syll, act[sel[1]] ) at /home/caj/files/reps/gap/gap/lib/gpprmsya.gi:1363
  arguments:
    s := SymmetricGroup( [ 1 .. 10 ] )
    u := Group( [ (2,5)(3,4), (2,3)(4,7), (2,4)(3,8) ] )
  local variables:
    dom := [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    issym := true
    o := [ [ 1 ], [ 6 ], [ 9 ], [ 10 ], [ 2, 5, 3, 4, 8, 7 ] ]
    b := <unassigned>
    beta := <unassigned>
    alpha := <unassigned>
    emb := <unassigned>
    nb := <unassigned>
    na := <unassigned>
    w := Group( [ (1,2,3,4), (1,2) ] )
    perm := ( 2, 6)( 3, 9)( 4,10)
    pg := [ ( 1, 6, 9,10), (1,6) ]
    l := 5
    is := 5
    ie := 6
    ll := 6
    syll := SymmetricGroup( [ 1 .. 6 ] )
    act := [ ,,,, Group( [ (1,2)(3,4), (1,3)(4,6), (1,4)(3,5) ] ) ]
    typ := [ ,,,, 12 ]
    sel := [ 5 ]
    bas := Group( () )
    wdom := <unassigned>
    comp := <unassigned>
    lperm := <unassigned>
    other := <unassigned>
    away := <unassigned>
    i := 12
    j := <unassigned>
    b0 := <unassigned>
    opg := <unassigned>
    bp := <unassigned>
 called from
NormalizerParentSA( G, U ) at /home/caj/files/reps/gap/gap/lib/gpprmsya.gi:1422
  arguments:
    G := SymmetricGroup( [ 1 .. 10 ] )
    U := Group( [ (2,5)(3,4), (2,3)(4,7), (2,4)(3,8) ] )
  local variables:
    P := <unassigned>
 called from
oper( super, sub ) at /home/caj/files/reps/gap/gap/lib/domain.gd:452
  arguments:
    super := SymmetricGroup( [ 1 .. 10 ] )
    sub := Group( [ (2,5)(3,4), (2,3)(4,7), (2,4)(3,8) ] )
  local variables:
    value := <unassigned>
 called from
<function "Normalizer try to exploit the in-parent attribute NormalizerInParent">( <arguments> )
 called from read-eval loop at *errin*:4
```

**Comment by fingolfin** [comment]
This issues goes back to at least GAP 4.4. Some observations:

`InversePcgs` was added in 1996-11-22. Nobody else made any serious modifications to it since then. I believe I understand the code well enough to debug it, I'll try to do that, tomorrow, after some sleep, or better next week, after our grant proposal deadline is past ;-)

A major chunk of the code `InversePcgs` duplicate code from the `KernelOfMultiplicativeGeneralMapping` method in the same file, around line 390; but there are two minor difference. One is the use of `Pcgs( Range( hom ) );` vs. `Pcgs( Image( hom ) );`. The other is that where `InversePcgs` has `ReducedPcElement( v, gensKer[ vw ] );`, the `KernelOfMultiplicativeGeneralMapping` method has `v  := ReducedPcElement( v, gensKer[ vw ] );`. But there is not two argument method for ReducedPcElement (!!). Meaning that this code line apparently never ever has been executed in the past couple of years?!? 

Anyway, those differences are ideally analyzed and fixed; tests added that trigger the offending lines; and then the code duplication removed, probably by adding a new helper to be called from both places. 


Back to the actual problem: it seems that `hom!.sourcePcgs` simply is wrong, which ultimately causes the incorrect kernel computation:
```
brk> Source(hom);
Group([ (1,4)(2,5)(3,6), (2,3,5,6,4), (1,3,4,2,6) ])
brk> hom!.sourcePcgs;
Pcgs([ (3,6,4,5) ])
```

So I reduced the example further:
```
gap> SetInfoLevel(InfoAttributes, 10);
gap> G:=Group([ (1,4)(2,5)(3,6), (2,3,5,6,4), (1,3,4,2,6) ]);;
gap> N:=Subgroup(G, [ (2,3,5,6,4), (1,3,4,2,6) ]);;
gap> phi:=NaturalHomomorphismByNormalSubgroup(G, N);;
gap> PreImagesRepresentative(phi, Range(phi).1);
#I  Attribute KernelOfMultiplicativeGeneralMapping ...
gap> StructureDescription(G);
"S5"
gap> phi!.sourcePcgs;   # G is not solvable, so there shouldn't be a sourcePcgs!
Pcgs([ (3,6,4,5) ])
gap> StructureDescription(N);
"A5"
```

The pcgs comes from this code:
https://github.com/gap-system/gap/blob/72494b239b7cab7f7492a58e2be423a536720504/lib/factgrp.gi#L1683-L1685

Now, `TryPcgsPermGroup` sadly is completely undocumented. My guess is that it is supposed to combine a solvability test with computing an pcgs, and is supposed to return false here. Hm, and since it gets `[G, N]` are argument, perhaps it is meant to compute a pcgs for G/N?

After all, we already established that the pcgs can't be one for G, nor for N (both are non-solvable). But can it be one for G/N, which has order 2? From the print out, it seem as if that pcgs defines a cyclic group of order 4. Hum? Actually... it is a "modulo pcgs", so perhaps it's really defining a group of order 2? Let's try
```
gap> IsModuloPcgs(pcgs);
true
gap> Order(Group(pcgs));
4
gap> NumeratorOfModuloPcgs(pcgs);
Pcgs([ (3,6,4,5) ])
gap> DenominatorOfModuloPcgs(pcgs);
fail
```
Hm, based on that it really seems to define C_4 not C_2.... although, let's see how the code `factgrp.gi` continues... Aha, by calling `CreateIsomorphicPcGroup`. Let's reproduce that:
```
gap> A:=CreateIsomorphicPcGroup(pcgs,false,false);
Group([ f1 ])
gap> Size(A);
2
```
What ???? OK, I *really* don't understand what `TryPcgsPermGroup` is doing, but it looks more and more as if at least here, it maybe is computing something like a pcgs for the image resp. something isomorphic to G/N?

In any case, even without understanding all of this, there is a strong hint here that these lines in the same `NaturalHomomorphismByNormalSubgroupOp` method later on are simply wrong:
https://github.com/gap-system/gap/blob/72494b239b7cab7f7492a58e2be423a536720504/lib/factgrp.gi#L1705-L1706

But we can't remove that, because we also set the filter to `IsGroupGeneralMappingByPcgs`, and that seems to require that a `sourcePcgs` is set. If we also drop that, then `ImagesRepresentative` later on runs into an infinite loop.

Something is really wrong here, but I do not yet understand all the pieces sufficiently.

Perhaps @hulpke knows more?

**Comment by fingolfin** [comment]
OK, so `ModuloPcgs` also calls `TryPcgsPermGroup` like that, and *that* is explicitly documented to allow for a non-solvable denominator. So after looking at the code for the primary ModuloPcgs method, I added this code to the problematic `NaturalHomomorphismByNormalSubgroupOp` method discussed above:
```gap
  # set numerator and denominator appropriately
  SetNumeratorOfModuloPcgs(pcgs,GeneratorsOfGroup(G));
  SetDenominatorOfModuloPcgs(pcgs,GeneratorsOfGroup(N));
```

But that didn't help either (not that I expected it to).

Digging a bit deeper, `IsModuloPcgs` does not imply `IsPcgs`, it's the other way around (which makes a lot of sense). Now, the above pcgs, while clearly only a "modulo pcgs", is actually in the filter `IsPcgs`, because `PcgsStabChainSeries` always sets that. So that's already one thing which is strictly speaking wrong. One can remove the `IsPcgs` from `PcgsStabChainSeries`, but then other things start to break because they need `IsPcgs` (and so far in all cases, rightfully so). No time to look more right now, though.

**Comment by hulpke** [comment]
The code for `inversePcgs` is old and predates the introduction of modulo pcgs for solvable factors of permutation groups. When the latter were introduced, they were set up to re-use some of the machinery for pc group homomorphisms, not noticing that the code in inversePcgs made (in setting the kernel, which is used in some situations for pc homomorphisms, I believe) the assumption that the pcgs is given for the whole group.

But in the problematic situation, `hom` will be a homomorphism constructed for a prescribed kernel (and thus know the kernel). So the wrong kernel was never set, but immediately discarded. This is not good procedure, it should instead add the denominator of the pcgs. I have a fix for this.

**Comment by hulpke** [comment]
@fingolfin 
`TryPcgsPermGroup` computes a pcgs for a (factor group of) a permutation group. it is used to use pc group methods for permutation groups and to represent solvable factior groups as pc groups.

The 2-argument version of `ReducedPcElement` occurs in the `Kernel...` method, not in the `inversePcgs` method. It is quite possible that there is dead code in there which has been superseded by other methods.
