### ISSUE TITLE
Improve validation of PackageInfo.g

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#3709]
A typo in a name of an optional component of the package info record was not detected - see example in https://github.com/gap-packages/permut/pull/17. 

We could make this check stricter by allowing only names of components from the specified list.

On the other hand, this will make difficult introducing new components, since validation will fail in older versions of GAP.

Or we will have to do a check dependently on the GAP version.

Any ideas?

**Comment by ChrisJefferson** [comment]
When I've had this problem previously, I've printed a warning about things I didn't understand. It will be a little annoying (but easy to ignore) when such warnings occur in older version of GAP.

**Comment by fingolfin** [comment]
Depends on what we are talking about exactly.

For members of the package info record itself, I wouldn't want even a warning, to be honest, it'd just be super annoying. Adding fields like `License`, `IssueTrackerURL`, `SourceRepository` etc. would have been much more painful; and some of us extensively use the unofficial `AutoDoc` entry in the package info record; and others might want to do similar things.

In the issue you report, though, the issue was actually not in the package info record itself, but rather in its `Persons` member, which is a bit different. There, a warning would be OK, perhaps even an error. Though again, we'd loose quite some flexibility, so I am very reluctant to make this an error by default. 

I wonder, though, if we could do something slightly more clever: When we encounter an unknown member of the pkginfo record (or a subrecord), we could compare it to the list of expected/defined record names (for that particular record) using something like [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance). Then, if the unknown name looks very similar to one of these entries, print a warning (or optional, error).

**Comment by alex-konovalov** [comment]
Or have some special check mode, which package redistribution tools will use, but not usually package authors...

**Comment by ChrisJefferson** [comment]
Why would you want them to be different? It would just mean you had to email suthors

**Comment by fingolfin** [comment]
I don't think we should go ahead with this.

**Comment by alex-konovalov** [comment]
fine
