### ISSUE TITLE
Enable LGTM for code analysis (Semmle) 

### ISSUE THREAD

**Issue by XVilka** [gap-system/gap#3765]
Will help to eliminate obvious errors. C/C++ is supported. See:
- https://lgtm.com/
- https://github.com/marketplace/lgtm

![image](https://user-images.githubusercontent.com/203261/69871982-2f673c80-12ef-11ea-85bd-ff273782cf90.png)

**Comment by ChrisJefferson** [comment]
Have you tried pointing this at the GAP source (is that possible without enabling it on all pull requests?). My past experience is some such tools have great difficulties with GAP's code as it is so unusual (all memory allocation is in GCed `Bag`s for example).

**Comment by ChrisJefferson** [comment]
I decided to ask LGTM to analyse gap, to see what it says. I haven't given the website any special access to my github account, so this shouldn't make any changes, or start adding messages to commits (if it does start doing anything I don't want, I'll hit it hard)

**Comment by ChrisJefferson** [comment]
You can see the output here:

It says it finds 172 alerts, but most of those aren't useful:

* 22 times we've written 'fixme' in a comment
* 144 times a local variable hides a global variable -- I think (I didn't scroll down the whole list as it loads dynamically and really slowly) we have given a function an argument called 'module', when we also have a global variable called 'module'.
* One example of a possible integer overflow in pperm (not positive this is a problem, but I'm going to check)
* One example where it thinks we pointlessly compare a variable to check it's not < 0. This one disturbs me, because I think we DO need to check, and i don't know why it thinks we don't have to. An unnecessary check isn't of course a bad thing.

**Comment by ChrisJefferson** [comment]
I'm not saying we should, or shouldn't enable it, at the moment, but I'm leaning towards it not being useful enough.

I think it's sensible to looking at LGTM before a release, to see if it has flagged up any interesting new issues, but I'm not positive I'd want to enable it for every PR, as we already have multiple things running every PR, and when they break or get confused (which happens to coverage and testing), it's annoying to developers and requires waiting while they rerun or get fixed.

**Comment by fingolfin** [comment]
I looked at LGTM and several similar tools before. I haven't found any that was useful yet. More interesting might be Coverity Scan, though it aims at security,  and frankly I consider that out of scope.

**Comment by XVilka** [comment]
@fingolfin from my experience (in [radare2](https://github.com/radareorg/radare2) project) with Coverity Scan it helps not only with the security bugs, but with many logical bugs too, see how it looks e.g.:

![image](https://user-images.githubusercontent.com/203261/69946506-b18d7600-1526-11ea-868c-7f7a25cba6bc.png)

Indeed, it might be different depending on the codebase. Anyway, just a suggestion to consider.

**Comment by fingolfin** [comment]
As to LGTM: there are just 6 out of 172 warnings which are not obviously useless. Those about the "hidden global variable `module`" are nonsensical in that the supposedly hidden global is declared *after* the function with the local variable that supposedly is hidden (indeed, if one swaps the order, then also GCC and clang report this thanks to `-Wshadow`). The remaining 6 are:
- two about comparison between `UInt` and `unsigned short`, which are harmless
- two about comparisons which are supposedly always false: these are simply wrong (!)
- two about comparisons which are always true -- we know about them, they are there to make the code safer because the involved `enum` values could end up being non-zero.

Coverity Scan might be useful, and if somebody wants to work on setting that up, I'll be happy to review the PR and merge it, assuming the result is useful (i.e. doesn't consist of 99% fluff among which perhaps a fine useful things are hidden). 

Another interesting thing would be to setup a Travis job running <https://clang-analyzer.llvm.org>. But care must again be taken to ensure the result is not useless (i.e.: shouldn't be silent, i.e.: notify if there are problems; but also shouldn't be spammy, i.e.: don't notify for harmless stuff. That means one would have to first address any warnings it produces, to ensure `master` builds warnings free. But I am not sure this is realistic. I actually tried it a month ago, and while it reported a few interesting things, there were also quite a few pointless things that just distracted. (All of this could then of course also be done with the address sanitizer, the UB sanitizer, etc. -- but they all risk being overly noisy...)

I.e.: patches are welcome, but suggestions for further work we could do are not that helpful, I am afraid, no matter how helpful the intentions behind them are, because we simply lack the resources to implement them.
