### ISSUE TITLE
System Panic when working with large solvable group

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#3786]
[This was reported by Heiko Dietrich]

### Observed behaviour

    gap> code:= rec( code := 4036976711286048149259,
    >                extdim := [  ], isFrattiniFree := true,
    >                isUnique := true,
    >             order := 4037839681938311097109 );
    gap> F := PcGroupCodeRec( code );
    <pc group of size 4037839681938311097109 with 2 generators>
    gap> Factors(4037839681938311097109);
    [ 4679, 862970652262943171 ]
    gap> IrreducibleModules(F,GF(4679),1);
     #G  FULL  691935/  68330kb live  4606596/ 263344kb dead  Panic in src/sysmem.c:654: cannot extend the workspace any more!

### Expected behaviour

A clearer error message, possibly in break loop

**Comment by fingolfin** [comment]
Which GAP version? On what operating system? What are the arguments given to GAP to start it?

**Comment by fingolfin** [comment]
ping @heikodietrich

**Comment by hulpke** [comment]
@fingolfin Happened for me in the development version (GAP 4.8.1-7613-g71282e8 of today) on a Macbook Pro. (Same happens on Linux machine (3.10.0-1062.4.3.el7.x86_64)
Startup with standard shell script, only option is -g

**Comment by fingolfin** [comment]
This issue exists at least since GAP 4.5 (probably before, but I can't test that right now).

The root cause is a call to `EmptyPlist` with a huge argument -- namely the `862970652262943171` factor of the group size. GAP tries to make that allocation but that fails. There is no way for GAP to recover from that, because allocations simply are not meant to ever fail in GAP, and all kinds of code rely on that.

Here is a simpler way to get essentially the same crash:
```
gap> l:=[1];;l[2^60-1]:=1;
Panic in src/sysmem.c:654: cannot extend the workspace any more!
```

We can probably duct tape over the `EmptyPlist` crash, and also my simple variant, by checking if the argument is too big. But (a) similar issues will hide in other places, and (b) the computation itself of course still won't work.

Ping @ChrisJefferson and @stevelinton who may wish to ponder this issue, too.

**Comment by ChrisJefferson** [comment]
This is a long standing problem in GAP. It actually wouldn't be hard to force GAP to enter a break loop in this kind of situation (running out of memory when asking for a huge object, but memory isn't actually that full). The problem is, I worry that lots of GAP kernel code isn't prepared for that, so might leave objects in a bad state.

These situations can't be "too bad" (like a lack of CHANGED_BAG calls), because the code must be prepared for an allocation to cause a GC, but it could certainly be inconsistent.

**Comment by ChrisJefferson** [comment]
I created a PR (#3793) which tries to produce a better error here. It of course doesn't fix the fact the code has no (current) chance of working, as it tries to create such a crazy-big array!
