### ISSUE TITLE
"make gap" (or "make doc") should create/update sysinfo.gap 

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#3890]
Please use the following template to submit an issue
(you may delete lines which are not used). Thank You!

### Observed behaviour
```
$ make clean
$ make doc
$ ls sysinfo.gap
ls: cannot access 'sysinfo.gap': No such file or directory
```

### Expected behaviour
the file present

### Copy and paste GAP banner (to tell us about your setup)
current (2020-02-10) master

**Comment by dimpase** [comment]
same with `make gap`

**Comment by fingolfin** [comment]
Could you please explain the reason for *why* you'd expect `sysinfo.gap` to be present?

**Comment by dimpase** [comment]
why should it be absent? that's an essential configuration info.

**Comment by fingolfin** [comment]
When you enter `make doc` you are telling the build system "build exactly the documentation, and anything strictly necessary for that". Likewise, if you enter `make gap`, you are saying "build exactly the `gap` binary, and anything strictly necessary for that".

So, why should the commands build things beyond that what you requested?

**Comment by dimpase** [comment]
how about "make gap"?
you run "make gap" and then many packages do not build.

**Comment by fingolfin** [comment]
Why are you running `make gap`? I am not aware of any GAP documentation suggesting to do that. If there is, it is in an error, and I'd appreciate a pointer to it so that I can fix it.

What we *do* say is to enter `make`, which works as intended.

**Comment by fingolfin** [comment]
In particular, the canonical way to build GAP is to enter `./configure && make`, and if you want to build a full GAP including docs, do `./configure && make && make doc`.

**Comment by dimpase** [comment]
On Mon, 10 Feb 2020, 20:23 Max Horn, <notifications@github.com> wrote:

> In particular, the canonical way to build GAP is to enter ./configure &&
> make, and if you want to build a full GAP including docs, do ./configure
> && make && make doc.
>

if the latter is recommended way to build docs then it makes perfect sense
to add "all" as a dependency of "doc",
and remove that extra "make &&" step from the recommendation.

just the principle of least surprise.

**Comment by fingolfin** [comment]
The “principle of least surprise” assumes that there is some reasonable standard which one might expect to hold, and then one can try not to deviate from that.

Which is why I asked *why* you expect this, and so far I have not yet seen an actual argument that I could understand.

For example, in your last comment, you say “then it makes perfect sense to add `all` as a dependency of `doc`” — and I completely fail to see the logic behind this statement. Why does it make perfect sense?!? My view is diametral opposite: why would `make doc` do anything beyond “making the documentation”? If it did that, I would find it quite surprising. I.e., it would violate the principle of least surprise.

So, as you can see, we can arrive at diametrically opposite conclusions by applying the same “principle”. The problem of course is that we assume different “axioms” here, i.e., our basic assumptions differs. I tried to outline my assumptions (`make foo` should do exactly what is needed to achieve `foo`, nothing more). What are yours?

**Comment by dimpase** [comment]
in my previous comment I said that **if** `./configure
 && make && make doc` is the recommended way to build docs **then** `all` should be a dependency of `doc`.

And most people would reasonably (IMHO) expect that if GAP is needed to build GAP's docs then it gets **fully** built before docs are built. And the latter is not the case for GAP.

**Comment by fingolfin** [comment]
I don't understand this if-then. Why does the one imply the other?!? 

How do you know what most people would reasonably expect? Did you conduct a poll? What sample size? Among the two of us, clearly it's not true, only 50% think so. At least ask on the GAP slack to see what people think?

**Comment by dimpase** [comment]
> The “principle of least surprise” assumes that there is some reasonable standard which one might expect to hold, and then one can try not to deviate from that.

IMHO it is just that you should (unpleasntly) surprise as few people as possible :-)
https://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by fingolfin** [comment]
I *know* what the principle of least surprise/astonishment/etc. is. I just don't agree with you what "people" will find surprising and what not.

**Comment by dimpase** [comment]
> I don't understand this if-then. Why does the one imply the other?!?

I was just explaining how my previous comment was meant to be read, sorry if it was not clear.

**Comment by fingolfin** [comment]
I still don't follow. If the instructions are "enter this command to build GAP *and* the documentation* imply that "doc" should depend on "all" ? Sorry, but I think this is really arbitrary.

I don't think this discussion is fruitful. If you can bring some concrete evidence that people other than you find the current behavior surprising; or that people run into actual issues because for some reasons they executed `make doc` and expected it to do something different from what it does; then we can re-open this discussion.

**Comment by dimpase** [comment]
> what "people" will find surprising and what not.

I find it quite surprising that GAP has a semi-built state where it runs, but one cannot build its pkgs. This is suprising, IMHO.

**Comment by dimpase** [comment]
https://github.com/gap-system/gap/wiki/Building-main-GAP-manuals says that you need to do 
`make && make doc` to build manuals. 

Why not shorten it to `make doc` ?
The purpose of `make` is to automate things, and so `make doc` should become the equivalent of the current `make && make doc`.
