### ISSUE TITLE
Broken makemanuals in Travis

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#3892]
See e.g. https://travis-ci.org/gap-system/gap/jobs/648833282

This does not fail the build, so went unnoticed:
```
/bin/mkdir -p dev/log
( cd doc/ref ; echo 'Read("testconsistency.g");' | /home/travis/build/gap-system/gap/bin/gap.sh --quitonbreak -b -m 100m -o 1g -q -x 80 -r -A  | \
               tee `date -u +../../dev/log/check_manuals_%Y-%m-%d-%H-%M` )
****************************************************************
*** Checking types in ManSections 
****************************************************************
./../../lib/matobj2.gd:737 : NewVector uses Oper instead of Constructor
./../../lib/matobj2.gd:738 : NewZeroVector uses Oper instead of Constructor
./../../lib/matobj2.gd:773 : NewMatrix uses Oper instead of Constructor
./../../lib/matobj2.gd:774 : NewZeroMatrix uses Oper instead of Constructor
./../../lib/matobj2.gd:
775 : NewIdentityMatrix uses Oper instead of Constructor
Syntax error: Identifier expected in stream:1
_EVALSTRINGTMP:=IsBound([]);
                        ^
Error, Could not evaluate string.
 at /home/travis/build/gap-system/gap/lib/string.gi:658 called from
+exit 0
```
`testconsistency.g` is my code, will have a look.

**Comment by fingolfin** [comment]
This is likely due to the MatrixObj changes (CC @ThomasBreuer )

**Comment by alex-konovalov** [comment]
Thanks @fingolfin - so there are two issues here, one with the documentation using wrong types, another with the code that tests it not properly handling test failure (?)

**Comment by ThomasBreuer** [comment]
I had a look at the file `doc/ref/testconsistency.g`.
On the one hand, it assumes that operations created by `DeclareConstructor` are documented using GAPDoc's `<Constr>` element.
On the other hand, the relevant code contains a comment which states that this situation does apparently not occur.
Indeed, there are quite some constructors in GAP but none of them had been documented, until recently the abovementioned ones from `matobj2.gd` got documented.

I am not sure whether the heuristics in `testconsistency.g` are useful.
(If such checks are regarded as interesting then one should better think about a tool that can be used also for package manuals, not just for the main manual.)
On the other hand, if GAPDoc offers a `<Constr>` element then there is no reason not to use it.

Concerning the syntax error, this is due to the invalid function name `[]`.

I will open a pull request that fixes these problems.

**Comment by ThomasBreuer** [comment]
just for the record: The pull request which I had promised was #3894
