### ISSUE TITLE
The image of a map is not contained in its range?

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#396]
It is possible to do the following:
```
gap> phi:=GroupHomomorphismByImages(Group((1,2)),Group((2,3)),[(1,2)],[(1,2)]);
[ (1,2) ] -> [ (1,2) ]
gap> Image(phi,GeneratorsOfGroup(Source(phi))[1]) in Range(phi);
false
gap> Image(phi,GeneratorsOfGroup(Source(phi))[1]);
(1,2)
gap> Range(phi);
Group([ (2,3) ]
```
When we were looking at this earlier, we had to wait for the polycyclic package to be updated in order to provide the fix that performs the membership test for generator images being in the range with an NC method which doesn't.

**Comment by fingolfin** [comment]
I don't recall this, nor how this has anything to do with polycyclic. Perhaps you mean to say that the fix for this issue would break the polycyclic package, and thus there was / is need to wait for a polycyclic update?

But then, wouldn't it be better to also list the proposed fix? Otherwise, neither Bettina nor me can update polycyclic suitably, as we wouldn't know what's required...

**Comment by fingolfin** [comment]
So @alex-konovalov explained to me that this refers to an old issue we had in our experimental and private Redmine issue tracker. So I was able to look there, and figure out what this is about. I will try to summarize what this is about:

Around version 4.6.x, in later 2012/early 2013, this issue was reported first. In response, on 2012-11-16 @hulpke made some changes to the `GroupHomomorphismByImages` (GHBI) and `GroupGeneralMappingByImages` (GGMBI) code. In particular, new operations `GroupHomomorphismByImagesNC` (GHBI-NC) and `GroupGeneralMappingByImagesNC` (GGMBI-NC) were introduced. The old code was moved there, and the new non-NC versions were changed to perform more tests.

This was of course in principle the right change. Problem was that it slightly broke backwards incompatibility -- because now anybody who installed methods for GHBI and GGMBI would run into problems; one needs to install those methods for GHBI-NC and GGMBI-NC now.

Luckily, very few packages ever install methods for these two operations. Indeed, to my knowledge only the polycylic package ever does so.

Anyway, since the change broke some code using polcycylic, we temporarily reverted it, to wait for a new polycyclic version addressing the issue (by installing the methods for GGMBI-NC if it exists, and otherwise installing them for GGMBI). This was done in polycyclic 2.11, released in March 2013.

It seems we then forgot to re-enable the new, better GHBI / GGMBI code. Well, we can probably do so now, safely. I'll take a look at it.

**Comment by fingolfin** [comment]
With the PR applied, I get this:
```
gap> phi:=GroupHomomorphismByImages(Group((1,2)),Group((2,3)),[(1,2)],[(1,2)]);
Error, images must lie in range group called from
...
```

**Comment by chsievers** [comment]
Please note that this also breaks code that uses GHBI when the additional tests are not computable.
One may guess that this only occurs when the previous tests already forced you to use the NC version, but that is not true.
One case that used to work, but does no longer, is a homomorphism from a free group to a subgroup of an fp group whose element test doesn't terminate.
I just had to fix such a case in the FGA package.
