### ISSUE TITLE
Hall Subgroup cannot be computed?

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-system/gap#404]
The following gives me an error, and I am unsure if this should be happening or not. Could someone help me out with this, please? Thank you.

    gap> G := Group([ (1,2)(3,4)(5,6)(7,8)(9,10)(11,12)(13,14)(15,16)(17,18)(19,20)(21,22)
    > (23,24)(25,26)(27,28)(29,30), (2,3)(5,6)(8,9)(11,12)(14,15)(17,18)(20,21)
    > (23,24)(26,27)(29,30), (1,5)(6,10)(11,15)(16,20)(21,25)(26,30) ]);
    gap> PrimeDivisors(Size(G));
    [ 2, 3, 5, 7 ]
    gap> pi := [ 5, 7 ];;
    gap> HallSubgroup(G, pi); 
    Error, Record: '<rec>.cocycleToList' must have an assigned value in
      N := ocr.cocycleToList( R ); at /home/ghorvath/work/gap/lib/onecohom.gi:1315 called from 
    OCOneCocycles( ocr, true 
     ); at /home/ghorvath/work/gap/lib/fitfree.gi:1207 called from
    HallsFittingFree( Image( hom ), pi 
     ) at /home/ghorvath/work/gap/lib/fitfree.gi:1278 called from
    HallViaRadical( G, pi 
     ) at /home/ghorvath/work/gap/lib/fitfree.gi:1348 called from
    <compiled or corrupted statement>  called from
    <function "local function">( <arguments> )
     called from read-eval loop at line 15 of *stdin*
    you can 'return;' after assigning a value
    brk>

**Comment by hulpke** [comment]
Yes, I'll fix this.

**Comment by alex-konovalov** [comment]
@hulpke thanks! Just to draw you attention that the fix is in your fork, not in the main repository, so it may be a bit early to close the issue. Was the intention to commit the fix to the main repository, or are you going to submit a pull request?

**Comment by hulpke** [comment]
@alex-konovalov Yes, I know. I was hoping there would be a 1-button function in github or source tree that would copy commits over into the other repository, If not I will probably collect a number of such minor changes before making a branch for a pull request.

**Comment by alex-konovalov** [comment]
@hulpke the command `git push upstream master` should push to the main repository instead of your fork (provided `git remote -v` will report the `upstream` set correctly). You may need to do `git pull --rebase upstream master` before trying to push to the main repository.

**Comment by hulpke** [comment]
@alex-konovalov Thank you.

**Comment by alex-konovalov** [comment]
@hulpke thanks - I will close this now. Of course, this backfires now by 4 other commits that you've pushed to the master. They hopefully would not break anything (Magma convertor, export to LaTeX), but otherwise this could lead to some complications....

It may be my fault - I should seen this coming and tell you to cherry-pick only one commit from the branch where you're working onto the master branch and then push... But it seems that you were not working on a branch at all - all commits were happening in the master branch of your fork. That could be a problem in the future: if you would be making a pull request, your pull request would have 5 commits belonging to 5 unrelated changes. Instead, a good habit is to work on each logical change on an individual branch, so whenever you want to do something new, call

```
git branch name-of-branch
git checkout name-of-branch
```

and then work on a branch.
