### ISSUE TITLE
Unexpected error for IsAutomorphismGroup

### ISSUE THREAD

**Issue by PaulaHaehndel** [gap-system/gap#4070]
The documentation about `IsAutomorphismGroup( G )` not specifies that the group has to be given in a special respresentation, but  `IsAutomorphismGroup( G )` returns an error when called for GL(2,5).

### Observed behaviour
```
 IsAutomorphismGroup(GL(2,5));
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 2nd choice method found for `IsAutomorphismGroup' on 1 arguments at /mnt/c/gap-4.11.0/lib/methsel2.g:249 called from
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
 called from read-eval loop at *stdin*:99
type 'quit;' to quit to outer loop
```

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.11.0 of 29-Feb-2020
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv7
 Configuration:  gmp 6.1.2, GASMAN, readline
 Loading the library and packages ...
 Packages:   Alnuth 3.1.2, AtlasRep 2.1.0, AutoDoc 2019.09.04, AutPGrp 1.10.2, CRISP 1.4.5, CTblLib 1.2.2,
             Digraphs 1.1.2, FactInt 1.6.3, Forms 1.2.5, GAPDoc 1.6.3, genss 1.6.6, GRAPE 4.8.3, IO 4.7.0,
             IRREDSOL 1.4, orb 4.8.3, OrbitalGraphs 0.1, Polycyclic 2.15.1, PrimGrp 3.4.0, recog 1.3.2,
             ResClasses 4.7.2, SmallGrp 1.4.1, SpinSym 1.5.2, TomLib 1.2.9, TransGrp 2.0.5, utils 0.69
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by fingolfin** [comment]
Thanks for the report!

I think `IsAutomorphismGroup` only works for groups in the filter `IsGroupOfAutomorphisms` (i.e. whose elements are genuine automorphisms, i.e. GAP mappings). This suggests that...
1. for other groups, such as GL(2,5), it should just return false, instead of producing an error;
2. the documentation should be adjusted to make it clear that this is the intended behavior.

I see no good other option; in particular, while every group is automorphism group of *some* object, not every group (isomorphism class) is the automorphism group of another group (e.g. C_3 isn't). But I know of no efficient computational criterium to check that; also, it doesn't seem like a very useful property to test for.

Ping @hulpke in case he has more insights.

**Comment by hulpke** [comment]
`IsAutomorphismGroup` is the property of being the full automorphism group of another group. It is declared only for `IsGroupOfAutomorphisms` -- that's why there is a "No method found" error.

The documentation (in morpheus.gd) says:

`IsAutomorphismGroup`
 indicates whether <A>G</A> is the full automorphism group of another
group <M>H</M>, this group is given as <Ref Attr="AutomorphismDomain"/> value of <A>G</A>.

**Comment by fingolfin** [comment]
Yeah, that's what I thought.

The I think the documentation would be clearer if it explicitly mentioned `IsGroupOfAutomorphisms` -- after all, `GL(d,p)` is also the "full automorphism group of another group".

**Comment by PaulaHaehndel** [comment]
Thanks.
That explains the behaviour and the documentation, thank you both.
I agree that it would be great if the documentation could be a bit more explicit in this point such that someone reading it doesn't need this conversation to understand it :)
