### ISSUE TITLE
RunAsyncTask not working (HPC-GAP)

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#409]
The hpcdoc.html contains an example about `RunAsyncTask`. 

```
RunAsyncTask(function() Print("Hello, world!\n"); end);;
```

When I run that code, nothing is printed. `Print()` itself works fine.
I'm using a fresh install and the commit `6278692` from 01 Dec.

**Comment by rbehrends** [comment]
In HPC-GAP, output that occurs in a different thread is redirected to its own output stream that is normally hidden. Use `!list` to see which threads have pending output, then use `!<n>` (where `<n>` is the thread's id) to switch to that output stream (and `!0` to switch back to the main thread).

And yes, ideally the user should be alerted rather than having to check for it; unfortunately, this is a bit tricky as it requires some non-trivial hacking of the line editor.

**Comment by ssiccha** [comment]
Hm, should that explanation maybe be added to the 'hpcdoc'?

**Comment by markuspf** [comment]
This is the current documentation of the UI: https://github.com/gap-system/hpcdoc/blob/master/ui.txt 
If you think something should be added, just submit a pull-request to `hpcdoc`.
