### ISSUE TITLE
[Install Question] How to make a relocatable install`

### ISSUE THREAD

**Issue by epsilon-0** [gap-system/gap#4136]
Currently after compiling the package, it is hard to move the installation to a different location as a lot of the files have the location hardcoded into their text.

I am currently unsure how to make this a relocatable install.

This would be really helpful as it would help make this into a package for operating systems, whereas currently people have to install this manually, and its very hard to keep track of dependencies.

Thanks,
Aisha

**Comment by fingolfin** [comment]
There are plenty of packages for GAP for various Linux distributions, see https://repology.org/project/gap. Granted, the process for packaging GAP could (and should) be made easier; but the usual proposal to do so is by adding a `make install` target, see e.g. <https://github.com/gap-system/gap/issues/197>. Almost no package distributions requires full relocatability; achieving that is much harder, and it requires platform specific work.

Why do you think this would be helpful in making a GAP package for operating systems? Which (distributions of) operating systems are you thinking about here?

**Comment by fingolfin** [comment]
See also https://github.com/gap-system/gap/blob/master/README.buildsys.md and what it says on `make install`.

**Comment by fingolfin** [comment]
@epsilon-0 does this answer your question? If not, please provide some further details taking into account what I wrote. Thank you!

**Comment by epsilon-0** [comment]
I did take a look at that but it still left a lot of questions.

I'm still unclear as to how to install the files after finishing a `make -f GNUmakefile all`.
I also managed to replicate `BuildPackages.sh`.

So I'm left with the compiled packages but I am still unclear which parts I need to install.

**Comment by fingolfin** [comment]
Well, it's still not clear to me what your question is: How to "install" GAP (e.g. into /usr), e.g. for packaging in a Linux distro? I can help with that. Or how to do a *reloctable* install? That's much harder.

**Comment by epsilon-0** [comment]
@fingolfin 
Yes, knowing how to install it in /usr would be helpful as well.

A quick 5s overview of Gentoo packaging system
- Compile package in `/some/temp/dir` 
- Do temporary install in `/someother/tmp/directory'
- Copy files from `/someother/tmp/directory` to `${PREFIX}/usr` where `PREFIX` is used for cross-compilation targets if needed, it is unset by default.

So for the third step, people have different `PREFIX` values, needing the install to be kind of relocatable.

But if that is too much, I'd really appreciate the `/usr` install as well :smile_cat:

**Comment by fingolfin** [comment]
So, are you looking into updating the GAP package for Gentoo? That'd be awesome, thank you!

Of course the install PREFIX can be adjusted. -- but like with most UNIX packages based around `autoconf`, you need to specify it *before* you compile, and can't relocate arbitrarily afterwards. We also support (well.. kinda... see below) the use of `DESTDIR` to prefix the PREFIX for the purpose of package creation.

I'll give you a brief rundown, but also really recommend to have a look at how some other distros do it; see https://repology.org/project/gap/versions for an overview of what's there I esp. recommend the Fedora port by @jamesjer which is in great shape, see https://src.fedoraproject.org/rpms/gap and in there https://src.fedoraproject.org/rpms/gap/blob/master/f/gap.spec -- even if one doesn't know the .spec format (I don't!) it isn't too hard to figure out what's going on.

Feel free to ask follow up questions later. And yeah, a "proper' `make install` is something I wanted for years but it's ... complicated ... but progress has been made and I really hope we can get there in the not so distant future.

Anyway, here's a rough build recipe (typed in from memory, so it may not be 100% accurate).

First, build GAP
```bash
./configure --prefix=$PREFIX  # bog standard
make  # feel free to use -jNNN
make doc  # buld the manual, requires LaTeX for the PDF versions; alternatively, use `make html` to only get the HTML/text ones
```

Now, install it. There used to be a `make install` target which printed a big fat WARNING that it was incomplete and buggy, then did 90% of the work. Since too many people missed or ignored the big fat warning, I removed that again, but left the parts in. Unfortunately, those also are somewhat buggy in GAP 4.11.0. However, you could extract a patch from the `stable-4.11` branch to fix most of that (GAP 4.11.1 should have been out months ago, but unfortunately we have a serious lack of people with time and the ability to work on GAP, and take care of releases, or for that matter, automating the release process to eliminate that bottleneck... anyway, I don't want to whine here, I am just trying to convey that we are not intentionally making this hard for you, but rather we are also volunteers with far too much .

Anyway: the `install` target in `Makefile.rules` basically should at some point be restored to look something like this:
```
install: install-bin install-gaproot install-headers install-libgap install-pkg
```
after which you then could do `make install DESTDIR=/some/tmp/dir` and things would get installed into `/some/tmp/dir/${PREFIX}` from which one then can prepare a package. Now, that `install` target isn't there (resp. the one that's there just prints an error), but you can still do this: `make install-bin install-gaproot install-headers install-libgap DESTDIR=/some/tmp/dir`. (I omitted `install-pkg` here because it is not implemented; the reason being that what it should do depends substantially on how the distro for which GAP is being packaged handles such things...)

However, as  I mentioned, these targets are somewhat buggy, and/or incomplete in GAP 4.11.0, so either you'll want to apply some patches from stable-4.11 (at the very least 4b8aebd97e00026ab97ddf1551e3fd6d5add1f78); or just not call those targets and instead replicate the code they are doing; and/or look at what e.g. Fedora does to inform what you do.


Aaaanyway: This comment is both too long already and still far too short, but I think it's better if you read this and have a look around and then I'll try to help as you go. Also, I'd be interested in working on restoring the `make install` target and fixing the remaining issues; if you are interested and willing in playing along with that, I could start a PR based on the `stable-4.11` branch (or even based on the `v4.11.0` tag, so that you could just grab patches from there) where we then could work on implementing the required changes... Alas, I fully understand if you'd rather cut directly to the chase, your time is limited as well, of course, just like mine :-).

Good luck!

**Comment by epsilon-0** [comment]
@fingolfin 
So this took a bit longer than I was expecting but I did manager to get GAP to build with a relocatable install.
I had to do a few extra `sed` commands with PREFIXs and DESTDIRs and BUILDDIRs but it is working now.
I'll see if I can upstream and make a PR to fix the core system install at least (`install-pkg` is way out of scope) but that will take A LOT longer, hope that is fine.

The package is now available in Gentoo Science - https://github.com/gentoo/sci/tree/master/sci-mathematics/gap
This only builds the core gap system, from the gap-core + required packages tarballs.
But it is working quite nicely and am also able to get it to build with optional julia/julia-gc, (memcheck and valgrind are available configuration options but hitherto untested by me).
This should be very useful for people to use.

There is additional effort from other Gentoo community members who are managing a Sage-on-Gentoo repository who make the gap packages available individually - https://github.com/cschwan/sage-on-gentoo/tree/master/dev-gap
I've not tested their installation system and it is not an official Gentoo repository, but it does look quite good :smile_cat: 

I will

**Comment by fingolfin** [comment]
Glad to hear it worked out!

**Comment by alex-konovalov** [comment]
@epsilon-0 @fingolfin that's good - so it seems we may close this issue now?

**Comment by epsilon-0** [comment]
Yes, that sounds good!
