### ISSUE TITLE
Strange behaviour of IsMersenneTwister

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#423]
In commit https://github.com/gap-system/gap/commit/dd4ba8ff8d156b95f1882a6ae8dcb3060603e8b3 @frankluebeck added the following example:
```
gap> mysource := RandomSource(IsMersenneTwister, 42);;
gap> Random(mysource, 1, 10^60);
474943581767832038339909502952186501785153672757525589711853
```
It happened however that this example is reproducible only in 64-bit build with GMP.

In all of the three other configurations (32-bit builds with/without GMP and 64-bit build without GMP) the result of `Random` is 
```
999331861769949319194941485000557997842686717712198687315183
```

First I thought that this is related to building GMP with c++ support, added in #399, but then I've checked that the same happens in the stable-4.7 branch. This must be just the new example that revealed this behaviour, which has been here before.

One could certainly adjust the example to run in the same way everywhere. For example replacing 10^60 by 10^30 helps. But I am also worried that this may point to a more serious problem and should be investigated. And if there is no bug here, then we should be aware that the output of randomised algorithms may also depend on the way how GAP was compiled.

**Comment by frankluebeck** [comment]
This is a bug. In the first implementation I made sure that the results of Random are the same on 32-bit and 64-bit versions of GAP.

Using an old installation of GAP 4.4.12 I get `999331861769949319194941485000557997842686717712198687315183` in all versions while in GAP 4.7.6 and the current master branch the 64-bit version gives a different result.

This is potentially a not so obvious dangerous bug because the high quality of randomness from the Mersenne twister may be compromised.

**Comment by fingolfin** [comment]
I'll bisect this (thanks to the old repository available to me, that should be easy enough)
