### ISSUE TITLE
e-mails sent by codecov[bot]

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#4260]
This is not an important problem, but since some experts on code coverage are anyhow sitting together during the GAP Days, it is perhaps worth mentioning.

After submitting pull requests, I get e-mail messages from "codecov[bot]" which tell me that due to the proposed changes, the code coverage will decrease by  35 % or so.
This is of course nonsense (in particular when I want to change only something in the documentation), and the code coverage shown in the pull request then changes, as more and more tests finish.

My question is why these messages are sent to me before the relevant information is available.

**Comment by fingolfin** [comment]
These comments are not really sent by the codecov bot, but rather by github when the codecov bot adds it comment to the PR.

And right now, the bot adds it immediately when the first job finishes; the comment then of course only contains the results from that first job, i.e., the fastest job, which in generally means it also tested the least, and thus severely underreports coverage.  It then repeatedly updates its comment whenever it gets additional data, until finally it has sensible content.

There are two ways to improve this:
1. we can disable the codecov comments; and instead enable Codecov "statuses" again (which we disabled in the past, because they implied that a PR was marked as "red" if the coverage drops even a little; but these days, there is a setting to have them show up but not "make the PR read"). We use this in Oscar.jl; there the Codecov results can be seen in the checks list, see e.g. https://github.com/oscar-system/Oscar.jl/pull/279/checks and also at the bottom of https://github.com/oscar-system/Oscar.jl/pull/279/ ; there are then also links to the report there

2. we can configure codecov to wait with adding its comment until all data is there; I know this can be done for Coveralls, but I am not 100% sure how and whether it can be done for Codecov...

So for now, I think option 1 is best.

**Comment by alex-konovalov** [comment]
Option 1 as at the bottom of https://github.com/oscar-system/Oscar.jl/pull/279 - LGTM!
