### ISSUE TITLE
LoadPackage calls in the GAP library

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#429]
I've noticed that there are several calls of LoadPackage in the GAP library. I am interested to know whether we are happy with them being here (and if so, then write here why), or whether this should be cleaned up.

* `lib/system.g` specifies `Dependencies := rec( NeededOtherPackages := [ [ "gapdoc", ">= 1.2" ] ]];` and GAP will not start without GAPDoc. However, there is a check
```
lib/package.gi:1996:  if LoadPackage("GAPDoc") <> true then
```
which is in fact obsolete.

* Other occurrences of LoadPackage calls (the one commented out is in the documentation) are:
```
colorprompt.g:104:##  LoadPackage("GAPDoc");
grplatt.gi:842:  if LoadPackage("tomlib")=true then
grplatt.gi:2716:  LoadPackage("tomlib"); # force tomlib load
grplatt.gi:2734:  LoadPackage("tomlib"); # force tomlib load
integer.gi:711:        if LoadPackage("FactInt") = true then
morpheus.gi:1888:    LoadPackage("autpgrp"); # try to load the package if it exists
morpheus.gi:1891:    LoadPackage("autpgrp"); # try to load the package if it exists
package.gi:1996:  if LoadPackage("GAPDoc") <> true then
```
and one more which genuinely needs to be there because ParGAP is loaded in a special way:
```
init.g:1170:  LoadPackage("pargap");     
```

* Finally, looking for code in `lib`, one shoud remember to look at `grp`: it has not only the data, but some code as well, and it has this:
```
grp/simple.gi:156:  if LoadPackage("atlasrep")<>true then
```

It seems to me that something is missing. We insist that package should not call LoadPackage but instead must use dependencies mechanism to specify needed and suggested packages. However, we use LoadPackage in the GAP library and do not use anything like `Dependencies.SuggestedOtherPackages` there. Any thoughts?

**Comment by hulpke** [comment]
That is you're asking for the converse of autoload -- the library, not the package, deciding about packages being loaded from the start?

Is there a risk that (say on Windows) atlas rep will whine every time about a missing external binary for downloading?

**Comment by stevelinton** [comment]
We have the basic mechanism. I think this is just cleanup needed. These packages should be either needed or suggested in lib/system.g.  If they are suggested then there should be no messages if they cannot be loaded for any reason and the system should still work (possibly more slowly or with some restricted functionality).  The calls to load package that Alexander lists above should either be removed (if they just try and load a package for speed) or replaced by  clean error messages if the package is really needed for some functionality.

**Comment by hulpke** [comment]
@stevelinton I think there are two further issues: 
- How would code then test for the availability of a package? (E.g. the subgroup lattice routines use a heuristic on the method to use depending on whether the tables of marks library is available.) This could be for speed, but might not be separated in a plausible operation so that method selection would take care of it.
- How to deal with operations that are only declared in a package (SimpleGroup calls AtlasGroup from the atlasrep package to avoid having to store some representations in duplicate).

**Comment by alex-konovalov** [comment]
@hulpke: `IsPackageMarkedForLoading("packagename", ["version"])` should resolve both issues. This is what packages should do, and I think the same mechanism should be used in the core system.

**Comment by stevelinton** [comment]
Yes. Combined with "suggesting" the package that does exactly what you want (and is quick). Maybe we should give that function a more intuitive name, although finding one that captured the exact meaning (relevant when complex package interdependencies are being resolved) is quite tricky.

I'm not sure what the problem withy `AtlasGroup` is. You might need 

    if not IsBound(AtlasGroup) then AtlasGroup := fail; fi;

to avoid Syntax errors, but otherwise you are fine. if IsPackageMarkedForLoading("atlasrep") returns true then (once package loading is completed) AtlasGroup should be defined.

**Comment by hulpke** [comment]
@stevelinton @alex-konovalov Thank you -- I will change this.
The issue with AtlasGroup was simply on whether it can be called -- I'm using `CallFuncList(ValueGlobal("AtlasGroup"),params)` to avoid syntax errors.

**Comment by alex-konovalov** [comment]
Thanks @hulpke for starting this in #431. 

I think that replacing all `LoadPackage` calls by `IsPackageMarkedForLoading` is only the first stage of the cleanup. 

First of all, these calls are scattered across the library and not documented anywhere. It's completely plausible that some providers of alternative distributions will omit some packages being unaware of this.

My suggestion is that in addition to `GAPInfo.Dependencies := rec( NeededOtherPackages := [ [ "gapdoc", ">= 1.2" ] ]];` in `lib/system.g` we should have `GAPInfo.Dependencies.SuggestedOtherPackages` which will list TomLib, FactInt, AutPGrp and AtlasRep. This will make this list available in one place and even accessible programmatically via `GAPInfo` record. Introducing this most likely will not cause any disruptions, since all these packages are loaded by default anyway - this will only change the order in which they are loaded. 

Second, I am worried that our regression tests do not cover situations when these packages are not available at all. Even if GAP is started with the `-A` option, these packages will be loaded at runtime later, so we do not monitor how big is the performance improvement provided by these packages, and never run the branch of the algorithm which is intended as a fallback solution if loading these packages fails. 

After the switch to `IsPackageMarkedForLoading` this will change: when GAP is started with `-A` option, `IsPackageMarkedForLoading` will return `fail` for all packages except GAPDoc, so we will be actually testing fallback implementations (get ready to surprises!). Hence, to ensure that both implementations are covered I suggest that packages from `GAPInfo.Dependencies.SuggestedOtherPackages` should not be loaded if GAP is started with `-A` option.

**Comment by stevelinton** [comment]
> On 6 Jan 2016, at 12:42, Alexander Konovalov <notifications@github.com> wrote:
> 
> Thanks @hulpke for starting this in #431.
> 
> I think that replacing all LoadPackage calls by IsPackageMarkedForLoading is only the first stage of the cleanup.
> 
> First of all, these calls are scattered across the library and not documented anywhere. It's completely plausible that some providers of alternative distributions will omit some packages being unaware of this.
> 
> My suggestion is that in addition to GAPInfo.Dependencies := rec( NeededOtherPackages := [ [ "gapdoc", ">= 1.2" ] ]]; in lib/system.g we should have GAPInfo.Dependencies.SuggestedOtherPackages which will list TomLib, FactInt, AutPGrp and AtlasRep. This will make this list available in one place and even accessible programmatically via GAPInfo record. Introducing this most likely will not cause any disruptions, since all these packages are loaded by default anyway - this will only change the order in which they are loaded.
> 

This was my intention. We could even go further and add all currently auto-loaded packages here as a first step towards
deprecating the mechanism where packages decide they should be auto-loaded in favour of one where GAP, or the users preferences determine this. 

> Second, I am worried that our regression tests do not cover situations when these packages are not available at all. Even if GAP is started with the -A option, these packages will be loaded at runtime later, so we do not monitor how big is the performance improvement provided by these packages, and never run the branch of the algorithm which is intended as a fallback solution if loading these packages fails.
> 
> After the switch to IsPackageMarkedForLoading this will change: when GAP is started with -A option, IsPackageMarkedForLoading will return fail for all packages except GAPDoc, so we will be actually testing fallback implementations (get ready to surprises!). Hence, to ensure that both implementations are covered I suggest that packages from GAPInfo.Dependencies.SuggestedOtherPackages should not be loaded if GAP is started with -A option.

We shouldn’t change the behaviour of options to suit our testing. The system should be designed for the users and the testing should work around that.

The question is what does -A mean (and do we need other options).

I’m inclined to think -A means “load as little as possible” in which case it should indeed not load packages which are suggested but not needed by GAP.

We could offer more refined options. I could imagine things like

—dont-load-gap-suggested-packages
—dont-load-self-suggested-packages
—dont-follow-package-suggestions

or even 

—dont-load-unless-needed=package1,package2,….
—always-load-packages=package1,package2,….
—only-follow-suggestions-to=package1,…..
—only-follow-suggestions-from=package1,….

Surely not all of these are sensible, but it might be worth thinking about what is useful.

	Steve

**Comment by alex-konovalov** [comment]
> I’m inclined to think -A means “load as little as possible” in which case it should indeed not load packages which are suggested but not needed by GAP.

This was my initial though too. However, what if there are users who prefer to always start GAP with `-A` and then load packages explicitly? For them, the behaviour of the system may suddenly change since e.g. computing of the automorphism group of a _p_-group will became slower because AutPGrp will not be loaded. Hmm... Perhaps we need a separate option indeed, which in this case is `—dont-load-gap-suggested-packages`. It will only prevent their loading when GAP is started, so it will be still possible to call `LoadPackage` subsequently.

**Comment by hulpke** [comment]
> I’m inclined to think -A means “load as little as possible” in which case it should indeed not load packages which are suggested but not needed by GAP.

I agree. Not loading packages is something done deliberately (e.g. to sort out incompatibilities) and a user who does so will be aware of potentially losing improved functionality.

**Comment by frankluebeck** [comment]
@alex-konovalov wrote:
> My suggestion is that in addition to GAPInfo.Dependencies := rec( NeededOtherPackages := [ [ "gapdoc", ">= 1.2" ] ]]; in lib/system.g we should have GAPInfo.Dependencies.SuggestedOtherPackages which will list TomLib, FactInt, AutPGrp and AtlasRep. 

I think introducing this as a further mechanism to specify the packages loaded at startup is a bad idea. When the entry `GAPInfo.Dependencies.NeededOtherPackages` was introduced we intentionally did not introduce a component `SuggestedOtherPackages`, but introduced the user preference `"PackagesToLoad"` instead.

The idea was that the  default value of the `"PackagesToLoad"` preference is exactly the list of `SuggestedOtherPackages` but that  it becomes easy for any user to change this list according to  own purposes.

Introducing a `GAPInfo.Dependencies.SuggestedOtherPackages` entry would only make everything more complicated and not provide any benefit. If `SuggestedOtherPackages` had higher priority than the user preference then the user preference would be partially disabled, which would be bad.
If the user preference had higher priority than the `SuggestedOtherPackages` (as it should!) then
the latter is just irrelevant. 

And @stevelinton wrote:
> We could even go further and add all currently auto-loaded packages here as a first step towards deprecating the mechanism where packages decide they should be auto-loaded in favour of one where GAP, or the users preferences determine this.

Please, note that packages cannot decide themselves if they want to be autoloaded. The former corresponding `AutoLoad` entry in `PackageInfo.g` files is just ignored since quite a few years.
The packages which are loaded when starting GAP are exactly those in `GAPInfo.Dependencies.NeededOtherPackages` and, if GAP is called without `-A` option, those specified by the `"PackagesToLoad"` user preference. This looks sufficiently easy to understand (and document) and very flexible to me and I don't see any need for further complications.

Nevertheless, we could introduce a `GAPInfo.Dependencies.SuggestedOtherPackages` with exactly the meaning I mentioned before: It is defined in `lib/system.g` (which would be a nicer place) and is used in `package.gi` as the default value of the user preference "PackagesToLoad". Another slight improvement would allow pairs [pkgname, version] instead of just package names in that list. If there is interest, I could provide a pull request implementing this.

**Comment by stevelinton** [comment]
I had forgotten about the User Preference. 

I agree that this is the right mechanism. A comment in system.g might be useful to remind people of this.

	Steve

**Comment by stevelinton** [comment]
All resolved in the library now
