### ISSUE TITLE
RankAction should check that the given action is transitive.

### ISSUE THREAD

**Issue by lhsoicher** [gap-system/gap#4370]
### Observed behaviour
```
gap> RankAction(SymmetricGroup([1..4]),[1..5]);                       
3
```
### Expected behaviour

I would expect an error message and a break loop to be entered.

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.11.1 of 2021-03-02
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv7
 Configuration:  gmp 6.1.2, GASMAN, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.1.2, AtlasRep 2.1.0, AutoDoc 2020.08.11, 
             AutPGrp 1.10.2, Browse 1.8.11, CaratInterface 2.3.3, CRISP 1.4.5, 
             Cryst 4.1.23, CrystCat 1.1.9, CTblLib 1.3.1, FactInt 1.6.3, 
             FGA 1.4.0, Forms 1.2.5, GAPDoc 1.6.4, genss 1.6.6, IO 4.7.0, 
             IRREDSOL 1.4.1, LAGUNA 3.9.3, orb 4.8.3, Polenta 1.3.9, 
             Polycyclic 2.16, PrimGrp 3.4.1, RadiRoot 2.8, recog 1.3.2, 
             ResClasses 4.7.2, SmallGrp 1.4.2, Sophus 1.24, SpinSym 1.5.2, 
             TomLib 1.2.9, TransGrp 3.0, utils 0.69
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by fingolfin** [comment]
Strictly speaking, this involves undefined behaviour (we only state what `RankAction` does if the given action is transitive, not what happens if it is not)...

To fix this in the way @lhsoicher suggests, we'll have to call `IsTransitive` at the start of `RankAction`, which of course incurs a performance penalty.. Not sure how bad that is relative to the cost of `RankAction` itself, though (and we might be able to do it more cleverly; I haven't looked at the code yet).

(Of course if one uses an `ExternalSet` this information also can be stored)

**Comment by wilfwilson** [comment]
This topic issue also comes up for some (most? all?) other similar  functions, such as `Blocks` (see #3364).
