### ISSUE TITLE
`BuildPackages.sh --strict` no longer works

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4384]
_Previous title:_ `CI: failure to compile IO, profiling should cause the relevant GitHub Actions step to fail`

Right now, it doesn't: In https://github.com/gap-system/gap/pull/4381/checks?check_run_id=2305769116 it fails to compile `io` but just goes on. And that despite using `BuildPackages.sh --strict` which should give us a non-zero exit code. Perhaps that got broken, or perhaps we are not correctly passing it on, or...

**Comment by wilfwilson** [comment]
It is the fault of `BuildPackages.sh`. If I deliberately break the profiling package and then call
```
../bin/BuildPackages.sh --strict profiling* && echo $?
```
from my `pkg` dir, then the final line of output is `0`. Here's the last few lines of output:
```
WARNING: Failed to build profiling

Packages which failed to build are in ./log/fail.log
0
```
Indeed, the `if [[ $STRICT ]]; then exit 1; fi` bit of code occurs immediately after the code that prints the `WARNING:` line, so that error code is only being caught internally; the script then goes on to print the "Packages which failed to build..." line and exit happily.

I'll see if I can fix it.

**Comment by wilfwilson** [comment]
This was introduced in #3922, which (according to my very limited understanding of bash...) put the relevant bit in a subshell whose result was ignored - something like that.
