### ISSUE TITLE
`SetIsSSortedList( list, false )`

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#4459]
The following (in the released version of GAP as well as in the master branch) is a bit irritating.
```
gap> l:= [ 1, 3, 2 ];
[ 1, 3, 2 ]
gap> HasIsSSortedList( l );
false
gap> SetIsSSortedList( l, false );
gap> HasIsSSortedList( l );
false
gap> IsSSortedList( l ); 
false
gap> HasIsSSortedList( l );
true
```
Thus GAP is able to store the knowledge about non-sortedness in the list,
but apparently the user cannot do this.

Note that setting the property to `true` works.
```
gap> l:= [ 1, 3, 5 ];
[ 1, 3, 5 ]
gap> HasIsSSortedList( l );
false
gap> SetIsSSortedList( l, true );
gap> HasIsSSortedList( l );
true
```

**Comment by fingolfin** [comment]
This is because `IsSSortedList` is a kernel property, with special handling for plists (where the sortedness is stored via the TNUM). Kernel properties have custom getters -- but in general no custom setter.

To fix this, one needs to add such a custom setter. Say by adding a kernel function which changes the TNUM suitably, by calling `SET_FILT_LIST( list, FN_IS_NSORT );` resp. `SET_FILT_LIST( list, FN_IS_SSORT );`; and the installing this as a method for `SetIsSSortedList`. But this would suffer from method selection overhead; so perhaps instead the code handling kernel properties (BTW there are just two of those right now) ought to be extended to allow (require?) specifying *two* handlers, one for the getter and one for the setter.
