### ISSUE TITLE
Add an option to Test to print the elapsed time (in ms)

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/gap#446]
While GAPstones are lovely, it would be really nice to have `Test` print the elapsed time in a more standard unit of time (such as, for example, milliseconds). I might go as far as suggesting that this be the default printed value.

**Comment by alex-konovalov** [comment]
If this is concerning the following usage of `Test`
```
gap> Test("algmat.tst");
algmat.tst
GAP4stones: 11818
true
```
then it is actually `STOP_TEST` that prints `GAP4stones`, not `Test`.

**Comment by james-d-mitchell** [comment]
Right, it is, but the option/default value should be set by `Test`.

**Comment by alex-konovalov** [comment]
@james-d-mitchell Ok, I've probably misinterpreted this because of the prior discussion. So the suggestion is not to modify STOP_TEST at all - your suggestion is to modify `Test` so that it could print timings just for any test, whenever START/STOP_TEST is used in the test file or not.

I like the idea of making this default option - in the situations when we display these data otherwise (e.g. with `TestDirectory`) it may be switched off, and while it will impact packages using `Test`, it will not make their tests failing.

However, I think we could/should do even better. Look at https://github.com/gap-system/gap/issues/305 - if we will make `Test` optionally returning the result e.g. of the form `rec(result:=true, runttime:=4456456)` then it can be used further up by `TestDirectory` etc., and this will help us to track runtime regressions.

**Comment by frankluebeck** [comment]
I don't agree that `TEST` should print additional timing information by default (many tests are so short that this is no useful information).

But it would be easy to add some option to print or return overall timing information for a test file (calling Runtimes() at the beginning and end and computing differences). 

Note that it is already possible to detect fine grained runtime regressions using the components `.writeTimings` and `.compareTimings` in the optional options record.

**Comment by james-d-mitchell** [comment]
I'd be happy with what you suggest @frankluebeck, if we also add an option to *not* display the usual `GAPstones:` line. For me at least, this line just clutters the screen and doesn't contain useful information.

**Comment by frankluebeck** [comment]
By default `Test` prints nothing if a test was successful (just return `true`).

The `GAPstones:` line is written by the `START_TEST` and `STOP_TEST` lines (see the documentation). How about a new convention that `STOP_TEST`  does not print a `GAPstones:` line if its second argument is 0?

**Comment by james-d-mitchell** [comment]
@frankluebeck sounds good to me.

**Comment by fingolfin** [comment]
GAPStones were removed some time ago, and we now indeed print times in milliseconds.
