### ISSUE TITLE
One(A) exists does not imply that IsAlgebraWithOne(A)? 

### ISSUE THREAD

**Issue by cdwensley** [gap-system/gap#4498]
### Observed behaviour
```
gap> F := GF(2);; 
gap> one := One(F);;
gap> z := Zero(F);;
gap> m := [ [ z, one ], [ one, z ] ];
[ [ 0*Z(2), Z(2)^0 ], [ Z(2)^0, 0*Z(2) ] ]
gap> A := Algebra( F, [m] );
<algebra over GF(2), with 1 generators>
gap> One( A ) = m^2; 
true
gap> IsAlgebraWithOne( A );
false
```
### Expected behaviour
```
gap> IsAlgebraWithOne( A );
true
```

### Copy and paste GAP banner (to tell us about your setup)
```
Christopher-Wensleys-iMac:xmodalg christopherwensley$ ../../4r11.sh 
 ┌───────┐   GAP 4.11.1 of 2021-03-02
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin17.7.0-default64-kv7
 Configuration:  gmp 6.1.2, GASMAN
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.1.2, AtlasRep 2.1.0, AutoDoc 2020.08.11, 
             AutPGrp 1.10.2, CRISP 1.4.5, Cryst 4.1.23, CrystCat 1.1.9, 
             CTblLib 1.3.1, FactInt 1.6.3, FGA 1.4.0, GAPDoc 1.6.4, 
             IRREDSOL 1.4.1, LAGUNA 3.9.3, Polenta 1.3.9, Polycyclic 2.16, 
             PrimGrp 3.4.1, RadiRoot 2.8, ResClasses 4.7.2, SmallGrp 1.4.2, 
             Sophus 1.24, SpinSym 1.5.2, TomLib 1.2.9, TransGrp 3.0, 
             utils 0.69
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by cdwensley** [comment]
Maybe this is the intended behaviour, but it looks odd.  (I'm trying to learn about algebras in GAP.)

**Comment by fingolfin** [comment]
This is intentional. The ring Z can be both considered as a ring ("ring-with-one", and a "rng" (ring with or without one), i.e., as object in either of these two (mathematical) categories. But the categories are different, e.g. they have different morphisms.

I agree the modelling of this is problematic in GAP -- mostly because GAP IMHO uses the `IsFOO` terminology for far too many distinct concepts: it can mean a "property" which is discoverable at run time (e.g. `IsSolvableGroup`) but also a "category" (now in the GAP sense, not the mathematical one) which is fixed and burned into the object (such as `IsPermGroup` or, here, `IsAlgebraWithOne`). In general it is not possible to decide based on just the name which it is (quick, make a guess for `IsEuclideanRing` and another for `IsIntegralRing` -- which one is a property and which one is a category?

At this point, though, we are stuck with this naming scheme, so I don't think there is anything to be done about this issue.

**Comment by cdwensley** [comment]
Thanks for this clear explanation.  I must remember to look more closely in the manual before raising an issue - I should have noticed that IsAlgebraWithOne is a category. 
However, in 62.8.4 of the Reference Manual it says: "An algebra-with-one in GAP is a ring-with-one that is also a left vector space. Note that this means that being an algebra-with-one is not a property a ring-with-one can get, since a ring-with-one is usually not represented as an external left set.", but A above is not a ring-with-one either.  Might one add something like "An algebra created with the Algebra operation cannot have this property either, even if it has a one.", or is that wrong?
