### ISSUE TITLE
Rename ErrorMayQuit to e.g. ErrorNoReturn

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#470]
I find the name of the GAP-level function `ErrorMayQuit` very confusing. If `Error` was called `ErrorMayQuitOrReturn`, I would understand it. But as it is, the name suggests to me that this is `Error`, but in addition "it may quit", which is not at all what this is about. Something like `ErrorNoReturn` or `ErrorMayNotReturn` would make more sense to me.

So, how about renaming it? There probably is not yet any (or at least not much) code outside of the library using `ErrorMayQuit`, is there? Even if, we can simply keep `ErrorMayQuit` as an undocumented alias (but I'd prefer if we didn't have to do that).

**Comment by ChrisJefferson** [comment]
I added the GAP-level function, and I hate the name too.

It originally had that name because it behaves like the much-used kernel function `ErrorMayQuit`, but I think in the interests of better names, we should rename it (particularly because I hope to see many uses of `Error` replaced, so it should appear in many places in the library).

**Comment by fingolfin** [comment]
I totally understand your motiviation and why it got that name -- and I also did not complain back then. It just hit me yesterday that this is a bad thing.

If there are no objections, perhaps we can rename it today. Does `ErrorNoReturn` sound OK to everybody?

**Comment by ChrisJefferson** [comment]
I much prefer ErrorNoReturn. I would leave an (undocumented) alias to ErrorMayQuit, just because I believe some packages already use it.

**Comment by alex-konovalov** [comment]
In GAP 4.8.1 (2nd beta of GAP 4.8), `ErrorMayQuit` is used by PolymakeInterface, json, linboxing, profiling and semigroups packages.

**Comment by fingolfin** [comment]
Actually, the matches in PolymakeInterface, json, linboxing are in the C code, phew :-). It seems only profiling and semigroups use them on the GAP level -- but I am sure @ChrisJefferson and @james-d-mitchell are willing to change that, if requested :)

**Comment by james-d-mitchell** [comment]
I can make these changes, no problem. 

On a related note, I'd really prefer to have an analogue of `ErrorQuit` which doesn't enter the break loop at all, since entering the break loop and only allowing `quit;` is not that useful (in my opinion).  Is there any prospect of having `ErrorQuit`?

**Comment by ChrisJefferson** [comment]
Certainly, with a nicer name, perhaps `ErrorNoBreakLoop`?

**Comment by stevelinton** [comment]
I am a bit uncomfortable with ErrorNoBreakLoop, because the break loop can be a very useful debugging tool for experts. Even if you think there is nothing to be learned by looking at local variables in your code, it may be useful to see why strange values were being passed TO your code by calling routines.

What might be better is to offer a cleaner and better documented way of letting the user specify how interested they are in entering break loops (roughly how expert they are, but also whether they are debugging or just running code).

**Comment by fingolfin** [comment]
I share @stevelinton's concern regarding `ErrorNoBreakLoop`. Contraty to @james-d-mitchell I think that being able to inspect local state on the break loop is *extremely* helpful, and I wouldn't want package authors to force down my throat whether I am allowed to do that or not -- so I'd most certainly would end up running a patched GAP version, which changes `ErrorNoBreakLoop` back to the usual `Error` :-)

**Comment by fingolfin** [comment]
The `profiling` package already replaced `ErrorMayQuit`, so only `semigroups` stil needs to be changed before this issue can be closed. I just opened a PR for that, see https://bitbucket.org/james-d-mitchell/semigroups/pull-requests/6/replace-errormayquit-by-errornoreturn/diff

**Comment by alex-konovalov** [comment]
@james-d-mitchell Does Semigroups 2.7.2 (28/01/2016) include the requested change? If so, may we merge this PR for GAP 4.8.2 then?

**Comment by james-d-mitchell** [comment]
Yes it does please go ahead with the merge

**Comment by fingolfin** [comment]
Actually, this isn't a PR, but I did open just now, #572

**Comment by alex-konovalov** [comment]
I've merged #572 and the change is now in `stable-4.8` branch as well.
