### ISSUE TITLE
Matrices over large finite fields

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#4716]
When running the Dixon-Schneider algorithm for character tables of larger groups (which uses matrices over GF(q), q prime but >2^16, these matrices are represented as lists) I noted that matrix arithmetic over larger finite fileds (when the matrix must be represented as lists of lists) gets very slow.

a) Is there already a workaround through the newer Matrix objects, which I ought to adapt?

b) If not, is it worth integrating into the library private code I have for matrices of ZModnZ objects? Or Is something else planned?

**Comment by ThomasBreuer** [comment]
If I understand the request right then we need a `MatrixObj` based implementation of matrices over large prime fields, such that the functions needed in the Dixon-Schneider context are applicable. This means that we need `NullspaceMat`, `MinimalPolynomial`, and so on, for these matrices.
However, we do not need (for the moment) groups or algebras of such matrices.

Such an implementation can be done along the lines of `lib/matobjplist.gi`.
We can store integers (mod p) in the matrices, and fetching an entry yields an `IsFFE` (and `IsZmodpZObj` if p is large).

Alternatively, we can use the interface from GAP to Julia, and work with the matrices over prime fields that are provided by the Nemo system.

In any case, a first step in order to use `MatrixObj` based matrices in the Dixon-Schneider functions will be to change the syntax of the GAP code to be "`MatrixObj` friendly", in the sense that access to rows of matrices is avoided where possible; in particular, entries of a matrix `M` should be accessed as `M[i,j]` not as `M[i][j]`.

**Comment by fingolfin** [comment]
For performance it might also be useful to look at the code and see if parts of it could benefit from using the elementary row/column operation APIs we added recently, such as `SwapMatrixRows`,  `AddMatrixColumns`, `MultMatrixRow`, etc.

**Comment by hulpke** [comment]
Thank you for your responses. I take from this that indeed the plan is to have `MatrixObj` be the representation for such matrices. 

Can I assume that the interface defined in `lib/matobj{1,2}.gd` is going to stay stable?

Obviously I don't mind if Julia, or Nemo, implements a better variant, but my main interest is to have an implementation in the GAP library soon, even if it is not an optimal. (It will be hard to be worse than the current lists of list of objects.)
Would it make sense for me to write a basic implementation in the library (even if it does not implement everything), and to change other code to then use these matrix objects?

Thanks!

  Alexander

**Comment by fingolfin** [comment]
The interface is in principle stable, modulo that we need people to implement it and then adapt code to use, and doing so may reveal issues in the interface, which we then need to address. In other words: if you start using it (great!) and find something problematic, then we would want to be able to adjust things.

But of course we hope the need for this is minimal (other than perhaps wanting to *add* further interfaces; but here the goal is to provide default implementations whenever possible).

So, yes, would absolutely make sense to provide a `ZmodnZMatrixObj` type (or whatever you might want to call it), and start using it. I would like to encourage active communication for us, so that if you run into issues with the documentation, implementation or interface, we can rectify them quickly (instead of frustration building up).

Thanks!

**Comment by hulpke** [comment]
Thank you.

First obstacle: Why is a `MatrixObj` not `IsMatrix?. (This way none of the Gaussian algorithm routines apply.)

**Comment by fingolfin** [comment]
Because `IsMatrix` is just a synonym for this beauty: `<Category "(((CategoryCollections(CategoryCollections(IsNearAdditiveElementWithInverse)) \
and CategoryCollections(CategoryCollections(IsAdditiveElement))) and IsTable) and (Catego\
ryCollections(CategoryCollections(IsMultiplicativeElement)) and IsTable))">`

In particular, `IsMatrix` implies "this is a list of lists", and we don't want that for matrix objects. 

But often code that was written for `IsMatrix` works for `IsMatrixObj`; when it comes to method installations, one can often simply replace `IsMatrix` by `IsMatrixOrMatrixObj` to have it work for both kinds of matrices.

**Comment by fingolfin** [comment]
Also, existing Gaussian algorithms often abuse that one can write `mat[i]` to access a row of a matrix. That makes sense for matrix types which are implemented as lists of row, but already for compressed matrices over GF2, that's a major burden, as it precludes all kinds of optimizations.

This is why we added `SwapMatrixRows`, `AddMatrixColumns`, `MultMatrixRow` etc. so that such code can be rewritten to work in both situations.

**Comment by hulpke** [comment]
Thanks. So, would it make sense to change the installations of the methods for matrix triangulization &c. to `IsMatrixOrMatrixObj` to at least have a basic implementation, even if it might not be optimal?

Or should this be file with temporary double installations of the existing methods for matrix objects?

Otherwise we have a bootstrap problem, that lots of algorithms cannot use the matrix objects, since the fundamental routines are missing.
