### ISSUE TITLE
LatticeSubgroups gives wrong result for SL

### ISSUE THREAD

**Issue by laurentbartholdi** [gap-system/gap#4717]
```
gap> g := SL(2,3);
SL(2,3)
gap> hom := NiceMonomorphism(g);
<action isomorphism>
gap> Size(g); Size(Image(hom));
24
48
```

So it seems that hom maps to `GL(2,3)`, and believes that it is surjective. I haven't investigated when this bug occurred, and where exactly it happens. This is on master, GAP 4.12dev-1062-g401c797.

**Comment by fingolfin** [comment]
Nothing is wrong here. From the documentation of `NiceMonomorphism`:
> `NiceMonomorphism( obj )` is  a homomorphism that is defined (at least) on the whole of `obj` and whose restriction to `obj` is injective.

Note in particular:
```
gap> Size(Image(hom,g));
24
```

The output you observe has been like this since at least GAP 4.10

**Comment by laurentbartholdi** [comment]
But `Image(hom)` should be the image of `hom`, right?

In all cases, this bug causes erroneous results in `LatticeSubgroups`:

```gap> g := SL(2,3);;
gap> List(ConjugacyClassesSubgroups(g),x->IsSubgroup(g,Representative(x)));
[ true, true, false, true, true, false, true, false, false, true, false, false, false, false, true, false ]
```
so I'm reopening the bug report.

**Comment by fingolfin** [comment]
Sure, and it is the image. It's just that the domain is larger than g. So the image of hom is not necessarily  the image of the group g, and the docs don't claim that. Use NiceObject or Image(hom,g) to get that.

if LatticeSubgroups makes wrong assumptions then that's a bug in there

**Comment by laurentbartholdi** [comment]
Sure enough,
```
gap> Print(ApplicableMethod(LatticeSubgroups,[g]));
function ( G )
    local hom, lattice, classes;
    hom := NiceMonomorphism( G );
    lattice := LatticeSubgroups( Image( hom ) );
...
```
but does GAP really want to trip all good-faith users of `NiceMonomorphism` into that kind of bug? It sounds sadistic. I don't see any overhead it having `NiceMonomorphism` return an object with domain `g`.

**Comment by fingolfin** [comment]
This is a low level operation that behaves exactly as documented. I don't see what is "sadistic" about that?

Restricting the domain of the morphism is not free, depending on which morphism implementation is used it can  affect every single application of the monomorphism which is undesirable. Nice monomorphisms are also generally inherited when forming subgroups; again, creating the restriction would incur a nontrivial cost, which in GAP is relatively high. If this was Julia or C/C++, the balance would be different. I am reluctant to make a change that could slow down lots of computations.

I'd be happy to add a sentence stressing this possibility and pointing to NiceObject (which should be used instead of `Image(NiceMonomorphism(g),g)`

**Comment by laurentbartholdi** [comment]
Certainly an argument against it is that it is used wrongly in the library, at least, in
/usr/local/src/gap/lib/grpramat.gi:254 and /usr/local/src/gap/lib/grplatt.gi:1260 (by a quick grep). These are trivial to fix (just add the group as 2nd argument), but I'm sure you see the potential for other bugs -- and the worst kind, silently returning the wrong result.

I understand the performance argument; but perhaps there could be a type `RestrictionOfHomomorphism` that would wrap  the monomorphism into a mapping restricted to `g`?
