### ISSUE TITLE
problem with homomorphisms between trivial groups

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#4737]
(This problem had been observed in oscar-system/Oscar.jl/issues/980.)
The following happens in the master branch.

```
gap> F:= FreeGroup( 1 );;
gap> G:= F / [ F.1 ];;
gap> IsFinite( G );;  # without this, we get an error already in the following call
gap> pres:= ConfluentMonoidPresentationForGroup( G );;
gap> map:= pres.fphom;;
gap> G.1 in PreImage( map );
true
gap> ImagesRepresentative( map, G.1 );
Error, Record Element: '<rec>.wholeGroup' must have an assigned value in
  FamilyObj( mapi[1] ) at /.../gap/lib/ghomfp.gi:218 called from
CosetTableFpHom( hom ) at /.../gap/lib/ghomfp.gi:249 called from
<function "ImagesRepresentative map from (sub)fp group, rewrite">( <arguments>\
 )
 called from read-eval loop at *stdin*:7
type 'quit;' to quit to outer loop
brk>
```

The problem with the `FamilyObj` call is due to the fact that `mapi[1]` is an empty list and thus does not know about groups. However, I think that it is already a problem that we enter `CosetTableFpHom`.

(The function `ConfluentMonoidPresentationForGroup` is currently undocumented.)

Essentially the same happens in GAP 4.11.1, the only difference is that `pres`is not a record but a list in this case, we have to set `map:= pres[1];`.

**Comment by fingolfin** [comment]
I wanted to see if this is due to how `ConfluentMonoidPresentationForGroup` creates the morphism, or if we can trigger it some other way. That lead me to look at the `ConfluentMonoidPresentationForGroup` method in `gpfpiso.gi`, lines 1081ff; there we find the line:
```
iso:=IsomorphismFpGroupByChiefSeries(G:rewrite);
```
However `IsomorphismFpGroupByChiefSeries` actually requires two arguments so it seems that code is untested and not working right now.


Anyway, that's not the relevant code path, as our trivial group is a "symmetric group". So this also reproduces the issue:
```
gap> F:= FreeGroup( 1 );;
gap> G:= F / [ F.1 ];;
gap> i:=SymmetricGroup(SymmetricDegree(G));;
gap> map:=CheapIsomSymAlt(G,i)*IsomorphismFpGroup(i);;
gap> G.1 in PreImage( map );
gap> ImagesRepresentative( map, G.1 );
Error, Record Element: '<rec>.wholeGroup' must have an assigned value in
...
gap> ImagesRepresentative( CheapIsomSymAlt(G,i), G.1 );
Error, Record Element: '<rec>.wholeGroup' must have an assigned value in
...
```
Actually `CheapIsomSymAlt ` delegates to `IsomorphismGroups`, which in this case just invokes `GroupHomomorphismByImagesNC`. So all in all:


```
gap> F:= FreeGroup( 1 );;
gap> G:= F / [ F.1 ];;
gap> H:=TrivialGroup(IsPermGroup);;
gap> map := GroupHomomorphismByImagesNC(G,H,[],[]);;
gap> ImagesRepresentative( map, G.1 );
Error, Record Element: '<rec>.wholeGroup' must have an assigned value in
gap> i:=SymmetricGroup(SymmetricDegree(G));;
gap> map:=CheapIsomSymAlt(G,i)*IsomorphismFpGroup(i);;
gap> G.1 in PreImage( map );
gap> ImagesRepresentative( map, G.1 );
Error, Record Element: '<rec>.wholeGroup' must have an assigned value in
```

The error is raised by this method in `ghomfp.gi`, which starts out by invoking `CosetTableFpHom` but perhaps it should have a special case where the source and/or range of the homomorphism is trivial?
```
InstallMethod( ImagesRepresentative, "map from (sub)fp group, rewrite",
  FamSourceEqFamElm, 
  [ IsFromFpGroupGeneralMappingByImages and IsGroupGeneralMappingByImages,
    IsMultiplicativeElementWithInverse ], 0,
function( hom, word )
local aug,si,r,i,j,tt,ct,cft,c,f,g,ind,e,eval;
  # get a coset table
  aug:=CosetTableFpHom(hom);
  r:=One(Range(hom));
...
```



CC @hulpke

**Comment by hulpke** [comment]
This has nothing to do with `ConfluentPresentation`, but with the fact that it is the trivial fp group with empty generating set.
