### ISSUE TITLE
CanComputeSize does not know properly when it can compute Size

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-system/gap#485]
This is probably not a bug, nevertheless I was wondering about the following: 

````
gap> G := DihedralGroup(IsFpGroup,60);
<fp group of size 60 on the generators [ r, s ]>
gap> CanComputeSize(G);
true
gap> S[2] := NormalClosure(G, SylowSubgroup(G, 2));
Group(<fp, no generators known>)
gap> CanComputeSize(S[2]);
false
gap> Size(S[2]);
60
````

I use this in my NormalHallSubgroups algorithm, and currently I exit with ````TryNextMethod();```` when ````CanComputeSize```` returns false. However, as the current situation shows, ````CanComputeSize```` is not always accurate. 

Is there a way to know better when a ````Size```` computation can be done? E.g. if ````CanComputeSize```` returns false, then still try to run ````Size````, and if it errors to a ```No method found``` then return to a sane state (automatically, not manually) and try another method not using the ````Size````?

**Comment by stevelinton** [comment]
Some care is needed -- there may be methods which only sometimes return a result and otherwise run forever. In general if an object does NOT have a filter you should be wary of reading too much into that. 

That said, there are various mechanisms that pass information between groups and subgroups, and I suspect that, in this case, an inference might be missing, since I think S[2] as a subgroup of a group with known size should probably acquire CanComputeSize.

**Comment by hungaborhorvath** [comment]
Ah, I think I see what happens here. Since I define the group with its size, it already knows the size and therefore it has ````CanComputeSize````, as well. However (maybe for all fp-groups?), the ````CanComputeSizeAnySubgroup```` returns ````false```` here, and probably that means that all subgroups will have ````CanComputeSize=false````, as well. Maybe except for the Sylow subgroups, for which it (again) knows the size from elsewhere. 

Interesting, though, that ````Size```` returns a value, and in fact in a rather short period of time. Maybe it would be worth to look at when is ````CanComputeSize```` and ````CanComputeSizeAnySubgroup```` defined to be ````true```` or ````false````, and if GAP already has some methods in the library for some of the situations, then update these filters.

**Comment by stevelinton** [comment]
Having poked at this a little, I wonder if a fp group which is finite and knows its size should have CanComputeSizeAnySubgroup? In principle it certainly can, although it might be slow or difficult.

Another question is whether we should expand the documentation to indicate, in particular, that CanComputeSize(d) = false does not imply that Size will fail.

**Comment by hulpke** [comment]
The `Can...` functions are there to guide the method selection away from potentially extremely hard tasks -- they are not intended to indicate absolute computability.

`CanComputeSizeAnySubgroup` is used e.g. in orbit algorithms to indicate whether the size of a (potentially only partial) stabilizer might be use as stopping criterion against orbit length and group order. If the group is a permutation group that is fine. If it is a matrix group over Q that does not yet have a nice monomorphism this is not the case.

The reason for `CanComputeSizeAnySubgroup` is because `HasSize` implies `CanComputeSize`, but (e.g. if I write Y555 as an fp group) a groups size might be set without any possibility to work out orders of most subgroups.

While the definitions might be inelegant, the current setup seems to work OK, and adding implications risks that some calculations will run in unnecessarily hard subgroup order computations. I therefore recommend to not add implications.

**Comment by stevelinton** [comment]
I have committed a small documentation clarification.

**Comment by hulpke** [comment]
> Having poked at this a little, I wonder if a fp group which is finite and knows its size should have CanComputeSizeAnySubgroup? In principle it certainly can, although it might be slow or difficult.

At the moment `CanComputeSizeAnySubgroup is used to indicate whether a subgroup order computation is notably faster than a coset orbit. That might mean the name of this filter was badly chosen (and I’d be happy to rename it), but this would speak against permitting this for fp groups (unless a faithful representation has been found).

Is there any problem (apart from documentation) with the current setup?

Alexander

**Comment by stevelinton** [comment]
I;ve fixed the documentation and closed the issue.
