### ISSUE TITLE
Iterating over permutation group elements.

### ISSUE THREAD

**Issue by MathieuDutSik** [gap-system/gap#4858]
I coded in [permutalib](https://github.com/MathieuDutSik/permutalib) the iteration over a permutation group elements. It turns out to be 100 times faster than GAP (for example for M23), which is not what I expected

Looking into the code of GAP I realize that the issue is that the routine **NumberElement_PermGroup** actually is suboptimal. It takes a number and returns a group element. But what we need when iterating is something else: When enumerating, what we actually need is to go from one element to the next (or fail).

That is if a permutation group has a stabilizer sequence of N stabilizers then we have to store N elements. When incrementing only a part of the N elements are changed and this is better than the existing code that consider all the stabilizers when computing.

The problem is that this change would not have a small impact on the code:
1) The existing code with EnumeratorByFunctions has ElementNumber / NumberElement which are obviously more
powerful than the proposed faster API.

2) The typical use case that I have in mind is
for eElt in GRP
do
.....
od;
where we do not need ElementNumber/NumberElement. What is the use case where we absolutely need to have
a NumberElement/ElementNumber ?

3) What we need instead of ElementNumber/NumberElement is something like FirstElement and a function NextElement
that goes to the next element or returns fail.

4) Another potential issue is that the list of elements in the loop "for eElt in GRP do .... od;" would be different
in the new code.

Therefore, I would like your input on this issue before proposing any PR.

**Comment by MathieuDutSik** [comment]
Thank you. I will check.

**Comment by fingolfin** [comment]
@ChrisJefferson is of course 100% correct. And indeed, GAP *does* have an iterator for permutation groups, see https://github.com/gap-system/gap/blob/017ec14e853a683e25cda896bdf97b946c64d692/lib/grpperm.gi#L650-L655 which calls https://github.com/gap-system/gap/blob/017ec14e853a683e25cda896bdf97b946c64d692/lib/stbc.gi#L1818-L1843


When one does `for g in G do ... od;` then it should actually be using this iterator.

**Comment by fingolfin** [comment]
Of course it may very well possible that this iterator in turn could be improved. To be honest, it may be possible that not much time was invested to tune it because this is not generally a feasible or useful operation for most large permutation groups; and usually there are much better methods than iterating over all elements (e.g. instead iterating over all conjugacy classes, etc.).

Also, the GAP iterator is of course implemented in pure GAP, while that in permlib is optimized C++. That could easily result in noticeable difference in performance, though a factor 100 indeed seems surprising to me.

@MathieuDutSik could you clarify what exactly you did to "iterate over all elements"? I.e. what GAP code did you use, what permlib code, and what are your exact timings ? That would help to compare it locally with some alternatives

**Comment by fingolfin** [comment]
Just for reference, these are some timings on my laptop:
```
gap> G:=MathieuGroup(21);;l:=[];;for g in G do Add(l,g); od; time;
21
gap> G:=MathieuGroup(22);;l:=[];;for g in G do Add(l,g); od; time;
314
gap> G:=MathieuGroup(23);;l:=[];;for g in G do Add(l,g); od; time;
7263
```

**Comment by MathieuDutSik** [comment]
> G:=MathieuGroup(21);;l:=[];;for g in G do Add(l,g); od; time;

Ok, my timings were incorrect. Sorry about that.
