### ISSUE TITLE
It's possible to construct integer matrices that are not matrices

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/gap#4885]
As the title suggests, it's possible to create matrices over the integers, which are non-rectangular (i.e. not matrices), which think they are:

### Observed behaviour
~~~
gap> Matrix(Integers, [[1, 1], [2]]);
<2x2-matrix over Integers>
gap> Display(last);
<2x2-matrix over Integers:
[[ 1, 1 ]
 [ 2 ]
]>
gap> x[2, 2] := 4;
4
gap> Display(x);
<2x2-matrix over Integers:
[[ 1, 1 ]
 [ 2, 4 ]
]>
gap> x[2, 5] := 0;
0
gap> x;
<2x2-matrix over Integers>
gap> Display(x);
<2x2-matrix over Integers:
[[ 1, 1 ]
 [ 2, 4,,, 0 ]
]>
gap>
~~~
### Expected behaviour

~~~
gap> Matrix(Integers, [[1, 1], [2]]);
Error,
~~~

Perhaps this is the intended behaviour, but at the very least the following should probably occur.
~~~
gap> x[2, 5] := 0;
Error,
~~~

**Comment by fingolfin** [comment]
These are indeed both bugs.

The assignment one should be relatively easy to fix. For the inversion bug, we should of course also fix it, but I am slightly concerned about performance; ideally, the function computing the inverse would already produce the error as soon as it computes a non-integer result. But right now, we'll compute the inverse by calling another GAP function, and then at the end we'll have to scan all entries to see if any is non-integer. That's annoyingly expensive... Then again, I think it is likely our inversion code is non-optimal for large integer matrices anyway, so I am probably "worrying" for nothing. Anyway, we should first make it correct, and then later can tune it as needed.

But before anybody delves too deeply into the `IsPlistMatrixRep` code to fix these, it would be great if my ancient PR #2973 was at least superficially reviewed and then merged, so that that work does not go to waste.
