### ISSUE TITLE
Out of date package documentation links

### ISSUE THREAD

**Issue by lhsoicher** [gap-system/gap#5017]
Unfortunately, the links on the GAP website to the documentation for the GRAPE, FinInG and probably other packages included with GAP 4.12.0, are not for the included versions of these packages. See, for example, the documentation links at 
https://www.gap-system.org/Packages/fining.html

**Comment by fingolfin** [comment]
Unfortunately I forgot that updating the package documentation on the server is no yet automatic. Also redirects need to be manually set up...

I am on vacation right now, so not much I can do about this in the next two weeks though I could give e.g. @ChrisJefferson SSH access to the new server before that.

A bunch of things we should do result from this issue:
- fix the immediate problem, of course 
- Automate this part of the release, too, to avoid it long term; or at least take measures to ensure it is not forgotten next time
- Set up a process/script/GH workflow to monitor validity of links on our website so that we catch issues like this in the future. This could be run as a CI jobs for PRs, but also as a daily cron job
- ensure more trusted people have SSH access to the server and know how it works / where everything is (by adding/improving documentation)

**Comment by fingolfin** [comment]
All fixed now
