### ISSUE TITLE
GAP 4.12.0 doesn't seem to export the location of its copy of GMP

### ISSUE THREAD

**Issue by RussWoodroofe** [gap-system/gap#5072]
### Observed behaviour
sysinfo.gap is used to specify information about GAP, including ```CPPFLAGS``` and ```LDFLAGS``` to find the libraries needed.  GMP is one of these libraries, but when building GAP with default settings (including built-in GMP), the directory extern/install/gmp/{include,lib} does not make it into the list(s).

This causes problems with building packages, including the float package.  In particular, if you download and try to follow our instructions, then a central and easy-to-build package fails.

### Expected behaviour
It would be helpful and sensible for GAP to export the location of its GMP, as many packages depend on it.

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.12.0 of 2022-08-18
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin18-default64-kv8
 Configuration:  gmp 6.2.1, GASMAN, readline
 Loading the library and packages ...
 Loading gaprc.
 Packages:   AClib 1.3.2, Alnuth 3.2.1, AtlasRep 2.1.4, AutoDoc 2022.07.10, 
             AutPGrp 1.11, Browse 1.8.14, CaratInterface 2.3.4, CRISP 1.4.5, 
             Cryst 4.1.25, CrystCat 1.1.10, CTblLib 1.3.4, FactInt 1.6.3, 
             FGA 1.4.0, Forms 1.2.8, GAPDoc 1.6.6, genss 1.6.7, IO 4.7.2, 
             IRREDSOL 1.4.3, LAGUNA 3.9.5, orb 4.8.5, Polenta 1.3.10, 
             Polycyclic 2.16, PrimGrp 3.4.2, RadiRoot 2.9, recog 1.3.2, 
             ResClasses 4.7.3, SmallGrp 1.5, Sophus 1.27, SpinSym 1.5.2, 
             TomLib 1.2.9, TransGrp 3.6.3, utils 0.76
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'

```

Best,
Russ

**Comment by fingolfin** [comment]
Yes, this was a deliberate change, to avoid all kinds of problems "exporting" the GMP built by GAP had. In general, the best solution is to not use that anyway, but rather to use a systemwide installation of GMP.

A major problem was that GAP hardcoded the paths to GMP in `sysinfo.gap`, but that caused major problems when GAP was being packaged for Linux distros: because then trying to compile GAP packages from source against such a GAP often failed, even (or perhaps: in particular) if those packages don't use GMP: because they were still told to look for C headers in that location, but that usually did not exist on those systems, resulting in weird errors (we have closed issues on this here and on various package repositories).

In a sense, this reason is (hopefully) less relevant or perhaps irrelevant, thanks to `make install` which installs a custom `sysinfo.gap` -- so we could have those paths in CPPFLAGS/LDFLAGS when GAP is built from source, but drop them when GAP is installed. However, I am not sure how many Linux distros will switch to using `make install` and when...

Another issue is that the location of "its GMP" is not always clear: it is if we build the bundled version; it may also be when the user uses `--with-gmp=PREFIX`; but the user can also specify this by passing arbitrary CPPFLAGS etc while building. So then we end up in a situation where *sometimes* we can tell packages where to find GMP, but we won't be able to do that always and reliably.


(BTW, I think `float` is not the best example in so far as (a) it is IMHO not central at all (non-machine-floating point is hardly a core feature for most computational group theory research) and (b) it actually also requires `mpfr` or `mpc` etc. -- without those, and just GMP, it is useless. But if one manages to install one of these anyway (and they all also need GMP!) then surely taking care of GMP is not a problem?


That is not to dispute that there is room for improvement here; just that I don't think this is the best example :-). So, let's see, which packages actually use `gmp.h`:

1. anupq
1. digraphs (via bliss)
1. caratinterface
1. cddinterface
1. float
1. grape (via nauty)
1. nq
1. normalizinterface -> this one also need to build normaliz

**Comment by fingolfin** [comment]
We could export a variabel `GMP_PREFIX` in `sysinfo.gap` but as you say it would need adjustment in the various packages to actually use it.

BTW for the packages in the list that don't build a kernel extension (anupq, grape, nq) this might also offer a chance to simplify their build system, by dropping use of the `FIND_GAP` m4 macro -- those packages don't really need GAP to build, they just ask for the location of GAP to determine the GAParch and possibly info about where to find GMP. But for this one only needs sysinfo.gap.

**Comment by fingolfin** [comment]
@RussWoodroofe have a look at PR #5079

**Comment by RussWoodroofe** [comment]
The PR looks generally sensible to me.  I like that it documents the circumstance under which GMP_PREFIX will be empty.  I'm not exactly sure what should happen under the "make install" situation (it seems possible that there may be some unforeseen consequences).  Since "make install" is not yet a going concern, this seems academic for now.
