### ISSUE TITLE
More questions about `ConvertToMatrixRep`, `ConvertToVectorRep` and their `NC` variants

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#5081]
I just had to debug code involving these functions, and while I found a solution, I was left with a bunch of questions. The documentation for them is a bit sparse perhaps...

First off, the return values. The manual says this for `ConvertToVectorRep` and it is similar for matrices:
> The return value is the size of the field over which the vector ends up written, if it is written in a compressed representation

But what is supposed to happen if a conversion is not possible?
- for `ConvertToMatrixRep` and its NC variant, it seems we get `fail`:

      gap> ConvertToMatrixRep([[1,2,3]]);
      fail
      gap> ConvertToMatrixRepNC([[1,2,3]]);
      fail

- for `ConvertToVectorRep` and its NC variant, it seems we get `true` (which I find quite surprising):

      gap> ConvertToVectorRep([1,2,3]);
      true
      gap> ConvertToVectorRepNC([1,2,3]);
      true

- with `ConvertToMatrixRepNC` we also can get an error -- I kinda think this is a bug? This is the initial issue I run into; note that the non-NC variant "works". This error happens because `ConvertToVectorRepNC` "fails"

      gap> ConvertToMatrixRep([[1,2,3]]*Z(17), GF(17^2));
      fail
      gap> ConvertToMatrixRepNC([[1,2,3]]*Z(17), GF(17^2));
      Error, ConvertToMatrixRep: Failed to convert a row

My suggestion would be to return `fail` in all these cases, and document it as such.

CC @ThomasBreuer

**Comment by ThomasBreuer** [comment]
Interesting. `ConvertToVectorRep` seems to return `fail` in *some* situations where the second argument is not valid, like in
```
gap> v:= [ Z(4) ];; ConvertToVectorRep( v, 4 );; ConvertToVectorRep( v, 6 );
fail
```
However, errors happen in other situations with invalid input for `ConvertToVectorRep`, and the documentation warns that anything may happen in such situations:

> It  is  forbidden to call this function unless list is a plain list or a row
> vector,  field  is a field, and all elements of list lie in field. Violation
> of  this  condition  can  lead to unpredictable behaviour or a system crash.

I agree that the documentation does *not* yet define what happens if the given vector cannot be converted, and that changing the code to return `fail` in these cases is no problem.

Concerning `ConvertToMatrixRepNC`, the documentation says that

> The NC versions  of  the  function  do  less checking of the argument and may cause unpredictable  results or crashes if given unsuitable arguments.

One could argue that `GF(17^2)` is an unsuitable argument, but I think that also here returning `fail` is more appropriate than explicitly calling `Error`.

**Comment by fingolfin** [comment]
> One could argue that `GF(17^2)` is an unsuitable argument [...]

The problem with that argument is that then the function becomes utterly useless, as it does not actually specify what suitable arguments *are*. I so far kinda assumed "the vector/matrix must be defined over the specified field", which is the case in my example. I don't think it's reasonable to allow such inputs to cause a crash. We could of course say that fields are only acceptable up to size 256, but that then precludes future extensions.

So yeah, returning `fail` seems like a better solution
