### ISSUE TITLE
'make install' is incomplete: it doesn't install gac, gap binary, packages, and some other files

### ISSUE THREAD

**Issue by yurivict** [gap-system/gap#5099]
In the FreeBSD port we have [this additional line](https://cgit.freebsd.org/ports/tree/math/gap/Makefile#n74) installing packages.

We also [install the gap binary](https://cgit.freebsd.org/ports/tree/math/gap/Makefile#n52).

gac is also not installed by 'make install'.

**Comment by fingolfin** [comment]
Actually `make install` *does* install `gap` and `gac`, see [here](https://github.com/gap-system/gap/blob/master/Makefile.rules#L582-L594) -- and this is also verified by [our CI tests](https://github.com/gap-system/gap/blob/master/dev/ci.sh#L233-L234).

Lucking at the ports file you linked to, it does not actually seem to invoke `make install`; it contains the line
```
INSTALL_TARGET=	install-headers install-libgap
```
so I assume it only invokes those two sub-targets of `make install`... Try changing this to just `install` ? (But beware, the `install-doc` subtarget will fail; this is fixed by PR #5091 which will be in 4.12.1, to be released in about two weeks)


Packages are indeed not (yet?) installed. I hope that this can be addressed in GAP 4.13, but we'll see.

**Comment by yurivict** [comment]
Thank you, I didn't notice before that the 'install' target wasn't used.
Now the port is updated, and the only remaining item is packages.

**Comment by fingolfin** [comment]
Great!

I see that aarch64 and RISC-V are marked as broken. Is that still true? If so it'd be great if you could report details so we can address them.

**Comment by fingolfin** [comment]
It would also be interesting to know what problem that C++20 related patching is fixing? Perhaps we could / should address that on our side?

For packages, you could use the `bin/BuildPackages.sh` script to at least compile all... one trick/hack for installing the packages could be this:
- first copy the package dirs to their final destination 
- then build them in the original dir
- then copy over just the "bin" subdirs of each package for which one was created to the final destination 

that avoids copying *.o files and other temporary artifacts
