### ISSUE TITLE
problem with compressed vectors

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#5123]
The following happens in the GAP master branch as well as in GAP 4.11.1 and GAP 4.12.0.
(Thanks to Bernhard Böhmler for reporting this problem.)
```
gap> v:= [ 0 * Z(2) ];;
gap> ConvertToVectorRep( v, 4 );
4
gap> ConvertToVectorRep( v, 8 );
gap: src/vec8bit.c:544: RewriteVec8Bit: Assertion `!(D_FIELDINFO_8BIT(info) % D_FIELDINFO_8BIT(info1))' failed.
Abort (core dumped)
```
In our situation, the entries of the vector lie in the prime field but are represented w.r.t. the field with four elements, which is not a subfield of the desired field with eight elements.
The GAP function `CONV_VEC8BIT` calls the kernel function `ConvVec8Bit`, which calls the kernel function `RewriteVec8Bit`, and the latter function expects that the field of the result vector contains the field of the given vector.

**Comment by fingolfin** [comment]
I can easily fix the crash and turn it into an error, that'd already be an improvement.

But should it give an error, or should it try to actually *do* something?

**Comment by ThomasBreuer** [comment]
I think that turning the crash into an error is enough on the side of the GAP kernel.
Then I will  provide a pull request for fixing the use of the kernel functions inside `ConvertToVectorRep`.

**Comment by fingolfin** [comment]
Same issue also affects `CopyToVectorRep` / `COPY_VEC8BIT` as it also calls `RewriteVec8Bit`. It is also called from `SUM_VEC8BIT_VEC8BIT`, `ADD_ROWVECTOR_VEC8BITS_5`, `ADD_ROWVECTOR_VEC8BITS_3`, `ADD_ROWVECTOR_VEC8BITS_2`, `DIFF_VEC8BIT_VEC8BIT`, `ASS_VEC8BIT`, ... -- I've not yet tried if I can trigger a segfault in any of them.

What I will do now is to change some assertions in `RewriteVec8Bit` into regular error checks, so that at least there won't be a segfault. When it comes to actually making the conversion work, that we'll have to see
