### ISSUE TITLE
Annoying double-slash in `TestDirectory` output

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#5249]
Recently messages printed by `TestDirectory` started to look like this:
```
/home/runner/gap/pkg/hap-1.47//tst/...
```
Notice the double slash. Not terrible bad, but annoying.

I suspect (but did not check, and thus might be totally wrong) that PR #5178 by @zickgraf could have started this.

If right, then one way to changes this would be to adjust things to be kind of the opposite: instead of ensuring there is *always* a trailing slash, we could ensure there is *never* a trailing slash; I think both are fine as long as we are consistent.

Another fix would be to adjust the `TestDirectory` code specifically to avoid the double slash. But I wonder if there are other places that might be similarly affected...

**Comment by zickgraf** [comment]
> If right, then one way to changes this would be to adjust things to be kind of the opposite: instead of ensuring there is _always_ a trailing slash, we could ensure there is _never_ a trailing slash; I think both are fine as long as we are consistent.

I think having the trailing slash is a good thing because it ensures compatibility with `Directory`, which always adds a trailing slash. So if other places are affected, I think they should simply be changed to use `Directory` and `Filename`, which should be more stable and consistent than handling file paths as strings.
