### ISSUE TITLE
Regression: recent changes caused package `guava` to fail its test suite

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#5334]
[First failing report](https://github.com/gap-system/PackageDistro/blob/data/reports/master/2023-01-12-15:27:16-bb2f35dc/report.md) is from 2023-01-12 at 15:27:16:
```
########> Diff in /home/runner/gap/pkg/guava-3.18/tst/guava.tst:355
# Input is:
WholeSpaceCode( 5, GF(4) ) = WholeSpaceCode( 5, GF(2) );
# Expected output:
false
# But found:
true
########
```

I have bisected the issue to commit 2f4a518d36912392d7102c940873e77b2c076c23 by @ThomasBreuer via PR #3006

**Comment by ThomasBreuer** [comment]
The real problem is a bug in `COEFFS_SEMI_ECH_BASIS`:
```
gap> V:= GF(2)^1;; B:= Basis( V, [ [ Z(2) ] ] );;
gap> Coefficients( B, [ Z(4) ] );
[ Z(2^2) ]
```
The correct result would be `fail`.

This problem shows up now because the changes from #3006 cause that a method for `\in` gets a lower rank, and thus another method (which uses `COEFFS_SEMI_ECH_BASIS`) is called in the computation in question. I will create a pull request in order to fix the bug.
