### ISSUE TITLE
Should packages still list GAPDoc as a needed package?

### ISSUE THREAD

**Issue by stertooy** [gap-system/gap#5411]
At the end of [Section 76.11](https://gap-system.github.io/gap/doc/ref/chap76_mj.html#X7928799186F9B2FE) of the GAP manual, it says:
 >   Finally, if the package manual is in the **GAPDoc** format, then **GAPDoc** should still be listed as _needed_ for this package (not as _suggested_), even though **GAPDoc** is now a needed package for **GAP** itself.

Currently, approximately half the packages with GAPDoc documentation that are distributed with GAP list GAPDoc as a dependency. A few packages list it as suggested, the remainder does not list it anywhere. So: is this guideline in the manual outdated, or is it still valid (just not strictly enforced)?

**Comment by fingolfin** [comment]
Personally I don't see why, but ping @frankluebeck @ThomasBreuer @ChrisJefferson

**Comment by olexandr-konovalov** [comment]
Dependencies on GAPDoc were always messy. All kinds of none/suggested/needed present among packages using GAPDoc to build manuals. It might have been that it was me writing that "needed" should be used, trying to make this uniform across all packages. But now I do think that "needed" should be only in cases when a package uses some of its functionality **at runtime** for non-manual building purposes, like e.g. OpenMath to parse XML.

**Comment by frankluebeck** [comment]
I agree with @olexandr-konovalov: Packages that use some of the utilities in the GAPDoc package (Text processing, unicode, XML parsing, ...) should mention GAPDoc as needed package.
Packages that (for users of the package) only depend on GAPDoc for reading their documentation may leave it out in the list of dependencies (because for this functionality GAP itself has GAPDoc as needed package). On the other hand, it doesn't hurt to list GAPDoc as dependency.

**Comment by fingolfin** [comment]
I made https://github.com/gap-system/gap/pull/5412 to address this.
