### ISSUE TITLE
Userpref test failure

### ISSUE THREAD

**Issue by Feyorsh** [gap-system/gap#5680]
Let me preface this by saying I am not an experienced GAP user; I simply encountered this issue while trying to package Sagemath. If this has already been fixed or is of no concern to the GAP project, please close the issue.

### Observed behaviour
```
testing: /nix/store/0c9vlbrw2kvnsinzmn5zxk32fd3likhx-gap-4.13.0/share/gap/tst/\
testinstall/userpref.tst
########> Diff in /nix/store/0c9vlbrw2kvnsinzmn5zxk32fd3likhx-gap-4.13.0/\
share/gap/tst/testinstall/userpref.tst:7
# Input is:
file:= StringFile( Filename( DirectoriesLibrary( "doc" ),
                                "ref/user_pref_list.xml" ) );;
# Expected output:
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMe\
thodFound
Error, no 1st choice method found for `InputTextFile' on 1 arguments
The 1st argument is 'fail' which might point to an earlier problem

########
```

### Copy and paste GAP banner (to tell us about your setup)
Using the Nix package manager (although not Nix's version of GAP):
```
 ┌───────┐   GAP 4.13.0 of 2024-03-15
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: aarch64-apple-darwin23-default64-kv9
 Configuration:  gmp 6.3.0, GASMAN, readline
 Loading the library and packages ...
 Packages:   Alnuth 3.2.1, AtlasRep 2.1.8, AutPGrp 1.11, CRISP 1.4.6, CTblLib 1.3.9, FactInt 1.6.3, FGA 1.5.0, GAPDoc 1.6.7, IO 4.8.2, IRREDSOL 1.4.4, 
             LAGUNA 3.9.6, Polenta 1.3.10, Polycyclic 2.16, PrimGrp 3.4.4, RadiRoot 2.9, ResClasses 4.7.3, SmallGrp 1.5.3, Sophus 1.27, TomLib 1.2.11, 
             TransGrp 3.6.5, utils 0.85
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

## The Fix

This test fails because `user_pref_list.xml` is in `doc/ref` in the source tree, but not in `share/gap/doc/ref` (the path returned by `DirectoriesLibrary`). I think this could be fixed one of two ways:
1. Symlink `doc/ref/user_pref_list.xml` to `tst/testinstall/files/` and change `tst/testinstall/userpref.g` accordingly
2. Force `user_pref_list.xml` to appear in `doc/ref/` (presumably by modifying `doc/make_doc.in`?)

I can contribute a patch, but I would like guidance on which of these approaches would be preferable.

(It would be difficult for me to check if this is a regression, as earlier versions of GAP fail to build using Clang 16; that being said, 81963ee8 seems to acknowledge this test failing.)

**Comment by fingolfin** [comment]
Ah yes. That test is there to verify `doc/ref/user_pref_list.xml` is up-to-date, but it fails in a GAP that was installed via `make install` because we don't install the sources for the documentation.

GAP didn't have a `make install` for several decades, so it is not surprising that a lot of things have some issues with such a GAP here and there; the test suite was not written with an installed GAP in mind.

As long as the tests are also not installed, your suggestion 1 would probably work.

I don't understand 2 unless you meant `PREFIX/share/gap/doc/ref/` instead of `doc/ref/` there?

Option 3 would be to modify `tst/testinstall/userpref.tst` to just silently pass if `ref/user_pref_list.xml` can't be located.

Option 4: delete `tst/testinstall/userpref.tst` and `doc/ref/user_pref_list.xml` from the repository and instead modify `doc/make_doc.in` to generate this XML file on the fly (and add it to `.gitignore`).


I don't like option 3 because it might also miss real issues?  Option 1 is probably easiest to implement. Option 4 to me seems like it is the "correct" solution?


@ThomasBreuer any thoughts from you on this?

**Comment by ThomasBreuer** [comment]
Creating/updating `doc/ref/user_pref_list.xml` automatically when processing the documentation is a good idea, and afterwards no test is necessary that the file is actually up-to-date.
I will create a pull request for that.

**Comment by Feyorsh** [comment]
> I don't understand 2

Yep, I meant `share/gap/doc/ref`, but I concur that option 4 is significantly better. Thanks for the help!
