### ISSUE TITLE
`ImmutableMatrix` strips memory from matrices when it shouldn't

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#5872]
Consider this output:
```
G:=GroupWithMemory(SL(4,16));
ImmutableMatrix(GF(4), G.1^5);
```

Expected output (what we got up to GAP 4.11):
```
gap> G:=GroupWithMemory(SL(4,16)); ImmutableMatrix(GF(4), G.1^5);
<matrix group with 2 generators>
<[ [ Z(2^2), 0*Z(2), 0*Z(2), 0*Z(2) ], [ 0*Z(2), Z(2^2)^2, 0*Z(2), 0*Z(2) ], [ 0*Z(2), 0*Z(2), Z(2)^0, 0*Z(2) ],
  [ 0*Z(2), 0*Z(2), 0*Z(2), Z(2)^0 ] ] with mem>
```

Actual output (since GAP 4.12):
```
gap> G:=GroupWithMemory(SL(4,16)); ImmutableMatrix(GF(4), G.1^5);
<matrix group with 2 generators>
[ [ Z(2^2), 0*Z(2), 0*Z(2), 0*Z(2) ], [ 0*Z(2), Z(2^2)^2, 0*Z(2), 0*Z(2) ], [ 0*Z(2), 0*Z(2), Z(2)^0, 0*Z(2) ],
  [ 0*Z(2), 0*Z(2), 0*Z(2), Z(2)^0 ] ]
```

An important part for triggering the issue is that that the input matrix is defined over GF(16), but the coefficients are all in GF(4). So the operation above is well-defined but needs to rewrite the matrix.

I noticed this because it caused a regression in the test suite of the ClassicalMaximals package when calling `recog` (so this affects `recog`)

**Comment by fingolfin** [comment]
Pretty sure this is the problem:
```
    if field=BaseDomain(matrix) then
      return Immutable(matrix);
    else
      return ImmutableMatrix(field,Unpack(matrix));   # <-- new after 4.11
    fi;
```
which is meant to fix a bug when the fields are different but, well, it strips the memory.

**Comment by ThomasBreuer** [comment]
As we have discussed today:
I agree with the idea that `ImmutableMatrix` needs a special method for objects in `IsObjWithMemory`, which unpacks the matrix, applies `ImmutableMatrix` to the result, re-packs this matrix with the original memory value, and returns the immutable variant of this object.

I guess there are more operations which need such special methods, and perhaps the filter `IsObjWithMemory` eventually needs a higher rank, since this filter may claim that it is the most important aspect of an object, which must always be honored.
