### ISSUE TITLE
Dynamic identifier assignment

### ISSUE THREAD

**Issue by vdlee37** [gap-system/gap#5881]
In a function, I need to give a local identifier a value, depending on circumstances. The function dynamically builds an assignment statement in a string by means of ```InputTextString()``` and then executes the statement through ```Read()```. However, the function's local variable is not updated. Instead, a global identifier in the ambient procedure is:

```
 ┌───────┐   GAP 4.14.0 of 2024-12-05
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-cygwin-default64-kv9
 Configuration:  gmp 6.3.0, GASMAN, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.2.1, AtlasRep 2.1.9, AutPGrp 1.11, Browse 1.8.21, CaratInterface 2.3.7,
             CRISP 1.4.6, Cryst 4.1.27, CrystCat 1.1.10, CTblLib 1.3.9, curlInterface 2.4.0, FactInt 1.6.3, FGA 1.5.0,
             Forms 1.2.12, GAPDoc 1.6.7, genss 1.6.9, IO 4.9.1, IRREDSOL 1.4.4, LAGUNA 3.9.7, orb 4.9.1,
             Polenta 1.3.10, Polycyclic 2.16, PrimGrp 3.4.4, RadiRoot 2.9, recog 1.4.3, ResClasses 4.7.3,
             SmallGrp 1.5.4, Sophus 1.27, SpinSym 1.5.2, StandardFF 1.0, TomLib 1.2.11, TransGrp 3.6.5, utils 0.85
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> a := 5;
5
gap> var := function()
>   local a;
>   a := 11;
>   Read(InputTextString("a := 10;"));
>   Read(InputTextString("Print(\"upshot: a = \",a,\"\\n\");"));
>   Print("result: a = ",a,"\n");
>   end;
function(  ) ... end
gap> var();
upshot: a = 10
result: a = 11
gap> a;
10
gap>
``` 
Question 1: what would be the correct way of executing a GAP assignment statement prepared in a string?
Question 2: the behaviour displayed above, is it as designed?

(I am running GAP 4.14.0 under Windows 11.)

**Comment by ChrisJefferson** [comment]
So, the short answer is that this is expected behaviour, and also this is a very well supported way of coding. Could you describe your algorithm more? Trying to avoid doing so much Read and InputTextString would be a good idea!

If you need to build up something to evaluate from a string, it's better to use `Eval`, then assign the result to the local variable (you of course need to use an if, or something similar, to decide which local variable to assign to).

**Comment by vdlee37** [comment]
Ok, thank you.

In the scenario I was considering, the _name_ of the local variable to be given a value is not known in advance. (It will be one of a series of predefined variables. The particular one is determined through user input at run time. Of course I could use an if, but I figured a single Read statement would be more elegant.)

**Comment by ChrisJefferson** [comment]
One thing you could do is use a record.

If you write `r := rec(a := 1, b := 2)`, then given a string `c := "a"`, `r.(c) := 7;` will set `r.a` to `7`. This also has the advantage of keeping variables set by users in a nice single variable, rather than letting them set variables you don't want them touching.

**Comment by vdlee37** [comment]
Ah, that is very useful. Thanks.
