### ISSUE TITLE
IsomorphismPcpGroupFromFpGroupWithPcPres errors out (Polycyclic package)

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-system/gap#595]
I have the following error, and I am unsure whether this is a bug or not. 
````
gap> F := FreeGroup("x", "y", "z");;
gap> x := F.1;; y := F.2;; z := F.3;;
gap> G := F/[x*y*x^(-1)*y^(-1), x*z*x^(-1)*z^(-1), z*y*z^(-1)*y^(-1), (x*y)^180, (x*y^5)^168];;
gap> IsomorphismPcpGroupFromFpGroupWithPcPres(G); time;Error, Generator 1 in rhs out of range (1-3) called from
SetPower( pcp, g, ExtRepOfObj( w ) 
 ); at /home/ghorvath/work/gap/pkg/polycyclic-2.11/gap/basic/collect.gi:246 c\
alled from
SetPower( ftl, i, rels.powersp[i] 
 ); at /home/ghorvath/work/gap/pkg/polycyclic-2.11/gap/basic/convert.gi:384 c\
alled from
FromTheLeftCollectorByRelations( gens, rels 
 ) at /home/ghorvath/work/gap/pkg/polycyclic-2.11/gap/basic/convert.gi:418 ca\
lled from
PcpGroupFpGroupPcPres( G 
 ) at /home/ghorvath/work/gap/pkg/polycyclic-2.11/gap/basic/convert.gi:436 ca\
lled from
<function "IsomorphismPcpGroupFromFpGroupWithPcPres">( <arguments> )
 called from read-eval loop at line 30 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
````
This happens even if I set the Abelian factor for this group, or if I decrease the exponents to 2. In fact, this even happens if I invert the relators (and thus GAP recognizes G to be Abelian instantly).

**Comment by fingolfin** [comment]
The function `IsomorphismPcpGroupFromFpGroupWithPcPres` only works on fp groups with a polycylic presentation, that is, all relators must correspond in an `obvious` way to relations of the form `x_i^{x_j} = w` or `x_i^{r_j} = w` where `w` is a word in normal form, `r_j` a natural number, and `j < i`. Your presentation is not in this form, and thus not a valid input. For example, the relator `(x*y)^180` is not of this form.

[ A general remark: It is usually pointless to submit issues with packages here, because the people to fix those issues typically are package authors, and  most of them do NOT read our issue tracker. Thus somebody then needs to notify the package maintainer about your issue, etc. -- it is  usually a better idea to directly contact the package maintainer(s).

In this particular case, you are lucky, because I happen to be one of the polycylic maintainers... :-) ]
