### ISSUE TITLE
GAP's jenkins server is using an invalid SSL certificate

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#608]
I tried to look at a result of the Jenkins test server at https://keith.cs.st-andrews.ac.uk:8443 but my browser wouldn't let me without adding a security exception, because that server is using an invalid certificate.

It would be really nice to get this fixed.

I can even  help -- doing this shouldn't be hard, we could e.g. use https://letsencrypt.org/

**Comment by markuspf** [comment]
Alex and I have discussed a slightly different approach: I'll get a machine here on which we can run our own jenkins on (because at the moment the jenkins instance is shared between us and other members of CIRCA), then get https://ci.gap-system.org/ and run coverage/jenkins/etc from there (note: not *on* there).

This has the advantage that we can publish all the results, and we'll have a proper SSL certificate.

I'll send an email to our IT guys now.

**Comment by fingolfin** [comment]
That sounds great, thank!

**Comment by fingolfin** [comment]
Seems that the certificate for https://keith.cs.st-andrews.ac.uk:8443/ has been fixed at some point.

And there is now https://ci.gap-system.org/ -- but that does not have a valid SSL certificate...

So we could either close this issue, or else rename it to be about https://ci.gap-system.org/ ?

**Comment by markuspf** [comment]
Max Horn writes:

> So we could either close this issue, or else rename it to be about https://ci.gap-system.org/ ?

I just fixed the certificate for https://ci.gap-system.org, I just don't
know what we want to have available under that URL?

Our IT people pretty explicitly said we shouldn't make jenkins
world-accessible at some point...

**Comment by markuspf** [comment]
I don't think this is really relevant anymore.
