### ISSUE TITLE
"no method found" points to the wrong line of code

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#616]
When I run

``` gap
f := function() 
  local l;
  l := 0 * [1..6];
  l[[1..3]] := 1;
end;
f();
```

I get the error msg

``` gap
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `[]:=' on 3 arguments called from
0 * [ 1 .. 6 ] at stream:3 called from
<function "f">( <arguments> )
 called from read-eval loop at line 5 of stream
...
```

although `l[[1..3]] := 1;` is the offending part of code.
This does not happen with my version of GAP 4.7.9.

**Comment by ChrisJefferson** [comment]
This has actually also got worse in the GAP 4.8 betas. I will investigate.

**Comment by ChrisJefferson** [comment]
Further investigation (for my own records mainly). The problem is that this used to be invalid because you can only index lists with integers. Now it's invalid because we can index lists with anything, but `l` in particular doesn't do indexing by a range, so the underlying error was always there (wrong marking of place where error occurs), but it didn't show up before.

**Comment by fingolfin** [comment]
This problem also occurs in plain GAP.

**Comment by fingolfin** [comment]
For some background: this is because we don't call `SET_BRK_CALL_TO` enough. I do have a fix for that ready; the main thing missing is a collection of tests which verify this doesn't break other things, and also ensuring this doesn't regress.
I.e. I want a bunch of tests which record the reported error, in different scenarios.
