### ISSUE TITLE
Union(Rationals,Integers) <> Rationals

### ISSUE THREAD

**Issue by Stefan-Kohl** [gap-system/gap#644]
In 4.8.2, we get the following wrong results:

```
gap> Union(Rationals,Integers) <> Rationals;          
true
gap> Union(Rationals,Integers) = Rationals;
false
gap> Union(Rationals,NonnegativeIntegers) = Rationals;
false
gap> Union(Rationals,Cyclotomics) = Cyclotomics;
false

**Comment by alex-konovalov** [comment]
Same in GAP 4.7.9. But where is `Union(Rationals,Integers)` defined? `gap -r -A` returns no-method-found, so is it in some package?

**Comment by ChrisJefferson** [comment]
This is coming from CRISP, classes.gi:

```
InstallMethod (Union2, "for two classes/lists/collections", true, 
    [IsListOrCollection, IsListOrCollection], 0, 
    function (C, D)
        return NewClass ("class union fam", IsClassByUnionRep,
            rec (united := [C,D]));
    end);
```

I'm not sure what that is doing, but it looks like it is maybe grabbing too much -- anywhere that `Union2` otherwise isn't defined.

**Comment by Stefan-Kohl** [comment]
I'd say since the results in general do not behave correctly w.r.t. \=, the method is wrong.

**Comment by fingolfin** [comment]
@bh11 may want to comment

**Comment by bh11** [comment]
This problem must have been around for 15 years, I think.

@ChrisJefferson The generic Union2 code in CRISP is supposed to create representations of such unions. This is needed for creating group classes which (must) contain groups from different families. As a consequence, classes have their own family.

Generally, for these generic classes, it's not possible to decide equality, so, as defined in the CRISP manual, two classes are equal only if they are the same GAP object. Probably I should have extended the definition in CRISP to explicitly say that a class cannot be equal to any other GAP object – in this sense, the above results would be correct (but admittedly unfortunate).

The "wrong" answers come from a GAP library function that decides that two objects cannot be equal if they have different families. 

I'm not sure what's the best solution for the above and related problems:

1. just amend the definition in CRISP so that the above results are technically correct but not what you'd expect mathematically (maybe a bit like `1 + x - x = 1` being `false` when x=X(Rationals), or the recent case where residue class unions needed to be handled as multisets, not as ordinary set unions)

2. let CRISP try to assign the right family to such unions (then the above code will probably run into an infinite loop or "no method found" error)

3. let CRISP ignore unions where neither of the operands is a class

4. remove the requirement that GAP can always compare objects via `\=`, and in particular the method returning `false` if families don't match

5. …

Regardless of whether one chooses 1), 2), or 3), there will always be cases when a class that is a proper set will be mathematically equal to some collection in GAP but one will get a "wrong" answer. 4) might be the best solution mathematically but would probably break the GAP code for inhomogeneous lists and potentially a lot more, so probably it isn't a viable option.

Any opinions?

**Comment by Stefan-Kohl** [comment]
I'd say, make CRISP's Union2 method applicable only to CRISP classes. This should solve the problem.

**Comment by stevelinton** [comment]
I'd support Stefan's suggestion (your 3). I think mathematically you need to consider your classes as being in a new universe distinct from (in the sense of unequal to) other kinds of set or collection.  This is a little unintuitive, (like the 1+x-x <> 1 thing) but at least clear and logically consistent.

There is also a meta-principle that a package should only very rafrely change the defined behaviour of already-existing objects. It can extend that behaviour, supply faster methods that implement the same behaviour or introduce new objects with whatever properties, but it should not simply change the way existing objects work.

**Comment by bh11** [comment]
Thanks @Stefan-Kohl and @stevelinton. I've made the suggested change (similarly for Intersection and Difference), so the problem should be resolved once the new package version has been picked up.

**Comment by alex-konovalov** [comment]
Thanks @bh11, CRISP 1.4.3 of 29/02/2016 has been picked up and now "no-method-found" error is produced both with and without CRISP - issue closed.
