### ISSUE TITLE
Misleading error message when missing `()` from function call

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#822]
### Observed behaviour

```
gap> f := function() Stabilizer; end;
Syntax error: := expected
f := function() Stabilizer; end;
```
### Expected behaviour

Perhaps `:= or () expected`? We could also expect `.`, `[]`, but I think the function call or brackets are what we want.

**Comment by fingolfin** [comment]
Actually, I always found this one a bit annoying
```gap
gap> Stabilizer;;
gap> if false then Stabilizer; fi;
Syntax error: := or ::= expected
if true then Stabilizer; fi;
                       ^
```
I understand why it is that way; but it defeats the "poor man's #if 0" trick I sometimes use during development... So I wonder whether we want to produce an error here, instead of just warning?

As to the message: Perhaps it could explain the actual problem instead? I.e. "Found an isolated identifier, expected a statement; perhaps you forgot () or := ?" or so... well, that's clearly bad, but I hope my point gets across?

Finally, note that just adding := or [BLA] or . alone would not make the syntax error go away! So one might argue that the message should only mention () - or else it should be more verbose and explain that "something is missing" in more detail.

**Comment by ChrisJefferson** [comment]
It would be very easy to switch to C-like behaviour, where we just allow `<identifier>` as an expression

How about `Syntax Warning: expression has no effect`?

**Comment by fingolfin** [comment]
That would be fine by me.

**Comment by fingolfin** [comment]
We could also do something like this:
```patch
diff --git a/src/read.c b/src/read.c
index 8638a468b6..b8a677469e 100644
--- a/src/read.c
+++ b/src/read.c
@@ -806,7 +806,7 @@ static void ReadCallVarAss(TypSymbolSet follow, Char mode)
             }
         }
         else {
-            Match( S_ASSIGN, ":=", follow );
+            Match( S_ASSIGN, "got an expression, but statement", follow );
             UInt currLHSGVar = ReaderState()->CurrLHSGVar;
             if ( LEN_PLIST(STATE(StackNams)) == 0 || !STATE(IntrCoding) ) {
                 ReaderState()->CurrLHSGVar = (ref.type == R_GVAR ? ref.var : 0);
```
Then we'd get this:
```
gap> f := function() Stabilizer; end;
Syntax error: got an expression, but statement expected
f := function() Stabilizer; end;
                          ^
```
But of course there are might be other situations where this new error message is rather inappropriate... Can't think of any right now, but that just means I am tired and have bad imagination.
