### ISSUE TITLE
IsObject is not a filter

### ISSUE THREAD

**Issue by LiftnLearn** [gap-system/gap#861]
### Observed behaviour
gap>IsFilter(IsObject)
false
### Expected behaviour
gap>IsFilter(IsObject)
true
### Copy and paste GAP banner (to tell us about your setup)
 ┌───────┐   GAP v4.8.3-697-ga70a755 of 2016-07-06 13:57:09 (UTC)
 │  GAP  │          |     http://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64

**Comment by stevelinton** [comment]
IsObject is actually just ReturnTrue, since it holds for every object. In a few cases in the library you see tests like

IsFilter(x) or IsIdenticalObj(x,IsObject) 

so I suspect it's better to add the test in IsFilter. I don't think you can add IsObject to FiLTERS because positions in that list correspond to bit positions in flags lists and IsObject is the empty flags list.
