### ISSUE TITLE
Wrong number of group generators

### ISSUE THREAD

**Issue by mike352** [gap-system/gap#929]
The dihedral group D8 only has 2 generators, but GAP shows that it has 3:
gap> D:=DihedralGroup(8);
pc group of size 8 with 3 generators
gap> IdGroup(D);
[ 8, 3 ]

I can construct D8 myself using the following sequence:
gap> F := FreeGroup(2);;
gap> DD := F/[F.1^4, F.2^2, F.2 * F.1 * F.2 * F.1];;
gap> IdGroup(DD);
[ 8, 3 ]
and both the official group and the constructed one give the same ID [8,3].

Likewise, I can ask GAP for the generators, and though they have the same group ID they have different numbers of generators:
gap> GeneratorsOfGroup(D);
[ f1, f2, f3 ]
gap> GeneratorsOfGroup(DD);
[ f1, f2 ]

Something is wrong with the counting and construction of generators for the dihedral group, which it should be noted is a very common group!

I'm running GAP on Kubuntu, using the most recent version available from the download page here:
http://www.gap-system.org/Releases/index.html
which after compiling and running gives me
gap> GAPInfo.Version;
"4.7.9"
So as far as I can tell, version 4.8.5 is not available yet for download for Linux, and someone else will have to check the newest version for this issue.

**Comment by fingolfin** [comment]
This is not a big. Generating sets are not uniquely defined.

**Comment by fingolfin** [comment]
E.g. for any grozp G, the whole group (viewed as a set) is a generating set.

**Comment by markuspf** [comment]
To give a bit more background:

By default GAP uses a polycyclic presentation for Dihedral groups.
This requires one more generator, but there are efficient methods to deal with polycyclic groups (See also [Chapter 46 of the GAP manual](http://www.gap-system.org/Manuals/doc/ref/chap46.html))

**Comment by markuspf** [comment]
Regardless of the techincal issues, thank you for taking the time to report your issue, and giving complete information about it.

It seems that you have installed a rather old GAP version from your distribution, even though your issue is unrelated to this. It is unfortunate that updates for GAP take a long time to filter through to distributions like Ubuntu. We are working on a solution for that.

**Comment by ssiccha** [comment]
@mike352 If I understand you correctly you said that you are using
http://www.gap-system.org/Releases/index.html
to download the latest GAP distribution and compile it via `./configure; make`?
I am using Kubuntu too and 4.8.5 from the page you linked works fine for me.

**Comment by alex-konovalov** [comment]
thanks @ssiccha - was just writing more or less the same. The page http://www.gap-system.org/Releases/index.html always points to the latest GAP release, and that is GAP 4.8.5 at the moment. Maybe it was an old version of that page in the browser's cache (???).

The delay with GAP releases becoming available in Debian and Ubuntu via `apt` is taking place indeed due to their testing cycle. But those are alternative GAP distributions and your mileage may vary - for example, some GAP packages may not be installed automatically, and therefore capabilities of that installation may be reduced. Thus, my recommendation for Linux users is to always install GAP from source, and the source archives are available at http://www.gap-system.org/Releases/index.html immediately when the release is happening.

**Comment by markuspf** [comment]
The issue is that we do not provide at least a Debian/Ubuntu package.

On modern Ubuntus there is not even a C compiler available for instance, and I understand users wanting to just install the software and use it. It is us who have to provide this if we want people to use it.

**Comment by mike352** [comment]
While what you say is true, it's renders utterly meaningless the information given by GAP. For any new user who loads the built-in library of dihedral groups and immediately gets the statement that there are 3 generators, that new user will assume that the software is in beta and not to be trusted. In such a case, the statement is misleading, but in the case of the function GeneratorsOfGroup, if it cannot return the correct minimum number of generators it is a completely useless function.

**Comment by mike352** [comment]
Concerning versions, I first installed it using apt-get install, but when I saw it was the old version I downloaded directly from 
http://www.gap-system.org/Releases/index.html
to be precise, this link:
http://www.gap-system.org/pub/gap/gap48/tar.gz/gap4r8p5_2016_09_25-11_49.tar.gz
and followed the instructions:
"Download one of the archives below, unpack it and run ./configure; make in the unpacked directory. Then change to the pkg subdirectory and call ../bin/BuildPackages.sh to run the script which will build most of the packages that require compilation"
After doing that, it still shows as version 4.7.9. I don't know what else I can do to be honest.

**Comment by alex-konovalov** [comment]
@mike352 regarding versions, how do you start GAP? You need to call `path-to-gap/gap4r8/bin/gap.sh` script. If you just typed `gap` then it started the version that you installed with apt-get, which is likely GAP 4.7.9. I suggest to uninstall GAP that came from apt-get, and then created a symlink `/usr/local/bin/gap` pointing to `bin/gap.sh` from your proper GAP installation (but you will have to remember to point it to a newer GAP after each upgrade to a new GAP release).

**Comment by alex-konovalov** [comment]
@mike352: please see `MinimalGeneratingSet` and `GeneratorsSmallest` - they return generating sets with special properties, and will indeed give you two generators.

**Comment by fingolfin** [comment]
@mike352 I disagree that this information is useless. Defining groups in terms of (usually non-minimal) generating sets is one of the fundamental ways to describe groups in computational group theory.  Many algorithms are centered around this notion.

Of course some people may initially (when beginning to learn about GAP in particular, and computational group theory in generally) be surprised by the non-minimality - for example, each time I teach a class of undergrads how to use GAP, I fully expect that some of them will fall into this trap. But then they have a great opportunity to learn, and information learned this way "in the trenches" tends to stick better than any theoretical knowledge anyway. I never mind, and am happy that they learn. After all, we once were beginners.

However, new users who draws from GAP's behavior in this case the incorrect conclusion that GAP is "beta quality", strike me asusers who (a) are still beginners (perhaps without realizing it), yet (b) considers their own abilities so superior that they do not even consider the possibility that their lack of knowledge might be the issue. Thus they immediately blame the software. 

Indeed, what sounds more plausible: That a software under development for more than two decades, with some of the world leading experts in computational group theory involved, gets something elementary as D_8 wrong; or that a new user, and a beginner in the field, knows it better than everybody else?

Now, there most definitely are lots of bugs in GAP (as in every software of that size), and I am sure lots of them *are* discoverable by beginners; and we are very glad to receive bug reports about them, so that we can improve them. But this is not one of these instances. And unless you are very, *very* sure you found one, I always recommend some humility when writing bug reports, and at least considering that you yourself are wrong. I certainly try to follow that advice myself when reporting bugs on any projects, even though (or perhaps *because*) I have decades of experience in software development and open source software.

Now, if you have further troubles using GAP, I recommend asking on the GAP Forum mailing list; or on https://math.stackexchange.com -- and if you encounter another "bug", perhaps first check there with others whether they agree it's a bug. Of course you are still welcome to report them here, but then please either be certain they are bugs, or else adjust the tone of your report.

Thank you!

**Comment by mike352** [comment]
@alex-konovalov Thank you very much - indeed I was starting it by typing gap, which was then using the apt-get version, and thank you for pointing me towards the functions MinimalGeneratingSet and GeneratorsSmallest. 

@ fingolfin You and I have an obvious disagreement about human-compter interaction and user interface, and I am against the notion that it is a feature for new users to fail to understand something simple just so that they can "learn something from it". This is a philosophy about software and how users interact with it, and I'm afraid we'll just have to agree to disagree about it respectfully. I meant no ill will in my initial report, and I apologize for the tone.

**Comment by ssiccha** [comment]
@mike352 @fingolfin I still remember being a little confused by these 'strange pc groups' and didn't know how to get a permutation representation, when I tried to use DihedralGroup for the first time. Maybe one could add an example to the documentation with the call `DihedralGroup( IsPermGroup, 10)`?

**Comment by alex-konovalov** [comment]
@ssiccha it may be better to add an entry to GAP F.A.Q, and not only for the dihedral group - if anyone wants to help to write this, please see https://github.com/gap-system/GapWWW/issues/23

**Comment by markuspf** [comment]
@ssiccha Why not submit a pull-request with that added example?

**Comment by ssiccha** [comment]
@markuspf I'll do that in a second. Have never fiddled with the GAP Doc thingy or whatever has to be adjusted there before.

**Comment by fingolfin** [comment]
@mike352 I disagree that this is what we disagree about :-).  There are many instances were I think GAP could and should be more user friendly. This, however, is not one of them...

My point is more like this: Every computer program (and in fact, *any* communication context) makes some basic assumption about some shared knowledge the user (resp. participants in the communication process) have. GAP presupposes some familiarity with terminology from mathematics and group theory. Hence, it expects you to know what a generating set is. Sure, it might explain what it is in the manual, but when you print a generating set, it does not also print out a definition.

In particular, it assumes that you know the different between a generating set, and a minimal generating set. Of course we could change the print routing from `a group with 3 generators` to `a group with 3 generators, which may or may not form a minimal generating set`. For some novice users, this *might* be helpful initially, but everybody else (in particular, anybody who uses GAP for more than a little bit) would be quickly fed up and annoyed by this. Just imaging how you'd react if your operating system would tell you, whenever a dialog with an OK button pops up: "Hi, this is a button. A button is... " and then gave you the full explanation. 

BTW, you might think that we should always use a minimal generating set. But then (a) you'd still have a problem if you incorrectly believe that a generating set is necessarily minimal (because at some point, you simply will encounter non-minimal ones, there is no sane way to avoid it), and (b) doing so is very expensive in general (and might take hours or years to compute) and in many contexts is not needed... Sure, we could make a special exception for "small" groups like D_8 (though, were exactly would you draw the line?). But as a teacher, I don't think that we would do a service to students if we did this.

In the end, the problem here was a misunderstanding of terminology on your side. Nothing to be ashamed of, happens to all of us all the time. You keep blaming GAP and our user interface design for it. But imagine your were writing an exam, and one of the questions was "Write down all generating sets for C_4", and you only wrote the two minimal ones. Would you expect full points? Would you blame the teacher for your misunderstanding? (Many students of course do... "But I would have known that answer, if only the question had been clearer"... but the question was clear. The sooner you admit this to yourself, the sooner you can learn and improve.

**Comment by fingolfin** [comment]
@ssiccha @alex-konovalov @markuspf We already have examples with `IsPermGroup` in the manual, e.g. in the entry for `CyclicGroup`.

One could argue that when trying to understand `DihedralGroup`, one is expected to read the full chapter (or at least the intro of that chapter), which explains this. But I agree it would be more user friendly to guide the user on this. So, perhaps add to the manual entry for every single of these commands a brief sentence like this: "To learn more about the meaning of the optional filter argument, read section X.Y`. And/or add explicit examples to each of them.

However, this should be discussed in a new issue. This one is getting way off-topic.
