### ISSUE TITLE
strings.tst not robust enough

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#947]
This is happening after merging PR #612 when running the test on Windows in Cygwin shell:
```
########> Diff in /proc/cygdrive/C/Users/jenkins/workspace/GAP-dev-compilers/G\
APCOPTS/64build/GAPREADLINE/readline/label/gcc-cygwin64/GAP-git-snapshot/tst/t\
estinstall/strings.tst:46
# Input is:
x:="\0xFF";
# Expected output:
"\377"
# But found:
"ÿ"
########
########> Diff in /proc/cygdrive/C/Users/jenkins/workspace/GAP-dev-compilers/G\
APCOPTS/64build/GAPREADLINE/readline/label/gcc-cygwin64/GAP-git-snapshot/tst/t\
estinstall/strings.tst:50
# Input is:
x:="A string with \0xFF Hex stuff \0x42 in it";
# Expected output:
"A string with \377 Hex stuff B in it"
# But found:
"A string with ÿ Hex stuff B in it"
########
```

On OpenSuse it looks even worse:

```
########> Diff in /home/hudson/workspace/GAP-dev-compilers/GAPCOPTS/64build/GA\
PREADLINE/readline/label/gcc481suse/GAP-git-snapshot/tst/testinstall/strings.t\
st:46
# Input is:
x:="\0xFF";
# Expected output:
"\377"
# But found:
"�"
########
########> Diff in /home/hudson/workspace/GAP-dev-compilers/GAPCOPTS/64build/GA\
PREADLINE/readline/label/gcc481suse/GAP-git-snapshot/tst/testinstall/strings.t\
st:50
# Input is:
x:="A string with \0xFF Hex stuff \0x42 in it";
# Expected output:
"A string with \377 Hex stuff B in it"
# But found:
"A string with � Hex stuff B in it"
########
strings
```

**Comment by markuspf** [comment]
This of course has little to do with #612, other than the added tests exposing the problem.

Though I don't understand the problem, who is manipulating what there?

**Comment by frankluebeck** [comment]
The output of ViewObj depends on the encoding of the terminal (which I think is sensible and intended behaviour). Unfortunately, there is no easy way for a program running in a terminal to find out the terminals output encoding. But GAP uses some heuristics which usually works. The guessed encoding is stored in  `GAPInfo.TermEncoding`.

In the example where you see a "ÿ" GAP probably assumes that the terminal is in latin1 encoding and since the string is a valid latin1-encoded string it displays that character directly. Nowadays it is more standard that your terminal is in UTF-8 encoding and since the string is not a valid UTF-8 encoded string the character is displayed in octal notation. 

The OpenSuse example looks as if the terminal is in UTF-8 encoding but `GAPInfo.TermEncoding` is `"latin1"`, so GAP sends the "ÿ" to the terminal but this is invalid output for this terminal.

(Not sure, what would be a more robust test. In this specific example one could probably set explicitly `GAPInfo.TermEncoding := "UTF-8";` which should not lead to a problem on any terminal because the expected output is ASCII.)

**Comment by alex-konovalov** [comment]
Thanks @frankluebeck. When I start GAP in the terminal on OpenSUSE, it reports `GAPInfo.TermEncoding = "UTF-8"`, but that may not be set when it's run by jenkins automatically. On some of the Jenkins slaves, `LANG` is set to `en_GB.UTF-8` but it happens that not on these two. I've set it now in the slave configuration - let's see if tests will pass.

**Comment by frankluebeck** [comment]
Yes, setting `LC_ALL` or `LANG` explicitly in the scripts for automatic test might be a solution.

**Comment by alex-konovalov** [comment]
Problem resolved by updating Jenkins slaves configuration.
