### ISSUE TITLE
Method dispatch idea: InstallEarlyMethod

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#955]
One long-running problem in GAP is that method dispatch for built-in lists can be very expensive.

This leads to methods like `First`, which do a pre-check before calling `FirstOp`, which does the actual dispatch. I've played around to try to remove this cost, but it isn't possible in general without a complete change to how GAP does things.

Instead, here is an idea to make it easier to work around, a new function `InstallEarlyMethod`:

`InstallEarlyMethod(opr, method)` installs `method` for `opr`. `method` is called before any other installed method is considered. Note that `method` is called even for arguments which do not satisfy the filter requirements of `opr`.

**Comment by fingolfin** [comment]
Interesting idea. But wouldn't this require some overhead for every single metod disparch, namley to check whether an "early" method has been installed?

**Comment by fingolfin** [comment]
And what would happen if multiple early methods get installed? Error on the second attempt? Perhaps we'd rhen also need a function to remove or eplace an early method?

**Comment by ChrisJefferson** [comment]
Good question about the multiple early methods. We could just allow them to stack up -- we don't currently have a way of removing installed methods?

Theere is no cost if we add another dispatch method, similar to how we already have the 'verbose' and 'non verbose' ones. When you first call `InstallEarlyMethod`, we will switch to the compatible dispatch method.

**Comment by fingolfin** [comment]
Note that the kernel already does something like this:

When invoking any kind of function object (including GAP functions, kernel functions, operations, attributes, properties), GAP looks into the function object for a "handler", a C pointer to a C function, which is called to do the work. For operations, this normally is `DoOperationNArgs` (or one of the thing wrappers around it, like `DoOperation0Args`, `DoOperation1Args` etc.). This is also the place where we compute the types of the arguments for method dispatch. For attributes this is `DoAttribute` resp. one of its relatives, etc.

But for some operations/attributes/properties/filters, GAP installs custom handlers. E.g. for `LENGTH` -- this is why `Length(list)` can computing the type of a given plist, and just returns its length immediately, very quickly. This setup also can be a bit confusing at times, if one just looks at the kernel code without knowing this.

To give a concrete example, `IsSSortedList` is such a kernel property. The C "handler" is `FuncIS_SSORT_LIST`, instead of the default `DoProperty`. The custom handler simply calls `IS_SSORT_LIST` on the kernel level, which in turn uses the TNUM to dispatch to a function in the `IsSSortListFuncs` array. In that array, we install two functions: `IsSSortListDefault` and `IsSSortListObject`. Here, `IsSSortListDefault` uses more generic list accessors like `LEN_LIST`, `ELMW_LIST` etc. to implement the check. For external tnums (i.e. user defined objects or tnums added by kernel extensions), `IsSSortListObject` is called, which simply defers to `DoProperty( IsSSortListProp, obj )` -- in other words, it does what the regular handler would have done, if it wasn't for `FuncIS_SSORT_LIST`. Finally, there is a kernel function `FuncIS_SSORT_LIST_DEFAULT` which allows calling `IsSSortListDefault` directly -- this can then be installed as a method for `IsSSortedList` as usual.

More examples can be found by grepping for `GVAR_FILTER` or `GVAR_OPER`.

Clearly `InstallEarlyMethod` could be implemented in a similar way: we'd just need a custom handler which calls the "early method"; if that early method calls `TryNextMethod` (i.e., returns `TRY_NEXT_METHOD`), we proceed as usual / call the original handler. We just need to store a pointer to the early method, as well as the pointer to the original handler somewhere.

**Comment by ssiccha** [comment]
I like this idea a lot. I'll have a look whether I can come up with something.

**Comment by fingolfin** [comment]
I was motivated to look at this again, and with a fresh look I realized this is much simpler to do than with my more complex past plan. The result is in PR #4557
